keptn/lifecycle-toolkit

- .gitignore
- README.md
- operator/Dockerfile
- operator/PROJECT
- operator/config/certmanager/certificate.yaml
- operator/config/certmanager/kustomization.yaml
- operator/config/certmanager/kustomizeconfig.yaml
- operator/config/default/kustomization.yaml
- operator/config/default/manager_webhook_patch.yaml
- operator/config/default/webhookcainjection_patch.yaml
- operator/config/manager/kustomization.yaml
- operator/config/webhook/kustomization.yaml
- operator/config/webhook/kustomizeconfig.yaml
- operator/config/webhook/manifests.yaml
- operator/config/webhook/service.yaml
- operator/go.mod
- operator/main.go
- operator/webhooks/pod_mutating_webhook.go
This PR introduces the skeleton for the mutating webhook, together with its required configuration
Fixes #3
> Bootstrap the mutating webhook controller

- README.md
> chore: Update README wording

- README.md
This PR bootstraps a new section in the readme to provide info on how the different component works.
Furthermore, I added the classic contribution shout-out at the bottom of the README.
> Introduce a How it works section in README

- lfc-scheduler/pkg/klcpermit/permit.go
- lfc-scheduler/pkg/klcpermit/service_manager.go
Resolves: https://github.com/keptn-sandbox/lifecycle-controller/issues/12
> feat: Add scheduler with annotations

- .github/workflows/validate-semantic-pr.yml
- adds a short pipeline to enforce semantic PRs in this repo
> ci: Add semantic PR check pipeline

- README.md
> Added description for webhook and workload

- README.md
Signed-off-by: Oleg Nenashev <o.v.nenashev@gmail.com>
> docs: Add GitHub Discussions badge and the App Lifecycle WG reference

- lfc-scheduler/Dockerfile
- operator/Dockerfile
> feat: Switch to distroless-base image

- CODEOWNERS
> chore: Add @mowies, @philipp-hinteregger, and @bacherfl as owners

- README.md
> chore: Added scheduler description into the README

- .github/workflows/CI.yaml
- Triggers a build everything CI run for release-please PRs
> ci: Trigger build everything for release-please PRs

- CODEOWNERS
> chore: Fix OWNERS file

- operator/controllers/keptntask/job_utils.go
Signed-off-by: RealAnna <anna.reale@dynatrace.com>
this would cause to create a job with possibly partial information
> fix: Missed error

- .github/workflows/release-please.yml
- adds a manual trigger for the release-please pipeline
> ci: Add a manual trigger for the release-please pipeline

- operator/api/v1alpha1/common/common.go
- operator/controllers/keptntask/controller.go
- operator/controllers/keptntask/function_utils.go
- operator/controllers/keptntask/job_utils.go
> fix: query jobs before creating

- lfc-scheduler/Makefile
- operator/Makefile
- operator/config/default/webhookcainjection_patch.yaml
> chore: added helpers in Makefile for local development

- operator/webhooks/pod_mutating_webhook.go
> fix(operator): Update workload if spec changes

- .github/workflows/CI.yaml
- fixes the conditional check within the CI pipeline in order to push images when pushes to the main branch occur.
> ci: Fix CI conditional check to push images on pushes to main

- release-please-config.json
- adjusts the configuration for conventional commits for release please towards keptn's usual config
> chore: Adjust conventional commit configuration

- .github/workflows/CI.yaml
- introduces caching for Go modules in the CI pipeline
> ci: Introduce Go caching

- .github/workflows/release.yml
- adds a separator into the operator release.yaml and changes the order of concatenation.
> ci: Fix the release pipeline

- README.md
> docs: Update manifest name in readme

- .github/workflows/release.yml
- release-please-config.json
- fixes some config options for release-please
> ci: Fix release please configuration file

- scheduler/cmd/scheduler/main.go
- scheduler/go.mod
- scheduler/go.sum
- scheduler/manifests/install/base/deployment.yaml
Note: The PR #145 contains a tutorial to make use of this feature
> feat(scheduler): Add support for OTel collector

- .gitignore
> build: Prepare release

- scheduler/Dockerfile
- scheduler/Makefile
- scheduler/cmd/scheduler/main.go
Closes #96 
From the stdout exporter: 
```
"Resource": [
{
"Key": "service.name",
"Value": {
"Type": "STRING",
"Value": "keptn-lifecycle-scheduler"
}
},
{
"Key": "service.version",
"Value": {
"Type": "STRING",
"Value": "latest-22a9cdf9737754f7d824b0e8365ef1032f344027-2022-10-12_08:58:12"
}
},
{
"Key": "telemetry.sdk.language",
"Value": {
"Type": "STRING",
"Value": "go"
}
}
```
> feat(scheduler): Add OTel Resource Attributes

- scheduler/cmd/scheduler/main.go
> feat(scheduler): Disable gRPC logs when creating OTLP exporter

- examples/podtatohead-deployment/manifest.yaml
- examples/podtatohead-deployment/post-deployment-tasks.yaml
- functions-runtime/entrypoint.sh
- operator/api/v1alpha1/keptntask_types.go
- operator/config/crd/bases/lifecycle.keptn.sh_keptntasks.yaml
- operator/config/manager/kustomization.yaml
- operator/config/manager/manager.yaml
- operator/controllers/keptntask/function_utils.go
- operator/controllers/keptntask/job_utils.go
- release-please-config.json
BREAKING CHANGE: As the context has been added to the controller and is passed over to functions, a new function runner is needed.
> feat(operator): Added minimal context information

- README.md
- examples/podtatohead-deployment-k8s-labels/.gitignore
- examples/podtatohead-deployment-k8s-labels/README.md
- examples/podtatohead-deployment-k8s-labels/app.yaml
- examples/podtatohead-deployment-k8s-labels/check_entry.yaml
- examples/podtatohead-deployment-k8s-labels/manifest.yaml
- examples/podtatohead-deployment-k8s-labels/post-deployment-tasks.yaml
- operator/api/v1alpha1/common/common.go
- operator/config/manager/kustomization.yaml
- operator/webhooks/pod_mutating_webhook.go
- scheduler/manifests/install/kustomization.yaml
- scheduler/pkg/klcpermit/workflow_manager.go
> feat(operator): add fallback behavior when no keptn annotations are set 

- examples/podtatohead-deployment/manifest.yaml
- operator/webhooks/pod_mutating_webhook.go
> feat(operator): Allow pre- and post-deployment tasks as labels or annotations

- operator/config/default/webhookcainjection_patch.yaml
We must forbid  keptn-lifecycle-controller-system in webhook
> feat: Namespace keptn-lifecycle-controller-system should never call webhook

- README.md
- examples/observability/README.md
> docs: Add documentation for OTel collector as pre-requisite

- operator/api/v1alpha1/common/phases.go
> feat(operator): Fix phase naming

- operator/api/v1alpha1/keptntask_types.go
- operator/api/v1alpha1/semconv/semconv.go
- operator/config/crd/bases/lifecycle.keptn.sh_keptntasks.yaml
- operator/controllers/keptnappversion/reconcile_prepostdeployment.go
- operator/controllers/keptntask/job_utils.go
- operator/controllers/keptnworkloadinstance/reconcile_prepostdeployment.go
> chore(operator): Add workload and app version to KeptnTask

- README.md
Part of #202 
Signed-off-by: Oleg Nenashev <o.v.nenashev@gmail.com>
> docs: Update the repository links in README after the org migration

- examples/argo/README.md
- examples/flux/README.md
> docs: Fix name of keptnappversions

- operator/api/v1alpha1/keptnapp_types.go
- operator/api/v1alpha1/keptnappversion_types.go
- operator/api/v1alpha1/keptnworkload_types.go
- operator/api/v1alpha1/keptnworkloadinstance_types.go
- operator/api/v1alpha1/semconv/semconv.go
- operator/config/crd/bases/lifecycle.keptn.sh_keptnapps.yaml
- operator/config/crd/bases/lifecycle.keptn.sh_keptnappversions.yaml
- operator/config/crd/bases/lifecycle.keptn.sh_keptnworkloadinstances.yaml
- operator/config/crd/bases/lifecycle.keptn.sh_keptnworkloads.yaml
- operator/controllers/keptnapp/controller.go
- operator/controllers/keptnappversion/controller.go
- operator/controllers/keptnappversion/reconcile_workloadsstate.go
- operator/controllers/keptnworkload/controller.go
- operator/controllers/keptnworkloadinstance/controller.go
From #209 
* Added Status Information for the Phases
* Added Failed and Progressing States to WorkloadInstances and AppVersions
* Added Overall State to AppVersions and WorkloadInstances
* Added Last Version Information to AppVersions and WorkloadInstances
> feat(operator): Improve state and phase information

- .gitignore
- examples/observability/Makefile
- examples/observability/assets/export.sh
- examples/observability/assets/grafana_dashboard_applications.json
- examples/observability/assets/grafana_dashboard_overview.json
- examples/observability/assets/grafana_dashboard_workloads.json
- examples/observability/config/prometheus/grafana-config.yaml
- examples/observability/config/prometheus/grafana-dashboardDatasources.yaml
- examples/observability/config/prometheus/grafana-deployment.yaml
Extracted from #209 
- Added some dashboards
- Pre-configured Jaeger Datasource in Grafana
- Updated Grafana
> feat: Add Dashboards for Applications and Workloads

- operator/api/v1alpha1/keptnappversion_types.go
- operator/api/v1alpha1/keptnworkloadinstance_types.go
- operator/controllers/keptnapp/controller.go
- operator/controllers/keptnappversion/controller.go
- operator/controllers/keptnworkloadinstance/controller.go
Build on top of #211 
Extracted from #209 
- Added an Additional Trace for the Deployment itself
- Fixed Trace Information
> feat(operator): Add separate trace for Deployment

- operator/controllers/keptnworkloadinstance/controller.go
> fix(operator): Fix nil pointer exception in case of app not being found

- scheduler/go.sum
> chore(deps): Update dependencies

- scheduler/pkg/klcpermit/workflow_manager.go
> fix(scheduler): Fix the status the scheduler is acting on (preDeploymentEvaluationStatus)

- .github/workflows/validate-semantic-pr.yml
- renovate.json
- changes renovate PR titles from `deps(deps): ...` to `deps: ...`
> ci: Fix renovate semantic PR titles

- .github/workflows/CI.yaml
- fixes the CI pipeline
- adds debugging output for get_run_type step
> ci: Fix missing manifests

- .github/workflows/CI.yaml
- README.md
- codecov.yml
- adds coverage reporting via https://codecov.io 
Fixes #298
> ci: Introduce code coverage reporting

- .github/workflows/release.yml
- signs released images using sigstore/cosign with keyless signing enabled
Fixes #268
> feat: Sign released container images with sigstore/cosign

- scheduler/pkg/klcpermit/permit.go
this change  is also good for testing purposes
> fix(scheduler): The client should inherit framework configs

- operator/api/v1alpha1/keptnappversion_types.go
- operator/api/v1alpha1/keptnworkloadinstance_types.go
- operator/controllers/common/interfaces.go
- operator/controllers/common/spanhandler.go
- operator/controllers/common/spanhandler_test.go
This PR closes #326 and also corrects some receiver names
> fix(operator): Use correct Span Names

- examples/kubecon-na-22-demo/Makefile
- examples/kubecon-na-22-demo/README.md
- examples/observability/assets/grafana_dashboard_applications.json
- examples/observability/assets/grafana_dashboard_workloads.json
- operator/config/manager/kustomization.yaml
- scheduler/manifests/install/kustomization.yaml
> chore: update grafana dashboards

- .github/workflows/release.yml
> ci: Fix operator name in release pipeline

- .ci/mlc_config.json
- .github/workflows/check-links.yaml
- examples/argo/README.md
- examples/observability/README.md
> ci: check links in markdown files

- CODEOWNERS
> chore(scheduler): make RealAnna codeowner

- examples/argo/Makefile
- examples/argo/README.md
- examples/kubecon-na-22-demo/Makefile
- examples/kubecon-na-22-demo/README.md
- examples/kubecon-na-22-demo/version-2/app-pre-deploy-eval.yaml
- examples/kubecon-na-22-demo/version-3/app-pre-deploy-eval.yaml
- examples/observability/Makefile
- examples/observability/README.md
- examples/single-service/deploy.yaml
- examples/single-service/pre-deployment-tasks.yaml
- examples/taskonly-hello-keptn/http/task.yaml
- examples/taskonly-hello-keptn/inline/task.yaml
- examples/taskonly-hello-keptn/inline/taskdefinition.yaml
- examples/taskonly-hello-keptn/upstream/task.yaml
- examples/taskonly-hello-keptn/upstream/taskdefinition_upstream.yaml
- operator/controllers/keptntask/controller.go
- release-please-config.json
> fix: Fixed problems in examples

- operator/config/rbac/role.yaml
- operator/controllers/common/errors.go
- operator/controllers/keptnworkloadinstance/controller.go
- operator/controllers/keptnworkloadinstance/controller_test.go
- operator/controllers/keptnworkloadinstance/reconcile_deploymentstate.go
- operator/test/component/workloadinstancecontroller_test.go
- test/integration/simple-daemonset-annotated/00-assert.yaml
- test/integration/simple-daemonset-annotated/00-install.yaml
- test/integration/simple-daemonset-annotated/00-teststep.yaml
- test/integration/simple-daemonset-annotated/01-assert.yaml
- test/integration/simple-daemonset-annotated/02-assert.yaml
- test/integration/simple-daemonset-annotated/02-install.yaml
> fix(operator): Also consider StatefulSets/DaemonSets when checking Workload Deployment state

- README.md
Signed-off-by: Andreas Grabner <grabnerandi@gmx.at>
> docs: adding reference to youtube video

- operator/test/component/appcontroller_test.go
Signed-off-by: RealAnna <anna.reale@dynatrace.com>
> test: Fix flacky component test

- operator/controllers/keptntask/controller.go
- operator/controllers/keptntask/job_utils.go
- operator/controllers/keptntask/job_utils_test.go
- operator/test/component/taskcontroller_test.go
> fix(operator): detect Job failure and set Task to failed

- codecov.yml
- operator/controllers/common/test_utils.go
- operator/controllers/keptnapp/controller_test.go
- operator/controllers/keptnappversion/controller_test.go
- operator/controllers/keptnworkloadinstance/controller.go
- operator/controllers/keptnworkloadinstance/controller_test.go
- fixes a small bug that was actually a typo in the end
- adds unit tests
- adds `test_utils.go` to the codecov ignore list
Fixes #416
> fix(operator): increment the correct meter to show deployment count

- operator/Dockerfile
- scheduler/Dockerfile
> fix(operator): build env variables are computed during docker build

- .github/workflows/CI.yaml
- .github/workflows/e2e-test.yml
- .github/workflows/golangci-lint.yml
- .github/workflows/integration-test.yml
- .github/workflows/performance-test.yml
- .github/workflows/release.yml
- adds more annotations for renovate so that auto updates catch all occurrences of some of our used packages
> deps: add more renovate annotations for auto updates

- renovate.json
- adds yaml files to the custom renovate regex matcher so that dependency versions in pipelines are also taken into account
> deps: add yaml files to renovate

- operator/api/v1alpha1/keptnapp_conversion.go
- operator/api/v1alpha1/keptnapp_conversion_test.go
- operator/api/v1alpha2/common/common.go
- operator/api/v1alpha2/common/common_test.go
- operator/api/v1alpha2/common/phases.go
- operator/api/v1alpha2/keptnapp_types.go
- operator/api/v1alpha2/keptnappversion_test.go
- operator/api/v1alpha2/keptnappversion_types.go
- operator/api/v1alpha2/keptnworkloadinstance_test.go
- operator/api/v1alpha2/keptnworkloadinstance_types.go
- operator/config/crd/bases/lifecycle.keptn.sh_keptnapps.yaml
- operator/config/crd/bases/lifecycle.keptn.sh_keptnappversions.yaml
- operator/controllers/common/phasehandler.go
- operator/controllers/common/phasehandler_test.go
- operator/controllers/interfaces/fake/phaseitem_mock.go
- operator/controllers/interfaces/phaseitem.go
- operator/controllers/interfaces/phaseitem_test.go
- operator/test/component/workloadinstancecontroller_test.go
- scheduler/go.mod
- scheduler/go.sum
- scheduler/pkg/klcpermit/workflow_manager.go
- scheduler/pkg/klcpermit/workflow_manager_test.go
- test/integration/api-conversion/00-assert.yaml
- test/integration/api-conversion/00-install.yaml
Part of #472
This PR as a preparation for https://github.com/keptn/lifecycle-toolkit/pull/544
> chore(operator): refactor operator and scheduler statuses + add unit tests

- operator/controllers/keptnworkloadinstance/controller_test.go
Closes #550 
Note: The problem in the referenced issue has already been solved in the meantime (since 0.4.1), but these tests make sure that this error does not happen again in the future
> test(operator): add more unit tests to check for readiness of referenced objects

- operator/Dockerfile
- renovate.json
- adds all Dockerfiles to renovate so that dependencies can be updated there
- adds controller tools in the operator dockerfile to renovate
> ci: add dockerfile support for renovate, add renovate comment in dockerfile

- test/integration/api-conversion/00-assert.yaml
- test/integration/api-conversion/00-install.yaml
- test/integration/api-conversion/01-assert.yaml
- test/integration/api-conversion/01-install.yaml
> test: added Kuttl tests to check conversion webhooks

- .golangci.yml
> chore: fail linter CI jobs when checks are failing

- .github/workflows/golangci-lint.yml
> chore: stop linter CI job on error

- .github/actions/update-documentation/action.yml
Should fix the following error:
https://github.com/keptn/lifecycle-toolkit/actions/runs/3939830984/jobs/6740153795
> ci: fix path for  docs auto update action

- .github/actions/update-documentation/action.yml
should fix this error: https://github.com/keptn/lifecycle-toolkit/actions/runs/3940243463/jobs/6741103645
> ci: fix python script flags

- .github/actions/update-documentation/action.yml
- should really really fix the docs auto update pipeline now :)
- adds a missing conditional that made the pipeline crash
- applies auto formatting
- changes the target branch to `main` so that real deployments will happen from now on
> ci: fix docs auto update again

- klt-cert-manager/Makefile
> fix: fix klt-cert-manager release-local Makefile target

- .github/workflows/CI.yaml
- .github/workflows/release.yml
Signed-off-by: Moritz Wiesinger <moritz.wiesinger@dynatrace.com>
> ci: fix pipeline step IDs

- klt-cert-manager/README.md
Signed-off-by: realanna <anna.reale@dynatrace.com>
> docs:  added breaking change message

- .github/scripts/generate-helm-docs.sh
- .github/workflows/validate-helm-docs.yml
- helm/chart/README.md
> ci: introduce pipeline for Helm docs validation

- Makefile
- klt-cert-manager/Makefile
- operator/Makefile
- scheduler/Makefile
> build: don't execute kustomize installation as part of other make commands

- docs/content/en/docs/getting-started.md
This PR:
- Alters "getting started" opening paragraph
Hopefully this makes the "mission statement" and "mechanics" of KLT a little clearer for first time readers.
Signed-off-by: agardnerit <adam@agardner.net>
> docs: update getting started wording

- .github/workflows/security-scans.yml
Signed-off-by: realanna <anna.reale@dynatrace.com>
> ci: remove duplicate manifests in security pipeline 

- .github/workflows/set-date.yml
- exchanges the used token in a pipeline and provides the correct one
> ci: use correct github access token

- .github/scripts/keptnevaluationprovider_migrator.sh
> feat(metrics-operator): introduce migration from KeptnEvaluationProvider to KeptnMetricsProvider

- netlify.toml
Improving netlify build with reduced calls, based on a more limited changeset
> docs: improve netlify build

- .github/workflows/htmltest.yaml
- docs/.htmltest.yml
- docs/Makefile
- docs/content/en/docs/concepts/architecture/_index.md
- docs/layouts/partials/navbar-version-selector.html
Fixed HTMLTest make target, and added a verification step for GitHub Actions.
> docs: add htmltest verification for documentation

- operator/test/component/evaluationcontroller_test.go
- operator/test/component/taskcontroller_test.go
- operator/test/component/taskdefinitioncontroller_test.go
- operator/test/component/workloadcontroller_test.go
- operator/test/component/workloadinstancecontroller_test.go
> test: generate resources names for each component test

- .github/workflows/validate-helm-docs.yml
- helm/chart/README.md
- helm/chart/doc.yaml
- helm/chart/values.yaml
- klt-cert-manager/config/manager/kustomization.yaml
- metrics-operator/config/manager/kustomization.yaml
- operator/config/manager/kustomization.yaml
- scheduler/manifests/install/kustomization.yaml
- adds data to helm chart README
-  forces validation pipeline to have all image TAG to refer to the next version of the chart to be released
> feat: fill in chart README

- operator/test/component/appversioncontroller_test.go
- operator/test/component/workloadinstancecontroller_test.go
> test: introduce component test for KeptnAppVersion controller + remove flakyness

- .github/scripts/generate-helm-docs.sh
- metrics-operator/pkg/metrics/server.go
- metrics-operator/pkg/metrics/server_test.go
make sure that metrics operator returns status code in case of error and not empty values
line 3 metrics not there, line 4 metric there but empty
> fix: remove missing 404 bug

- examples/support/observability/Makefile
- release-please-config.json
- adds the helm chart file to the release please config so that the auto-version-update should work there
> fix: add helm chart to release please config

- CONTRIBUTING.md
- docs/content/en/contribute/general/technologies/_index.md
> docs: technologies to get familiar before working with KLT

- operator/config/rbac/role.yaml
- operator/controllers/options/keptnconfig_controller.go
- Grants read-only RBAC permissions to the KeptnConfig controller
Parts of #1095
> chore(operator): read-only RBAC for KeptnConfig controller

- metrics-operator/controllers/common/providers/dynatrace/dynatrace.go
- metrics-operator/controllers/common/providers/dynatrace/dynatrace_test.go
> fix(metrics-operator): normalize Dynatrace URL

- .github/scripts/generate-crd-docs/generate-crd-docs.sh
- improves some user output that the script does while running
> chore: improve CRD docs generation script output

- docs/content/en/docs/snippets/tasks/install.md
- makes some smaller fixes in the getting started guide's installation instructions to make them work better
> docs: fix getting started instructions

- .github/workflows/CI.yaml
- test/integration/expose-keptn-metric/00-install.yaml
- test/integration/expose-keptn-metric/01-install.yaml
- test/integration/expose-keptn-metric/02-teststep.yaml
- fixes a YAML syntax bug introduced in #1174
> ci: fix CI pipeline YAML error

- examples/support/metrics/Makefile
- examples/support/metrics/deployment.yaml
- examples/support/metrics/metric.yaml
This PR fixes some minor issues with the metrics demo
> fix: fix metrics demo setup

- examples/sample-app/base/provider.yaml
> fix: fix kubecon examples

- README.md
> docs: add better overview KeptnApp to readme

- operator/test/component/app/app_suite_test.go
- operator/test/component/appversion/appversion_suite_test.go
- operator/test/component/evaluation/evaluation_suite_test.go
- operator/test/component/load/load_suite_test.go
- operator/test/component/task/task_suite_test.go
- operator/test/component/taskdefinition/taskdefinition_suite_test.go
- operator/test/component/workload/workload_suite_test.go
- operator/test/component/workloadinstance/workloadinstance_suite_test.go
adds retry to manager setup in tests.
> chore: fix failing component test

- helm/chart/README.md
- helm/chart/doc.yaml
- helm/chart/values.yaml
- metrics-operator/config/manager/manager.yaml
https://github.com/keptn/lifecycle-toolkit/actions/runs/4829540816
> chore(metrics-operator): add configuration parameters for container securityContext

- README.md
- docs/content/en/docs/concepts/keptnConfig/_index.md
- examples/support/keptn/keptnconfig.yaml
> docs: update KeptnConfig docs to include KeptnAppCreationRequestTimeout

- README.md
- docs/content/en/docs/concepts/evaluations/_index.md
- operator/controllers/common/helperfunctions.go
- operator/controllers/common/helperfunctions_test.go
- operator/controllers/lifecycle/keptnevaluation/controller.go
- operator/controllers/lifecycle/keptnevaluation/controller_test.go
- operator/test/component/evaluation/evaluation_test.go
> feat(operator): introduce fallback search to KLT default namespace when KeptnEvaluationDefinition is not found

- operator/apis/lifecycle/v1alpha3/keptntask_test.go
- operator/apis/lifecycle/v1alpha3/keptntask_types.go
- operator/controllers/lifecycle/keptntask/controller.go
- operator/controllers/lifecycle/keptntask/function_utils.go
- operator/controllers/lifecycle/keptntask/job_utils.go
- operator/controllers/lifecycle/keptntask/job_utils_test.go
- operator/test/component/task/task_test.go
> chore(operator): make use of status.jobName when searching for job in KeptnTask controller

- .github/.kubescape/controls-inputs.json
- .github/actions/deploy-klt-on-cluster/action.yml
- .github/workflows/CI.yaml
- .github/workflows/release.yml
- .github/workflows/validate-helm-chart.yml
- functions-runtime/README.md
- helm/chart/README.md
- helm/chart/values.yaml
- operator/config/manager/manager.yaml
- renovate.json
> fix: remove scarf redirect from containers images

- docs/go.sum
- operator/controllers/errors/errors.go
- operator/controllers/lifecycle/keptntask/container_builder.go
- operator/controllers/lifecycle/keptntask/job_utils.go
- operator/controllers/lifecycle/keptntask/js_builder.go
- operator/controllers/lifecycle/keptntask/js_builder_test.go
- operator/go.mod
- test/integration/simple-deployment-recursive-task/00-assert.yaml
- test/integration/simple-deployment-recursive-task/00-install.yaml
- test/integration/simple-deployment-recursive-task/00-teststep.yaml
- test/integration/simple-deployment-recursive-task/01-assert.yaml
> chore(operator): refactor keptntaskcontroller to use builder interface

- operator/apis/lifecycle/v1alpha3/common/common.go
- operator/apis/lifecycle/v1alpha3/common/common_test.go
- operator/apis/lifecycle/v1alpha3/keptnapp_types.go
- operator/apis/lifecycle/v1alpha3/keptnworkload_types.go
- operator/common/common.go
- operator/common/common_test.go
- operator/controllers/common/helperfunctions.go
- operator/controllers/common/helperfunctions_test.go
- operator/controllers/lifecycle/keptnapp/controller.go
- operator/controllers/lifecycle/keptnapp/controller_test.go
- operator/controllers/lifecycle/keptnappversion/reconcile_workloadsstate.go
- operator/controllers/lifecycle/keptntask/job_utils.go
- operator/controllers/lifecycle/keptntask/js_builder.go
- operator/webhooks/pod_mutator/pod_mutating_webhook.go
- operator/webhooks/pod_mutator/pod_mutating_webhook_test.go
- scheduler/pkg/klcpermit/workflow_manager.go
- scheduler/pkg/klcpermit/workflow_manager_test.go
> chore: standardize generation of resource names

- docs/content/en/docs/intro-klt.md
fix:#1503
added the link to the [Keptn Lifecycle Toolkit README file]
now its workiing fine
Signed-off-by: Nitishupkr [nitishupkr@gmail.com](mailto:nitishupkr@gmail.com)
> fix: added the missing link 

- docs/content/en/docs/getting-started/metrics/_index.md
> docs: updated the misspelled word

- docs/content/en/docs/intro-klt.md
> docs: fix typos

- docs/config/production/params.yaml
This should fix failing edit  links
> chore: website edit links should point to page

- docs/content/en/docs/yaml-crd-ref/evaluationdefinition.md
> docs: fix typo

- docs/content/en/contribute/docs/source-file-structure/_index.md
> docs: minor improvement for docs contribution guide

- docs/content/en/docs/getting-started/generic-gs/_index.md
> docs: fix installation steps in E2E example

- Makefile
- helm/chart/Chart.yaml
> fix(helm-chart): propagate labels for validation webhook

- .github/actions/deploy-klt-on-cluster/action.yml
- .github/workflows/CI.yaml
- .github/workflows/integration-test.yml
- test/integration/expose-keptn-metric/00-teststep.yaml
- test/integration/expose-keptn-metric/01-teststep.yaml
- test/integration/expose-keptn-metric/job-existing-metric.yaml
- test/integration/expose-keptn-metric/job-no-metric.yaml
- test/integration/keptn-config/get-logs.sh
- test/testcertificate/cert-recreates/00-assert.yaml
- test/testcertificate/cert-recreates/01-assert.yaml
- test/testcertificate/cert-recreates/02-assert.yaml
> ci: use helm-chart as default installation method

- docs/content/en/docs/getting-started/_index.md
Fixes: #1684 
Here I changed excercises text to exercises
> docs: excercises text changed to exercises

- operator/webhooks/pod_mutator/pod_mutating_webhook.go
- operator/webhooks/pod_mutator/pod_mutating_webhook_test.go
> fix: take last element in tag as Workload version number

- docs/content/en/docs/intro-klt.md
> docs: update intro-klt.md

- README.md
> feat: update stability of Certificate Manager

- docs/content/en/partials/_index-observability-left.md
Signed-off-by: geoffrey1330 <israelgeoffrey13@gmail.com>
fixes #1739
> docs: fixed typo Troubleshoort to Troubleshoot

- operator/webhooks/pod_mutator/pod_mutating_webhook.go
- operator/webhooks/pod_mutator/pod_mutating_webhook_test.go
> fix(operator): sanitize app name annotation from uppercase to lowercase

- docs/content/en/docs/yaml-crd-ref/evaluationdefinition.md
> docs: fixed typo

- docs/content/en/docs/crd-ref/metrics/v1alpha3/_index.md
This PR updates the auto generated docs to add the new field that has been added to the KeptnMetrics CRD
> docs: update auto generated docs to include `spec.range.step` in `KeptnMetric`

- .github/workflows/stale.yml
> ci: fix stale action

- docs/content/en/docs/yaml-crd-ref/crd-template.md
This PR fixes : #1858 
This PR was raised in order to create `crd-template.md` file in main as suggested by @RealAnna in #1876 
Reference: https://lifecycle.keptn.sh/docs/crd-ref/crd-template/
> docs: create crd-template.md

- renovate.json
> ci: fix functions-runtime renovate updates

- renovate.json
> ci: fix functions-runtime renovate updates again

- .github/workflows/CI.yaml
- .github/workflows/release.yml
- README.md
- docs/content/en/docs/install/install.md
- docs/content/en/docs/snippets/tasks/install.md
> revert: remove generation of KLT manifest releases

- docs/content/en/docs/concepts/architecture/components/scheduler/_index.md
- scheduler/README.md
Relate: #770
Fixes: #1682
signed-off-by: YashPimple [yashpimple22@gmail.com](mailto:yashpimple22@gmail.com)
> docs: keptn Scheduler architecture documentation

- docs/content/en/docs/intro-klt/_index.md
- docs/content/en/docs/migrate/metrics-observe/_index.md
> docs: small improvements

- .github/workflows/CI.yaml
- .github/workflows/e2e-test.yml
- .github/workflows/golangci-lint.yml
- .github/workflows/htmltest.yaml
- .github/workflows/integration-test.yml
- .github/workflows/load-test.yml
- .github/workflows/markdown-checks.yaml
- .github/workflows/performance-test.yml
- .github/workflows/release-examples.yml
- .github/workflows/security-scans.yml
- .github/workflows/set-date.yml
- .github/workflows/stale.yml
- .github/workflows/update-labels.yml
- .github/workflows/validate-helm-chart.yml
- .github/workflows/validate-semantic-pr.yml
- .github/workflows/yaml-checks.yaml
- remove the monitor action again since after checking, we already have the least amount of permissions in our pipelines
> chore: remove monitor action

- .release-please-manifest.json
- klt-cert-manager/CHANGELOG.md
- klt-cert-manager/Makefile
Signed-off-by: Moritz Wiesinger <moritz.wiesinger@dynatrace.com
This reverts commit a8c22f779eafd68ea12c97c808ad2041fc89acbf.
> revert: revert cert-manager release again

- docs/content/en/contribute/general/codespace/_index.md
This publishes the material about using Codespaces that @agardnerIT developed in https://github.com/keptn/lifecycle-toolkit/pull/1428 👍 
* A video that demonstrates using CodeSpaces
* A summary list of the steps to take, following what is in the video.
This section needs xrefs to other docs for topics like proper naming of a commit/PR and how to create a PR.  That will be done in a separate PR after other PRs are merged.
We may want to eventually expand this material to include more complicated examples such as creating a new file (rather than just modify an existing file), show how to run some basic tests on a software contribution, etc.  If warranted, this material can be added later.
> docs: how to use GitHub Codespaces to contribute to Keptn

- metrics-operator/converter/sli_converter.go
- metrics-operator/converter/slo_converter.go
- metrics-operator/converter/slo_converter_test.go
- metrics-operator/main.go
- support conversion of multiple criteria elements in pass criteria
- unit tests
- renamed converter parameters
Fixes: #2021
> feat(metrics-operator): support combination of OR criteria in SLO converter

- docs/content/en/docs/getting-started/_index.md
(cherry picked from commit a6e4d6542dd8989d7c46bc1ce24f15f449c0ca19)
Signed-off-by: Moritz Wiesinger <moritz.wiesinger@dynatrace.com>
> docs: improve getting started guide

- metrics-operator/converter/README.md
- metrics-operator/converter/sli_converter.md
- metrics-operator/converter/slo_converter.md
- release-please-config.json
Fixes: #2002
Depends on https://github.com/keptn/lifecycle-toolkit/pull/2023
> docs(metrics-operator): usage of SLI and SLO converters

- klt-cert-manager/config/default/kustomization.yaml
- lifecycle-operator/config/crd/kustomization.yaml
- lifecycle-operator/config/default/kustomization.yaml
- metrics-operator/config/crd/kustomization.yaml
- metrics-operator/config/default/kustomization.yaml
Closes #1775
Updated kustomiztion.yaml in configs
> fix: update kustomization.yaml to avoid usage of deprecated patches/configs

- docs/content/en/docs/implementing/tasks-non-k8s-apps.md
- lifecycle-operator/config/samples/function_execution/task_schedule.yaml
- lifecycle-operator/config/samples/function_execution/task_slack.yaml
> docs: adapt KeptnTask example to changes in API 

- metrics-operator/converter/common.go
- metrics-operator/converter/common_test.go
- metrics-operator/converter/sli_converter.go
- metrics-operator/converter/sli_converter_test.go
- metrics-operator/converter/slo_converter.go
- metrics-operator/converter/slo_converter_test.go
> fix(metrics-operator): convert SLI names to valid K8s resource names

- .github/scripts/.helm-tests/certificates-only/result.yaml
- .github/scripts/.helm-tests/certificates-only/values.yaml
- .github/scripts/.helm-tests/lifecycle-only/result.yaml
- .github/scripts/.helm-tests/lifecycle-only/values.yaml
- .github/scripts/.helm-tests/lifecycle-with-certs/result.yaml
- .github/scripts/.helm-tests/lifecycle-with-certs/values.yaml
- .github/scripts/.helm-tests/metrics-only/result.yaml
- .github/scripts/.helm-tests/metrics-only/values.yaml
- .github/scripts/.helm-tests/metrics-with-certs/result.yaml
- .github/scripts/.helm-tests/metrics-with-certs/values.yaml
> test: add helm tests for umbrella chart

- .github/scripts/.helm-tests/certificates-only/result.yaml
- .github/scripts/.helm-tests/lifecycle-only/result.yaml
- .github/scripts/.helm-tests/lifecycle-with-certs/result.yaml
- .github/scripts/.helm-tests/metrics-only/result.yaml
- .github/scripts/.helm-tests/metrics-with-certs/result.yaml
> fix: helm test

- .github/workflows/CI.yaml
- .github/workflows/validate-helm-chart.yml
- chart/doc.yaml
- chart/values.yaml
> chore: update pipelines to work with new helm charts

- docs/content/en/docs/install/upgrade.md
> docs: upgrade Keptn to Helm from a manifest installation

- docs/content/en/contribute/general/technologies/_index.md
- docs/content/en/contribute/software/dev-environ/_index.md
- docs/content/en/docs/intro/_index.md
Closes https://github.com/keptn/lifecycle-toolkit/issues/809 
This PR adds info from Ondrej's presentation at the 11 Sept New Contributors meeting.
Note that this has limited information about augmenting the test suites for a new feature.  I think that needs to be handled in a separate page.
> docs: how to use software dev environment

- docs/content/en/docs/getting-started/observability/_index.md
Replaces https://github.com/keptn/lifecycle-toolkit/pull/2286
Fixes https://github.com/keptn/lifecycle-toolkit/issues/2285
> docs: correct getting-started info about using KeptnConfig

- docs/content/en/docs/architecture/deployment-flow.md
- docs/content/en/docs/getting-started/usecase_metrics.md
- docs/content/en/docs/implementing/evaluatemetrics.md
- docs/content/en/docs/implementing/evaluations.md
- docs/content/en/docs/implementing/otel.md
- docs/content/en/docs/implementing/tasks-non-k8s-apps.md
- docs/content/en/docs/install/install.md
- docs/content/en/docs/install/k8s.md
- docs/content/en/docs/intro/_index.md
- docs/content/en/docs/intro/usecase-observability.md
- docs/content/en/docs/intro/usecase-orchestrate.md
- docs/content/en/docs/troubleshooting.md
- docs/content/en/docs/yaml-crd-ref/app.md
- docs/content/en/docs/yaml-crd-ref/config.md
- docs/content/en/docs/yaml-crd-ref/evaluationdefinition.md
> docs: add links to most workload word occurrences

- lifecycle-operator/controllers/common/evaluationhandler.go
- lifecycle-operator/controllers/common/evaluationhandler_test.go
- lifecycle-operator/controllers/common/helperfunctions.go
- lifecycle-operator/controllers/common/phasehandler.go
- lifecycle-operator/controllers/common/phasehandler_test.go
- lifecycle-operator/controllers/common/taskhandler.go
- lifecycle-operator/controllers/errors/errors.go
- lifecycle-operator/controllers/lifecycle/keptnapp/controller.go
- lifecycle-operator/controllers/lifecycle/keptnapp/controller_test.go
- lifecycle-operator/controllers/lifecycle/keptnappversion/controller.go
- lifecycle-operator/controllers/lifecycle/keptnappversion/controller_test.go
- lifecycle-operator/controllers/lifecycle/keptnappversion/reconcile_workloadstate_test.go
- lifecycle-operator/controllers/lifecycle/keptnevaluation/controller.go
- lifecycle-operator/controllers/lifecycle/keptnevaluation/controller_test.go
- lifecycle-operator/controllers/lifecycle/keptntask/controller.go
- lifecycle-operator/controllers/lifecycle/keptntask/job_utils.go
- lifecycle-operator/controllers/lifecycle/keptnworkload/controller.go
- lifecycle-operator/controllers/lifecycle/keptnworkloadversion/controller.go
- lifecycle-operator/main.go
- lifecycle-operator/test/component/app/app_test.go
- lifecycle-operator/test/component/evaluation/evaluation_suite_test.go
- lifecycle-operator/test/component/task/task_suite_test.go
- lifecycle-operator/test/component/workload/workload_test.go
> chore(lifecycle-operator): remove spans for reconciliation loops, adjust log levels

- chart/NOTES.txt
> chore: add NOTES to helm chart

- renovate.json
- enables renovate updates on the helm test result files that we have
> chore: enable renovate on helm test files

- docs/content/en/docs/install/assets/values-advance-changes.yaml
- docs/content/en/docs/install/assets/values-only-lifecycle.yaml
- docs/content/en/docs/install/assets/values-only-metrics.yaml
- docs/content/en/docs/install/assets/values-remove-certmanager.yaml
add example of values.yaml to document umbrella chart instalaltion
> chore: add example of values.yaml

- .github/workflows/CI.yaml
Fixes https://github.com/keptn/lifecycle-toolkit/actions/runs/6744546050/job/18334704029
> chore: fix helm chart sync workflow

- lifecycle-operator/test/component/workloadversion/workloadinstance_suite_test.go
- metrics-operator/config/crd/bases/metrics.keptn.sh_keptnmetricsproviders.yaml
Please include a short summary of the changes and the related issue.
Please also include relevant motivation and context.
List any dependencies that are required for this change.
Fixes #
> chore(lifecycle-operator): renamed TracerFactory to tracerFactory workloadversion

- .github/workflows/validate-helm-chart.yml
small improvement for the Chart Validation workflow
> ci: validate Helm Chart workflow run only on charts changes

- .github/workflows/spell-checker.yml
This PR adds the k8s and the go dictionary to the spell checker action since those are relevant for this repo.
(the spell check on the PR will be green after merging, tested in fork)
Part of #2291
> chore: add more dictionaries to spell checker action

- docs/config/production/params.yaml
- docs/content/en/search.md
This PR adds some missing files and config to the page branch to enable google custom search on the production website.
> chore: change to google custom search

- .github/actions/deploy-klt-on-cluster/values.yaml
- .github/scripts/.helm-tests/default/result.yaml
- .github/scripts/.helm-tests/metrics-only/result.yaml
- .github/scripts/.helm-tests/metrics-with-certs/result.yaml
- metrics-operator/chart/README.md
- metrics-operator/chart/templates/deployment.yaml
- metrics-operator/chart/values.yaml
- metrics-operator/main.go
This PR removes the possibility of blocking the Analysis feature. Analysis is always enabled.
Fixes #2456
> feat(metrics-operator)!: release Analysis feature

- .github/scripts/keptnevaluationprovider_migrator.sh
- docs/content/en/docs/architecture/components/metrics-operator.md
- docs/content/en/docs/getting-started/metrics.md
- docs/content/en/docs/implementing/evaluatemetrics.md
- docs/content/en/docs/implementing/slo.md
- docs/content/en/docs/migrate/metrics-observe.md
- docs/content/en/docs/yaml-crd-ref/analysis.md
- docs/content/en/docs/yaml-crd-ref/analysisdefinition.md
- docs/content/en/docs/yaml-crd-ref/analysisvaluetemplate.md
- docs/content/en/docs/yaml-crd-ref/metric.md
- docs/content/en/docs/yaml-crd-ref/metricsprovider.md
- examples/sample-app/base/metric.yaml
- examples/sample-app/base/provider.yaml
- examples/support/analysis/README.md
- examples/support/metrics/README.md
- examples/support/metrics/hpa.yaml
- examples/support/metrics/metric.yaml
- examples/support/observability/assets/podtatohead-deployment-evaluation/available-cpus-metric.yaml
- examples/support/observability/assets/podtatohead-deployment-evaluation/consumed-memory-metric.yaml
- examples/support/observability/assets/podtatohead-deployment-evaluation/metricsprovider.yaml
> docs: use metrics v1beta1 API version

- metrics-operator/converter/sli_converter.go
- metrics-operator/converter/sli_converter.md
- metrics-operator/converter/sli_converter_test.go
- metrics-operator/converter/slo_converter.go
- metrics-operator/converter/slo_converter.md
- metrics-operator/converter/slo_converter_test.go
* adapt sli slo convertors for v1beta1
* fixed tests
* fixed docs
Fixes #2435 
> refactor: adapt SLI and SLO converters to convert to `v1beta1` metrics API resources

- docs/content/en/docs/migrate/metrics-observe.md
add version of metrics operator to release please
> docs: adapt SLI and SLO converters in migration guide

- docs/content/en/docs/installation/_index.md
- docs/content/en/docs/installation/uninstall.md
> docs: introduce uninstall page

- docs/assets/hpa/hpa.yaml
- docs/assets/hpa/keptnmetric.yaml
- docs/assets/hpa/sample-app.yaml
- docs/content/en/docs/use-cases/hpa.md
Fixes #2495 
Failures in HTML test are expected, as the new resources were introduced
> docs: improve HPA user guide

- README.md
- dashboards/grafana/README.md
- examples/sample-app/README.md
- examples/support/argo/README.md
- examples/support/observability/README.md
- lifecycle-operator/README.md
- runtimes/deno-runtime/README.md
- runtimes/python-runtime/README.md
In https://github.com/keptn/lifecycle-toolkit/issues/1431, we removed Scarf from container images. 
This PR finishes the cleanup removing transparent pixels in our md files.
> docs: remove Scarf transparent pixels

- docs-new/docs/installation/index.md
fixes an occurrence of docsembed and replaces it with include for mkdocs
> docs: fix embedded file

- docs-new/docs/guides/slo.md
- docs-new/docs/migrate/metrics-observe.md
- docs-new/docs/migrate/strategy.md
- docs/content/en/docs/guides/slo.md
- docs/content/en/docs/migrate/metrics-observe.md
- docs/content/en/docs/migrate/strategy.md
Depends on https://github.com/keptn/keptn.github.io/pull/1660
> docs: migrate old Keptn links to new URL

- docs-new/overrides/main.html
adds Google verification for our new website
> docs: add Google verification

- .github/actions/spelling/expect.txt
> docs: fix spell checker

- docs/CONTRIBUTING.md
Removed the odl link and add new cloud native slack link which is  https://cloud-native.slack.com/archives/C017GAX90GM.
Removed the odl link and add new cloud native slack link which is  https://cloud-native.slack.com/archives/C017GAX90GM.
Fixes #2747 
Fixes # (issue)
- [] My PR fulfills the Definition of Done of the corresponding issue and not more (or parts if the issue is separated
into multiple …
> docs: update link to Slack channel

- lifecycle-operator/PROJECT
- metrics-operator/config/crd/bases/metrics.keptn.sh_keptnmetricsproviders.yaml
> fix(lifecycle-operator): duplicate version in project file

- .github/scripts/.helm-tests/certificates-only/result.yaml
- .github/scripts/.helm-tests/default/result.yaml
- .github/scripts/.helm-tests/lifecycle-with-certs/result.yaml
- .github/scripts/.helm-tests/metrics-with-certs/result.yaml
- chart/Chart.lock
- chart/Chart.yaml
- keptn-cert-manager/chart/Chart.yaml
Please include a short summary of the changes and the related issue.
Please also include relevant motivation and context.
List any dependencies that are required for this change.
Fixes # (issue)
Please include a short summary of the changes and the related issue.
Please also include relevant motivation and context.
List any dependencies that are required for this change.
Fixes # (issue)
into multiple …
> chore: bump keptn-cert-manager version in helm charts

- .github/scripts/.helm-tests/certificates-only/result.yaml
- .github/scripts/.helm-tests/default/result.yaml
- .github/scripts/.helm-tests/lifecycle-only/result.yaml
- .github/scripts/.helm-tests/lifecycle-with-certs/result.yaml
- .github/scripts/.helm-tests/metrics-only-with-apiservice-disabled/result.yaml
- .github/scripts/.helm-tests/metrics-only/result.yaml
- .github/scripts/.helm-tests/metrics-with-certs/result.yaml
- chart/Chart.lock
- chart/Chart.yaml
- keptn-cert-manager/chart/Chart.yaml
- lifecycle-operator/chart/Chart.yaml
- metrics-operator/chart/Chart.yaml
Revert of:
https://github.com/keptn/lifecycle-toolkit/commit/ad2609373c4819fc560766e64bc032fcfd801889
https://github.com/keptn/lifecycle-toolkit/commit/681a0507020aedcd86a0321ab7230f8072f62f0b
> chore: revert helm charts bump

- docs-new/docs/components/lifecycle-operator/deployment-flow.md
Fixed a broken layout caused by indentation of code blocks.
https://keptn.sh/latest/docs/components/lifecycle-operator/deployment-flow/?h=deployment+flow#pre-deployment-evaluation-phase
- [n/a] My PR fulfills the Definition of Done of the corresponding issue and not more (or parts if the issue is separated
- [n/a] I regenerated the auto-generated docs for Helm and the CRD documentation (if applicable) …
> docs: fix broken code block styling

- keptn-cert-manager/chart/Chart.lock
- keptn-cert-manager/chart/Chart.yaml
- lifecycle-operator/chart/Chart.lock
- lifecycle-operator/chart/Chart.yaml
- metrics-operator/chart/Chart.lock
- metrics-operator/chart/Chart.yaml
This PR update the keptn/common chart dependency in all helm charts to 0.1.3
> deps: update keptn/common helm chart to 0.1.3

- .github/actions/spelling/expect.txt
- docs/blog/.authors.yml
adds me as an author for an upcoming blog post
> docs: add staceypotter to blog post authors

- mkdocs.yml
This PR adds the Linux Foundation copyright notice to the footer of the website to conform to CLOMonitor and Linux Foundation/CNCF requirements.
Fixes #2874
> chore: add copyright disclaimer to website

- docs/blog/posts/2023-keptn-year-in-review.md
fixing a weirdly worded sentence.
> docs: fix grammatically incorrect line 2023-keptn-year-in-review.md

- docs/blog/posts/analyzing-application-performance.md
Modified the original title  and done the changes, i.e., changed the title (similar to the original title) to fit into the social card or make it apt for social card  for analyzing-application-performance Blog
Fixes #2729
[
](url)
> docs: change Analysis blog post title to fit into social cards

- docs/docs/guides/slo.md
> fix: docs link

- Makefile
> chore: fix makefile lint targets

- docs/docs/reference/crd-reference/task.md
fixes [#2895](https://github.com/keptn/lifecycle-toolkit/issues/2895)
> chore: update Task CRD reference page for v1beta1

- .github/actions/spelling/expect.txt
- runtimes/deno-runtime/Dockerfile
> deps(deno-runtime): update libcrypto3 and libssl3

- docs/docs/components/lifecycle-operator/keptn-apps.md
- docs/docs/guides/evaluations.md
- docs/docs/guides/tasks.md
- docs/docs/reference/crd-reference/taskdefinition.md
fixes #2884 
Also keptn-apps and taskdefinitions needed an adaption
> docs: update content in Evaluations and Task guides with KeptnAppContext

- .github/workflows/htmltest.yaml
small fix to get the cache key working correctly
> ci: fix HTMLTest cache key

- docs/docs/contribute/general/release-checklist.md
- mkdocs.yml
> docs: add release checklist to contribution guide

- renovate.json
> chore: merge dependency for mkdocs-material

- docs/docs/components/lifecycle-operator/deployment-flow.md
- docs/docs/components/lifecycle-operator/keptn-apps.md
- docs/docs/core-concepts/index.md
- docs/docs/getting-started/assets/keptnappcontext.yaml
- docs/docs/getting-started/assets/lifecycle-management-deployment.yaml
- docs/docs/getting-started/assets/lifecycle-management-labels.yaml
- docs/docs/getting-started/assets/lifecycle-management-send-event-task.yaml
- docs/docs/getting-started/assets/lifecycle-management-send-event-taskdefinition.yaml
- docs/docs/getting-started/assets/promotion-task.yaml
- docs/docs/getting-started/lifecycle-management.md
- docs/docs/guides/auto-app-discovery.md
- docs/docs/reference/crd-reference/appcontext.md
- docs/docs/use-cases/day-2-operations.md
- examples/sample-app/base/kustomization.yaml
- examples/sample-app/base/promotion-task.yaml
- examples/sample-app/version-1/appcontext.yaml
- examples/sample-app/version-2/appcontext.yaml
> docs: document promotion task feature

- mkdocs.yml
> docs: added Sticky navigation tabs feature

- examples/sample-app/base/kustomization.yaml
- examples/sample-app/version-1/kustomization.yaml
- examples/sample-app/version-2/kustomization.yaml
Fixes #2995 
I'm sorry for closing my Last PR because of some technical issues. All the requested changes have been made. please let me know if there are any further changes to be made. closed PR #3059
> chore: update kustomize patches

- docs/docs/contribute/software/add-new-metric-provider.md
- metrics-operator/config/crd/bases/metrics.keptn.sh_keptnmetricsproviders.yaml
> docs: remove disabled linter

- docs/docs/migrate/keptn/strategy.md
> docs: rephrase migration guide to propagate propagation feature

- .github/workflows/integration-test.yml
> chore: bump chainsaw version

- .github/scripts/.helm-tests/default/result.yaml
- .github/scripts/.helm-tests/lifecycle-only/result.yaml
- .github/scripts/.helm-tests/lifecycle-with-certs/result.yaml
- docs/docs/reference/api-reference/options/v1alpha1/index.md
- lifecycle-operator/apis/options/v1alpha1/keptnconfig_types.go
- lifecycle-operator/chart/templates/keptnconfig-crd.yaml
- lifecycle-operator/config/crd/bases/options.keptn.sh_keptnconfigs.yaml
- test/chainsaw/integration/keptn-config/00-assert.yaml
- test/chainsaw/integration/keptn-config/00-install.yaml
> feat(lifecycle-operator): introduce blockDeployment parameter into KeptnConfig

- lifecycle-operator/controllers/common/config/config.go
- lifecycle-operator/controllers/common/config/config_test.go
- lifecycle-operator/controllers/common/config/fake/config_mock.go
- lifecycle-operator/controllers/options/keptnconfig_controller.go
- lifecycle-operator/controllers/options/keptnconfig_controller_test.go
> feat(lifecycle-operator): adapt KeptnConfig reconciler to set up blockedDeployment parameter

- .github/scripts/.helm-tests/default/result.yaml
- .github/scripts/.helm-tests/lifecycle-only/result.yaml
- .github/scripts/.helm-tests/lifecycle-with-certs/result.yaml
- lifecycle-operator/apis/lifecycle/v1beta1/common/common.go
- lifecycle-operator/chart/templates/keptnappversion-crd.yaml
- lifecycle-operator/chart/templates/keptnworkloadversion-crd.yaml
- lifecycle-operator/config/crd/bases/lifecycle.keptn.sh_keptnappversions.yaml
- lifecycle-operator/config/crd/bases/lifecycle.keptn.sh_keptnworkloadversions.yaml
updates the states in our crd docs after the change introduced by #3113
> docs: update keptn state descriptions in our CRDs

- docs/docs/reference/crd-reference/analysis.md
Repetition of a paragraph in Analysis reference page
Fixes #3146 
> docs: remove duplicated paragraph from Analysis CRD docs

- docs/docs/index.md
> docs: add use cases to intro page

- .gitignore
⚠️⚠️⚠️⚠️ DO NOT MERGE ⚠️⚠️⚠️⚠️
> chore: bump Keptn version

- .github/actions/spelling/expect.txt
- .github/workflows/scorecard.yml
- README.md
- SECURITY-INSIGHTS.yml
This is an OpenSSF best practise and will increase our [CLOMonitor score](https://clomonitor.io/projects/cncf/keptn).
The workflow is fully generated by the scorecard app and not written by me.
> chore: increase CLOMonitor score

- docs/docs/contribute/general/codespace.md
This pull request addresses the goal of providing easily digestible video material for Keptn contributors.
closes #2820 
The outdated video in Codespaces, demonstrating documentation contribution using GitHub Codespaces, has been revised.
The updated video now covers both documentation and code contributions.
The Codespaces page features a new video that utilizes the latest tools and documentation structure.
This pull request ensures that Keptn contributors can access updated and comprehensive video resources, simplifying project setup and contributions via GitHub Codespaces.
> docs: create tutorial for Keptn contributions with GitHub Codespaces

- .github/actions/spelling/expect.txt
- Makefile
- test/chainsaw/traces/00-assert.yaml
- test/chainsaw/traces/00-install.yaml
- test/chainsaw/traces/chainsaw-test.yaml
- test/chainsaw/traces/collector.yaml
- test/chainsaw/traces/keptnconfig.yaml
- test/chainsaw/traces/verify-traces.sh
> test: introduce integration test for OTel collector

- docs/docs/guides/metadata.md
- adds some more information on how to use the `keptn.sh/metadata` field with multiple k/v pairs
> docs: add info and example about metadata k/v list

- .github/actions/deploy-keptn-on-cluster/action.yml
- .github/actions/deploy-keptn-on-cluster/certificate.yaml
- .github/actions/deploy-keptn-on-cluster/values-cert-manager-io.yaml
- .github/workflows/CI.yaml
- .github/workflows/integration-test.yml
- Makefile
> test: introduce workflow to test integration with cert-manager.io

- README.md
> docs: adapt goals of Keptn in README

- docs/docs/reference/crd-reference/analysis.md
- docs/docs/reference/crd-reference/analysisvaluetemplate.md
- docs/docs/reference/crd-reference/app.md
- docs/docs/reference/crd-reference/appcontext.md
- docs/docs/reference/crd-reference/evaluationdefinition.md
- docs/docs/reference/crd-reference/metric.md
- docs/docs/reference/crd-reference/metricsprovider.md
- docs/docs/reference/crd-reference/task.md
- docs/docs/reference/crd-reference/taskdefinition.md
> docs: improve CRD reference intro paragraphs

- README.md
> docs: fix some readme links

- .github/actions/spelling/expect.txt
- .github/scripts/.helm-tests/default/result.yaml
- .github/scripts/.helm-tests/local-global-precedence/result.yaml
- .github/scripts/.helm-tests/metrics-only-with-apiservice-disabled/result.yaml
- .github/scripts/.helm-tests/metrics-only/result.yaml
- .github/scripts/.helm-tests/metrics-with-certs/result.yaml
- docs/docs/assets/crd/examples/yaml-synopsis.yaml
- docs/docs/components/metrics-operator.md
- docs/docs/contribute/software/add-new-metric-provider.md
- docs/docs/core-concepts/index.md
- docs/docs/getting-started/metrics.md
- docs/docs/installation/k8s.md
- docs/docs/migrate/keptn/strategy.md
- docs/docs/reference/api-reference/metrics/v1/index.md
- docs/docs/reference/crd-reference/analysisvaluetemplate.md
- docs/docs/reference/crd-reference/evaluationdefinition.md
- docs/docs/reference/crd-reference/metricsprovider.md
- docs/docs/use-cases/non-k8s.md
- metrics-operator/api/v1/keptnmetricsprovider_types.go
- metrics-operator/api/v1/keptnmetricsprovider_types_test.go
- metrics-operator/chart/templates/keptnmetricsprovider-crd.yaml
- metrics-operator/config/crd/bases/metrics.keptn.sh_keptnmetricsproviders.yaml
- metrics-operator/controllers/common/providers/common.go
- metrics-operator/controllers/common/providers/prometheus/prometheus.go
- metrics-operator/controllers/common/providers/prometheus/prometheus_test.go
- metrics-operator/controllers/common/providers/provider.go
- metrics-operator/controllers/common/providers/provider_test.go
> feat: add Thanos metrics provider

- test/chainsaw/testmetrics/metrics-keda/chainsaw-test.yaml
here is a flakyness in the keda test, increasing the timeout and small adaptation to remove the flakyness
> test: adapt keda integration test to remove flakyness

- mkdocs.yml
Reverts: https://github.com/keptn/lifecycle-toolkit/pull/3369
> revert: enable mkdocs social plugin

- .github/actions/spelling/expect.txt
- docs/docs/use-cases/assets/flux/app.yaml
- docs/docs/use-cases/assets/flux/flux-kustomization.yaml
- docs/docs/use-cases/assets/flux/gitrepository.yaml
- docs/docs/use-cases/assets/flux/kustomize.yaml
- docs/docs/use-cases/flux.md
- mkdocs.yml
> docs: create use-case for integration with Flux

- dashboards/grafana/configmap/grafana-dashboard-keptn-applications.yaml
> fix(dashboards): fix formatting of Keptn Applications dashboard

- docs/docs/installation/configuration/vcluster.md
Fixes https://github.com/keptn/lifecycle-toolkit/issues/3436
> docs: fix vCluster link

- docs/docs/contribute/general/release-checklist.md
Added to verify helm charts docs verification for breaking changes. 
Fixes #3541
Changes can be checked in `docs/docs/contribute/general/release-checklist.md`
N/A
Adding  checks to verify breaking changes are reflected by helm charts in release checklist. 
Fixes #3541
the [Contribution …
> docs: update release checklist to verify reflection of breaking changes in helm charts

- docs/docs/components/certificate-operator.md
- docs/docs/installation/configuration/cert-manager.md
Fixes #3520
- Shifted the troubleshooting segment to cert-manager.md
> docs: troubleshooting shifted

- docs/docs/reference/api-reference/options/v1alpha1/index.md
- lifecycle-operator/apis/options/v1alpha1/keptnconfig_types.go
- lifecycle-operator/config/crd/bases/lifecycle.keptn.sh_keptnappcontexts.yaml
- lifecycle-operator/config/crd/bases/lifecycle.keptn.sh_keptnappcreationrequests.yaml
- lifecycle-operator/config/crd/bases/lifecycle.keptn.sh_keptnapps.yaml
- lifecycle-operator/config/crd/bases/lifecycle.keptn.sh_keptnappversions.yaml
- lifecycle-operator/config/crd/bases/lifecycle.keptn.sh_keptnevaluationdefinitions.yaml
- lifecycle-operator/config/crd/bases/lifecycle.keptn.sh_keptnevaluationproviders.yaml
- lifecycle-operator/config/crd/bases/lifecycle.keptn.sh_keptnevaluations.yaml
- lifecycle-operator/config/crd/bases/lifecycle.keptn.sh_keptntaskdefinitions.yaml
- lifecycle-operator/config/crd/bases/lifecycle.keptn.sh_keptntasks.yaml
- lifecycle-operator/config/crd/bases/lifecycle.keptn.sh_keptnworkloadinstances.yaml
- lifecycle-operator/config/crd/bases/lifecycle.keptn.sh_keptnworkloads.yaml
- lifecycle-operator/config/crd/bases/lifecycle.keptn.sh_keptnworkloadversions.yaml
- lifecycle-operator/config/crd/bases/options.keptn.sh_keptnconfigs.yaml
- lifecycle-operator/controllers/common/config/config.go
- lifecycle-operator/controllers/common/config/fake/config_mock.go
- lifecycle-operator/controllers/options/keptnconfig_controller.go
- lifecycle-operator/controllers/options/keptnconfig_controller_test.go
- lifecycle-operator/converter/example_output.yaml
Adds a feature flag for the Rest Api
Fixes #3594 
> feat(lifecycle-operator): introduce RestApiEnabled parameter in KeptnConfig

- .github/workflows/release.yml
> chore: attest provenance for images

- .github/workflows/validate-semantic-pr.yml
- lifecycle-operator/config/rbac/role.yaml
- lifecycle-operator/controllers/options/keptnconfig_controller.go
small fix to the keptn gateway service that it is now available on localhost on port 30091
> fix(keptn-gateway): service not working as expected

- docs/assets/stylesheets/home.css
Added css change to remove back button when screen size is reduced.
Fixes #2947
> docs: add css change to remove back button when screen size is reduced

- lifecycle-operator/chart/templates/lifecycle-mutating-webhook-configuration.yaml
- lifecycle-operator/chart/values.yaml
Extended Chart to allow FailurePolicy to be set while still keeping default behavior, This is useful as it allows people to opt out on the lifecycle controller being a single point of failure for cluster scaling when running in an environment which may use spot nodes or other reasons the lifecycle controller (singleton) becomes unavailable. 
Fixes # [issue](https://github.com/keptn/lifecycle-toolkit/issues/3923)
This is not a code change to unit tests are not overly relevant here I have however confirmed this small change renders correctly via helm playground [here](https://helm-playground.com/#t=IYBwlgagpgTgzmA9gOwFwAJgBMC2Y4IoxQDm%2BALjMOUsgHQDWAHHHUgPQBuAjAFANhkWDAFkAruWqCSAdSgAjABaJEDAMIoAZmBJiqNFLxxRJWasFS906ZMGMYANmE1QAxgE9XDqAFocEqWQSHwB3BWVVH1ctHT0pQ2sHYHkoBzhLa2sGKBByejhFdkEAKzdyK …
> feat: allow FailurePolicy to be configured by users
