keptn/lifecycle-toolkit

operator/webhooks/pod_mutating_webhook.go

feat: Inject keptn-scheduler when resource contains Keptn annotations

---

functions-runtime/Dockerfile
functions-runtime/README.md
functions-runtime/entrypoint.sh

feat: initial version of function runtime

---

lfc-scheduler/manifests/install/kustomization.yaml

As this led to problems when deploying outside of the keptn-lifecycle-controller-system namespace

fix: fixed namespace in scheduler kustomization

---

lfc-scheduler/manifests/install/base/scheduler-config.yaml

Using the current configuration for the `KubeSchedulerConfiguration` resulted in the following error in the scheduler:
```
command failed" err="json: cannot unmarshal object into Go struct field KubeSchedulerProfile.profiles.pluginConfig of type []v1beta3.PluginConfig
```
Changing the value to what we previously had in the scheduler config seems to solve this.

fix: scheduler config plugin configuration

---

examples/podtatohead-deployment/pre-deployment-tasks.yaml

With the namespace added, the demo can simply be executed using `kubectl apply -f .` in the `examples/podtatohead-deployment` directory

fix: Added namespace to task definition for podtato head example

---

.github/workflows/release.yml

Closes #34 
- Adds the manifest file from lfc-scheduler to the release

ci: Add lfc-scheduler manifest to release

---

.github/workflows/CI.yaml

- Splits the Docker build and push steps into two separate steps
- Skips the following steps in the CI pipeline if the PR is from a fork
- Push Docker Images
- Install controller-gen
- Generate release.yaml
- Upload release.yaml

ci: Skip docker push steps if the PR is from a fork

---

functions-runtime/Makefile
operator/Makefile
scheduler/Makefile

- disables all ARM related builds for now since they probably don't work and aren't tested either
- (distroless doesn't have ARM images)

ci: Disable ARM builds for now

---

.github/workflows/CI.yaml

- Skips the remaining jobs within the CI pipeline if the build matrix is empty

ci: Skip the remaining workflow execution if the build matrix is empty

---

operator/controllers/keptnworkload/controller.go
operator/main.go

feat(operator): Introduce OTel tracing for Workload controller

---

operator/api/v1alpha1/semconv/semconv.go
operator/controllers/keptnworkloadinstance/controller.go
operator/main.go

feat(operator): Introduce OTel tracing for WorkloadInstance controller

---

operator/api/v1alpha1/semconv/semconv.go
operator/controllers/keptntask/controller.go
operator/main.go

feat(operator): Introduce OTel tracing for Task controller

---

scheduler/cmd/scheduler/main.go
scheduler/manifests/install/base/rbac.yaml
scheduler/pkg/klcpermit/permit.go

Permit plugin should check the waiting queue and reject or approve pods before the eviction
This is for now implemented as a recursive async routine.
A little learning: we cannot queue pod by default, if there is an error due to the pod being evicted etc. the queue action may fail and the scheduler could end up looping indefinitely

feat(scheduler): Background check for pod status in permit plugin

---

.github/workflows/CI.yaml
functions-runtime/Makefile
operator/Makefile
scheduler/Makefile

- fixes docker layer caching
The latest [run](https://github.com/keptn-sandbox/lifecycle-controller/actions/runs/3218023374) shows that the cache is now working

ci: Fix docker layer caching

---

operator/config/manager/manager.yaml
operator/go.mod
operator/go.sum
operator/main.go

This PR introduces the support for sending OpenTelemetry traces to the otel-collector:
Example Trace in Jaeger UI:

feat(operator): Add support for OTel collector

---

scheduler/pkg/klcpermit/permit.go

This PR solves the problem of running into the dynamic client's rate limiter due to the context already being cancelled outside of the permit function

fix(scheduler): Create new context when starting background routine for pod checks

---

scheduler/cmd/scheduler/main.go

In OTel v20, any erorr log generated by OTel compoenents would have been printed. This PR disables them like the default in v1.10

fix(scheduler): Ignoring OTel error logs

---

operator/api/v1alpha1/keptnevaluation_types.go
operator/config/crd/bases/lifecycle.keptn.sh_keptnevaluations.yaml
operator/config/manager/kustomization.yaml
operator/config/manager/manager.yaml
operator/config/samples/lifecycle_v1alpha1_keptnevaluationdefinition.yaml
operator/controllers/keptnevaluation/controller.go
operator/go.mod
operator/go.sum

feat(operator): Introduce Prometheus evaluation

---

examples/observability/config/prometheus/prometheus-networkPolicy.yaml

This PR fixes the network policy for prometheus to enable the lifecycle controller to access the Prometheus API

chore: Updated Prometheus Network policy for granting access from lifecycle controller namespace

---

operator/api/v1alpha1/common/phases.go
operator/api/v1alpha1/keptnappversion_types.go
operator/api/v1alpha1/keptnworkloadinstance_types.go
operator/controllers/keptnappversion/controller.go
operator/controllers/keptnworkloadinstance/controller.go

feat(operator): Add information about current phase in workloadinstances and appversions

---

operator/api/v1alpha1/common/common.go
operator/controllers/keptnappversion/controller.go
operator/controllers/keptnevaluation/controller.go
operator/controllers/keptntask/controller.go
operator/controllers/keptnworkloadinstance/controller.go
operator/main.go

Closes #203 
This makes sure that the number of active deployments/tasks/evaluations/apps stays consistent and there are not leftover counter values.
Example for active deployments in Grafana:

feat(operator): Use Async Gauges for active KLC Entities

---

examples/podtatohead-deployment/app.yaml
operator/controllers/keptnworkloadinstance/controller.go
operator/go.mod
operator/go.sum

Split from https://github.com/keptn/lifecycle-controller/pull/209

fix(operator): Fixed starting deployments, when no corresponding app-version is available

---

functions-runtime/Dockerfile

-  fixes the issue from the latest [run](https://github.com/keptn/lifecycle-controller/actions/runs/3360233311) on the main branch

ci: Fix docker build stage for functions-runtime

---

operator/api/v1alpha1/common/common.go
operator/api/v1alpha1/keptnappversion_types.go
operator/api/v1alpha1/keptnworkloadinstance_types.go
operator/controllers/common/helperfunctions.go
operator/controllers/common/interfaces.go
operator/controllers/common/interfaces_test.go
operator/controllers/common/phasehandler.go
operator/controllers/common/spanhandler.go
operator/controllers/keptnapp/controller.go
operator/controllers/keptnappversion/controller.go
operator/controllers/keptnappversion/reconcile_prepostdeployment.go
operator/controllers/keptnappversion/reconcile_prepostevaluation.go
operator/controllers/keptnappversion/reconcile_workloadsstate.go
operator/controllers/keptnevaluation/controller.go
operator/controllers/keptntask/controller.go
operator/controllers/keptnworkloadinstance/controller.go
operator/controllers/keptnworkloadinstance/reconcile_deploymentstate.go
operator/controllers/keptnworkloadinstance/reconcile_prepostdeployment.go
operator/controllers/keptnworkloadinstance/reconcile_prepostevaluation.go
operator/main.go

- refactored handling of the phase -> common code for KeptnAppVersion and KeptnWorkloadInstance
- support `Progressing` state in each phase
- improved speed of the whole cycle (30-40s improvement on deploying podtatohead observability example 2:30min -> 1:45min)
- move duplicated code to controller common package

chore(operator): Support Progressing state in every phase + refactoring + speed improvements

---

.github/workflows/CI.yaml
operator/Makefile
scheduler/Makefile

- improves CI pipeline performance
- removes fmt vet and generate from make test
- removes fmt and vet from make build
- Runtime [main](https://github.com/keptn/lifecycle-toolkit/actions/runs/3377183551) branch: 9min 11s
- Runtim [this](https://github.com/keptn/lifecycle-toolkit/actions/runs/3377371766) branch: 7min 18s

ci: Improve CI pipeline performance

---

.github/workflows/validate-semantic-pr.yml

- switches the amannn/action-semantic-pull-request github action from commit hash to tag versions

ci: Switch semantic PR action from commit hash to tag

---

.github/workflows/CI.yaml
.github/workflows/component-test.yml
.github/workflows/e2e-test.yml
.github/workflows/integration-test.yml
.github/workflows/performance-test.yml
.github/workflows/release.yml
operator/Dockerfile
operator/go.mod
scheduler/Dockerfile
scheduler/go.mod

deps: update go 1.19

---

README.md

docs: add cert-manager installation instructions to README

---

README.md
examples/single-service/deploy.yaml
examples/single-service/pre-deployment-tasks.yaml
operator/api/v1alpha1/groupversion_info.go
operator/config/rbac/role.yaml
operator/controllers/common/fake/tracer.go
operator/controllers/keptnapp/controller_test.go
operator/webhooks/pod_mutating_webhook.go
operator/webhooks/pod_mutating_webhook_test.go
scheduler/cmd/scheduler/main_test.go

feat(operator): Copy annotations from parent resource if not defined on pod

---

operator/api/v1alpha1/keptnappversion_types.go
operator/api/v1alpha1/keptnappversion_types_test.go
operator/controllers/keptnworkloadinstance/controller.go
operator/controllers/keptnworkloadinstance/controller_test.go
operator/test/component/common.go
operator/test/component/workloadinstancecontroller_test.go

fix(operator): Do not proceed with WLI if no AppVersion containing it is available

---

.github/actions/deploy-klt-on-cluster/action.yml
.github/workflows/CI.yaml
.github/workflows/e2e-test.yml
.github/workflows/integration-test.yml
.github/workflows/performance-test.yml

- builds the Docker images without pushing it to a registry for local testing.
- extracts those images to `.tar` archives and uploads them as artifacts
- downloads these images in testing stages, to import them into a local k3d cluster
- only pushes to the `ghcr` registry, if all tests have passed, and the push event occurs on a main/maintenance branch
This enables the pipeline to run all tests for PRs from forks.

ci: Use local images for testing

---

.github/workflows/validate-semantic-pr.yml

- ensures that PR subject start lowercase
Fixes #425 

chore: ensures that PR subjects start with lowercase

---

examples/argo/Makefile

- fixes a tiny bug in the Argo example where the argo namespace gets deleted. The wrong variable was used there.

fix: use correct namespace variable in delete cmd

---

operator/api/v1alpha1/common/common_test.go
operator/api/v1alpha1/common/phases.go
operator/api/v1alpha1/common/phases_test.go
operator/api/v1alpha1/keptntask_types.go
operator/config/crd/bases/lifecycle.keptn.sh_keptntasks.yaml
operator/controllers/common/phasehandler.go
operator/controllers/common/phasehandler_test.go

feat(operator): include detailed information about task/evaluation failure in span

---

README.md

```yaml
> kubectl describe crd keptnevaluationdefinitions.lifecycle.keptn.sh
Name:         keptnevaluationdefinitions.lifecycle.keptn.sh
Namespace:
Labels:       <none>
Annotations:  controller-gen.kubebuilder.io/version: v0.9.2
API Version:  apiextensions.k8s.io/v1
Kind:         CustomResourceDefinition
```
```yaml
> kubectl describe crd keptnevaluationproviders.lifecycle.keptn.sh
Name:         keptnevaluationproviders.lifecycle.keptn.sh
Namespace:
Labels:       <none>
Annotations:  controller-gen.kubebuilder.io/version: v0.9.2
API Version:  apiextensions.k8s.io/v1
Kind:         CustomResourceDefinition
```
Signed-off-by: Nicolas Lamirault <nicolas.lamirault@gmail.com>

docs: fix CRD api version for EvaluationProvider and EvaluationDefinition

---

.github/workflows/golangci-lint.yml
.golangci.yml
operator/controllers/common/activemetricsobject.go
operator/controllers/common/fake/activemetricsobject_mock.go
operator/controllers/common/fake/listitem_mock.go
operator/controllers/common/fake/metricsobject_mock.go
operator/controllers/common/fake/phaseitem_mock.go
operator/controllers/common/metrics_test.go
operator/controllers/common/metricsobject.go
operator/controllers/common/phasehandler_test.go
operator/controllers/common/phaseitem.go
operator/controllers/common/phaseitem_test.go
operator/controllers/keptnapp/controller_test.go
operator/controllers/keptnappversion/controller_test.go
operator/controllers/keptnevaluation/controller.go
operator/controllers/keptnworkloadinstance/controller.go
operator/controllers/keptnworkloadinstance/controller_test.go
operator/test/component/DEVELOPER.md
operator/test/component/appcontroller_test.go
operator/test/component/load_test.go
operator/test/component/suite_test.go
operator/test/component/taskcontroller_test.go
operator/test/component/workloadinstancecontroller_test.go
operator/webhooks/pod_mutating_webhook.go
scheduler/pkg/klcpermit/workflow_manager.go
scheduler/test/e2e/fake/v1alpha1/groupversion_info.go
scheduler/test/e2e/scheduler_test.go
scheduler/test/e2e/suite_test.go

- introduces a new workflow for checking the code with golangci-lint
- the following linters are being used
- errcheck (default)
- gosimple (default)
- govet (default)
- ineffassign (default)
- staticcheck (default)
- typecheck (default)
- unused (default)
- gofmt
- #391 
- implement + refactor currently commented out linters

ci: add golangci-lint workflow

---

.github/workflows/golangci-lint.yml
.golangci.yml
operator/controllers/keptnappversion/controller_test.go

- is a follow up PR of #448 
- introduces the following linters for `golangci-lint`
- errorlint
- containedctx
- dogsled
- nilnil
- noctx
- adds refactoring for errors of the added linters
- #391 

ci: introduce additional linters for golangci-lint

---

.github/workflows/release.yml

- adds a trigger in the release pipeline to also run for maintenance branches

ci: trigger release pipeline also for maintenance branches

---

.github/workflows/CI.yaml
.github/workflows/component-test.yml
codecov.yml
operator/Makefile

Add component tests to the coverage report: https://app.codecov.io/gh/keptn/lifecycle-toolkit/tree/chore%2Funify-coverage
We can see a bump from 57% to 68%

chore: add component tests as part of the coverage

---

.github/workflows/CI.yaml

This PR avoids having multiple instances of the same controller running at the same time during the component/performance tests

chore: execute performance tests after all other tests have been executed

---

.github/actions/deploy-klt-on-cluster/action.yml
.github/workflows/CI.yaml
.github/workflows/e2e-test.yml
.github/workflows/integration-test.yml
.github/workflows/performance-test.yml

This PR should fix the failing integration tests on the release-please branches due to the missing functions runner image

ci: pass locally built functions runner image to test setups

---

.github/actions/deploy-klt-on-cluster/action.yml
.github/workflows/CI.yaml
.github/workflows/golangci-lint.yml
.golangci.yml
operator/Makefile
scheduler/Makefile

- adds some more linters to golangci-lint:
- `cyclop`: Measures and limits cyclomatic complexity
- `gocognit`: Measures and limits cognitive complexity
- `funlen`: Limits function line and statement length
- this change will enable us to get rid of sonarcloud since we have everything covered by golangci-lint
- adjusts makefile `test` commands to return aggregated and fully syntactically correct coverage reports
- golangci-lint will fail until all errors are fixed in a follow up ticket
- for now golangci-lint will not make the pipeline go red since we cannot fix all errors right now
Closes #462
Linter issues will be fixed in #485.

chore: enhance golangci-lint with code complexity and other measures

---

README.md
dashboards/grafana/README.md
examples/argo/README.md
examples/flux/README.md
examples/kubecon-na-22-demo/README.md
examples/observability/README.md
examples/podtatohead-deployment/README.md
examples/taskonly-hello-keptn/README.md
functions-runtime/README.md
operator/README.md
scheduler/README.md

Signed-off-by: Christian Heckelmann <christian.heckelmann@dynatrace.com>

chore: add scarf pixel to markdown files

---

.github/actions/deploy-klt-on-cluster/action.yml
.github/workflows/release.yml
operator/config/manager/kustomization.yaml
operator/config/manager/manager.yaml
scheduler/manifests/install/kustomization.yaml

- introduces a new container registry under our own keptn domain
- this gives keptn the option to keep track of download numbers and versions of KLT that are downloaded
THIS IS A BREAKING CHANGE
Part of #195

feat: use scarf.sh registry for all container images

---

.github/actions/deploy-klt-on-cluster/action.yml
.github/workflows/CI.yaml

- uses the k3s version `v1.24.8` to avoid [this](https://github.com/k3s-io/k3s/issues/5835) networking bug
- runs performance-tests again in parallel with the e2e- and integration-tests
- fixes #516

ci: run performance tests parallel to e2e and integration tests

---

.github/actions/deploy-klt-on-cluster/action.yml
.github/workflows/e2e-test.yml
.github/workflows/integration-test.yml
.github/workflows/performance-test.yml

- uses `kind` instead of `k3d` for testing

ci: use kind instead of k3d for tests

---

renovate.json

- fixes renovate in the KLT by ignoring the scheduler and operator images

ci: fix renovate by ignoring KLT container images

---

dashboards/grafana/configmap/grafana-dashboard-keptn-applications.yaml
dashboards/grafana/configmap/grafana-dashboard-keptn-workloads.yaml
dashboards/grafana/grafana_dashboard_applications.json
dashboards/grafana/grafana_dashboard_workloads.json
dashboards/grafana/import/grafana_dashboard_applications.json
dashboards/grafana/import/grafana_dashboard_workloads.json
examples/observability/config/prometheus/grafana-dashboard-keptn-applications.yaml
examples/observability/config/prometheus/grafana-dashboard-keptn-workloads.yaml

fix(dashboards): use fixed color mode for succeeded AppVersion/WorkloadInstance tiles

---

operator/webhooks/pod_mutating_webhook.go

This fixes the way how lifecycle toolkit resources are correlated in ArgoCD. Looks like this in the end:

feat(operator): fix ownership information for keptnworkloads

---

.github/workflows/CI.yaml
.github/workflows/release.yml

- generates SBOMs for all 3 container images upon release
- the SBOMs are attached to the newly created release in JSON format
Fixes #300

feat: generate SBOMs for container images on release

---

.github/workflows/security-scans.yml

- changes github issue reporting for the security scan pipeline so that it only reports outcomes on scheduled runs and not on manually triggered runs

ci: only report security scan result on scheduled runs

---

.gitignore
operator/PROJECT
operator/apis/lifecycle/v1alpha1/common/common.go
operator/apis/lifecycle/v1alpha1/keptnevaluationprovider_conversion.go
operator/apis/lifecycle/v1alpha1/keptnevaluationprovider_conversion_test.go
operator/apis/lifecycle/v1alpha2/keptnevaluationprovider_conversion.go
operator/apis/lifecycle/v1alpha2/keptnevaluationprovider_webhook.go
operator/config/crd/kustomization.yaml
operator/kubebuilder
operator/main.go

feat(operator): add version conversion rule for KeptnEvaluationProvider

---

.github/workflows/CI.yaml
.github/workflows/release.yml
examples/support/argo/README.md

- fixes a small issue with the KLT docs auto update pipeline steps. they should get triggered correctly now
- fixes a broken markdown link

ci: use correct needs value to kick off docs auto update

---

docs/Makefile

- makes sure that the docs tooling hugo version is picked up by renovate using the correct syntax

ci: let renovate pick up hugo version

---

.github/actions/update-documentation/action.yml
.github/workflows/release.yml

- makes sure that upon release of KLT, also the default version in the docs get updated to the new one
- fixes commit author name and email address

ci: docs auto update on release

---

docs/content/docs/tasks/restart-application-deployment/_index.md

docs: documentation for restartable applications feature

---

operator/apis/metrics/v1alpha1/keptnmetric_test.go
operator/apis/metrics/v1alpha1/keptnmetric_types.go
operator/controllers/common/providers/common.go
operator/controllers/common/providers/dynatrace.go
operator/controllers/common/providers/keptnmetric.go
operator/controllers/common/providers/keptnmetric_test.go
operator/controllers/common/providers/prometheus.go
operator/controllers/common/providers/provider.go
operator/controllers/common/providers/provider_test.go
operator/controllers/lifecycle/keptnevaluation/controller.go
operator/controllers/lifecycle/keptnevaluation/controller_test.go
operator/test/component/evaluationcontroller_test.go
operator/test/component/suite_test.go

feat(operator): evaluation controller uses KeptnMetric as SLI provider

---

.github/workflows/CI.yaml
.github/workflows/release.yml

- adds a cache step for the build tools so that we should see less GH API rate limiting happening in our pipeline
- caching for the cert manager will be added in #687
Fixes #563

ci: add step to cache build tools in artifact upload job

---

operator/controllers/metrics/keptnmetric_controller.go

perf: requeue `KeptnMetric` and process them only when deadline is met

---

.github/workflows/golangci-lint.yml
.github/workflows/release.yml
.github/workflows/validate-semantic-pr.yml
klt-cert-manager/controllers/keptnwebhookcontroller/certificate_secret.go
klt-cert-manager/controllers/keptnwebhookcontroller/keptnwebhookcertificate_controller.go
klt-cert-manager/controllers/keptnwebhookcontroller/webhook_cert_controller_test.go
klt-cert-manager/eventfilter/eventfilter_test.go
klt-cert-manager/kubeutils/query.go
klt-cert-manager/kubeutils/query_test.go
klt-cert-manager/kubeutils/secret.go
klt-cert-manager/kubeutils/secret_test.go

fix: add cert-manager to missing pipelines + fix linter issues

---

README.md

Fix the broken link to the observability demo
Closes issue: https://github.com/keptn/lifecycle-toolkit/issues/665
Signed-off-by: Brad McCoy <bradmccoydev@gmail.com>

chore: update observability demo link

---

README.md

Fixes #670 
Updated the link to the examples folder in README.md at line 100 to `./examples/sample-app/`

fix: broken link to examples folder in README.md

---

operator/controllers/common/test_utils.go
operator/controllers/lifecycle/keptnworkloadinstance/controller.go
operator/controllers/lifecycle/keptnworkloadinstance/controller_test.go

Related to #680 
This PR makes sure that the status of a KeptnAppVersion's evaluation is only checked as long as a KWI has not entered it's first reconciliation phase. This will reduce calls to the K8s API, and avoid sending a new KeptnAppPreEvaluationSuccess K8s event in each reconciliation loop

perf(operator): only check for KeptnApp pre-evaluation if KWI has not entered its first phase yet

---

operator/apis/lifecycle/v1alpha2/common/common.go
operator/apis/lifecycle/v1alpha2/common/common_test.go
operator/controllers/common/phasehandler.go
operator/controllers/lifecycle/keptnworkloadinstance/controller_test.go

Closes #680 
This PR prevents tasks of WorkloadInstances being attempted to be reconciled if they are in the `Cancelled` state (which had been replaced with `Deprecated` recently).

fix(operator): prevent re-execution of workload tasks that have been cancelled in a previous KLT version

---

operator/cmd/metrics/adapter/adapter.go
operator/cmd/metrics/adapter/provider/provider.go
operator/cmd/metrics/adapter/provider/provider_test.go
operator/config/rbac/extra_roles.yaml
operator/config/rbac/kustomization.yaml
operator/config/rbac/role.yaml
operator/main.go

Signed-off-by: realanna <anna.reale@dynatrace.com>

fix(operator): refactored metric adapter for helm generation

---

.github/.kubescape/exceptions.json
.github/kics-config.yml
.github/workflows/security-scans.yml
examples/sample-app/base/manifest.yaml
examples/support/observability/assets/podtatohead-deployment-evaluation/manifest.yaml
functions-runtime/Dockerfile
klt-cert-manager/config/default/manager_auth_proxy_patch.yaml
klt-cert-manager/config/manager/manager.yaml
operator/config/default/base/manager_auth_proxy_patch.yaml
operator/config/manager/manager.yaml
operator/config/rbac/auth_proxy_service.yaml
operator/test/e2e/operator_test.go
test/integration/podtato-head-application-v1alpha1/00-install.yaml
test/integration/podtato-head-application/00-install.yaml
test/integration/restartable-app/00-install.yaml
test/integration/simple-deployment-annotated/00-install.yaml
test/integration/simple-deployment/00-install.yaml
test/integration/simple-statefulset-annotated/00-install.yaml
test/integration/simple-statefulset-annotated/02-install.yaml
test/integration/workload-instance-failing-pre-task/00-install.yaml
test/integration/workload-instance-missing-evaluation/00-install.yaml

closes #687 
closes #678 
closes #628 
closes #699 
closes #717
Adds cert manager to the security pipeline
Modify security pipeline to run from branch images if triggered manually
Also addresses agreed changes from [this run ](https://github.com/keptn/lifecycle-toolkit/actions/runs/4015989214/jobs/6898435561)
Run with all fixes available [here](https://github.com/keptn/lifecycle-toolkit/actions/runs/4051860582/jobs/6970640603)

fix: security pipeline issues

---

functions-runtime/README.md
functions-runtime/samples/ts/prometheus.ts

Signed-off-by: Shardul Srivastava <shardul.srivastava007@gmail.com>
Adds a simple function for fetching metrics from Prometheus and evaluates them against a specified expected value.
Closes https://github.com/keptn/lifecycle-toolkit/issues/65

feat: add prometheus metrics evaluation example

---

docs/Makefile

KTL docs port changes so that id does not conflict with the keptn docs (#708)
Example:
` make PORT=1319 server `

docs: change port for KTL docs

---

operator/apis/options/v1alpha1/keptnconfig_types.go
operator/config/crd/bases/options.keptn.sh_keptnconfigs.yaml

- adds the new `KeptnAppCreationRequestTimeout` to the KeptnConfig API
Part of #695

feat: add KeptnAppCreationRequestTimeout field to KeptnConfig API

---

docs/content/en/docs/getting-started.md

Signed-off-by: Rakshit Gondwal <rakshitgondwal3@gmail.com>
Fixed some typo's and some grammatical errors.

docs: modify getting-started.md

---

examples/sample-app/Makefile

Fixes #779 
Path to the observability folder updated for `make` commands

fix: updated path to observability folder

---

.github/workflows/validate-semantic-pr.yml
helm/chart/Chart.yaml

- adds helm and artifacthub metadata to the KLT helm chart
- some annotations were omitted because they are too much effort and would need to be updated manually:
- CRDs
- CRD examples
Fixes #596

feat: add metadata to helm chart

---

docs/content/en/docs/tasks/implement-slack-notification/_index.md
examples/sample-app/README.md
examples/sample-app/base/app.yaml

docs: added documentation to enable Slack notification post deployment task (#787)

---

docs/content/en/docs/crd-ref/_index.md
docs/content/en/docs/crd-ref/crd-template.md
docs/content/en/docs/crd-template.md

Signed-off-by: Meg McRoberts <meg.mcroberts@dynatrace.com>
This sets up the directory and a template file for the CRD Reference pages
This is for use in Phase 1 of https://github.com/keptn/lifecycle-toolkit/issues/778 , to allow us to develop content.  This is almost certainly not how this material will ultimately be published but will provide us with valuable learning to help us determine the structure we want and implement the appropriate tooling.

docs: set up directory for CRD Reference

---

operator/apis/lifecycle/v1alpha2/keptnappversion_test.go
operator/apis/lifecycle/v1alpha2/keptnappversion_types.go
operator/apis/lifecycle/v1alpha2/keptnworkloadinstance_test.go
operator/apis/lifecycle/v1alpha2/keptnworkloadinstance_types.go
operator/controllers/common/metrics.go
operator/controllers/common/metrics_test.go
operator/controllers/common/otel_utils.go

Closes #807 
This PR fixes the calculation of the deployment interval metrics.
When calculating these metrics for AppVersions, which support multiple revisions for the same version since the last release, the earliest revision of a KeptnAppVersion's predecessor is being used as a reference.

fix(operator): fix calculation of deployment interval metrics

---

CODEOWNERS

Signed-off-by: Moritz Wiesinger <moritz.wiesinger@dynatrace.com>

chore: update codeowners to have default owners for docs folder

---

README.md

This PR wants to provide more visibility on the new feature we're adding and their current maturity level.

chore: add maturity status for each feature

---

operator/controllers/common/metrics.go
operator/controllers/common/metrics_test.go

fix(operator): compute deployment interval on deployment endtime

---

.github/workflows/release.yml

Fixes #852
Example of run that the ns file is correctly created: https://github.com/thisthat/lifecycle-controller/actions/runs/4183048159/jobs/7246906287

fix: include namespace creation in release manifest

---

.github/workflows/set-date.yml

- exchange the keptn bot token used in the set date pipeline with one that can access projects to make the whole thing work

ci: use different token to access projects

---

examples/support/observability/config/prometheus/kube-state-metrics-deployment.yaml
test/load/assets/prometheus/kube-state-metrics-deployment.yaml

The main Kubernetes container registry is now defaulted to registry.k8s.io. See: https://kubernetes.io/blog/2022/11/28/registry-k8s-io-faster-cheaper-ga/.
Switching to the new registry for the yaml files

chore: switch to registry.k8s.io in yaml files in prometheus example

---

metrics-operator/cmd/metrics/adapter/provider/custom_metrics.go
metrics-operator/cmd/metrics/adapter/provider/custom_metrics_test.go
metrics-operator/cmd/metrics/adapter/provider/provider.go
metrics-operator/config/rbac/role.yaml
metrics-operator/controllers/metrics/controller.go

Follow up PR for #849 
To support evaluations that are done in a namespace other than `keptn-lifecycle-toolkit-system` and therefore maintain feature parity with previous KLT versions, `KeptnMetrics` need to be able to live in any namespace. This PR adapts the roles required for the metrics-operator to support this, and adapts the metrics adapter accordingly

feat(metrics-operator): allow KeptnMetrics to be placed in any namespace 

---

.github/scripts/generate-helm-docs.sh
.github/workflows/validate-helm-docs.yml
helm/.gitignore
helm/chart/README.md
helm/chart/doc.yaml
helm/chart/values.yaml
renovate.json

Part of #840 
- pins the version of the doc generator tool
- separate documentation from value.yaml (see #880)
- prints a more user-friendly diff when the README.md file is not up-to-date

feat(helm-chart): split documentation from value files

---

.github/workflows/CI.yaml
.github/workflows/golangci-lint.yml

ci: conditionally trigger GitHub Actions when needed

---

Makefile
docs/Makefile

Allowing "make" targets of the `docs` directory to be populated into the main `makefile`. Now they can be called from both directories.

chore: improve Makefiles usage

---

CONTRIBUTING.md

Ref: #733 
I have compiled a preliminary list of supplementary technologies associated with Keptn, as several new individuals have expressed interest in obtaining this information. This list has been assembled from the contributions provided by members of the community. If you have any additional resources that need to be included, kindly inform us.

docs: initial list of related technologies of Keptn

---

klt-cert-manager/config/manager/manager.yaml

~~- Removes kube-rbac-proxy since it goes against our Observability first approach (see their [docs](https://book.kubebuilder.io/reference/metrics.html#protecting-the-metrics))~~
- adjust limits based on monitoring while running the performance tests

chore: adjust manifest limits

---

.github/workflows/release-docs.yml

It seems like `require` and `default` are not working as expected, hence that we are remove the `required` flag.
closes: #951

fix: remove required from release docs yaml parameters

---

docs/README.md

As the build has heavily changed recently, we need to document those changes.

docs: add docs publishing information

---

.github/workflows/htmltest.yaml
docs/Makefile

Adding Caching of hugomodules to the makefile and build target.
This way, we don't need to fetch them all the time. This should
speed up the build time, especially on slow internet connections.

chore: add Hugo caching

---

docs/content/en/docs/tasks/write-tasks/_index.md

docs: added more detailed explanation of how to make use of secrets in KeptnTasks

---

metrics-operator/config/manager/manager.yaml
metrics-operator/config/manager/service.yaml
metrics-operator/main.go
metrics-operator/pkg/metrics/server.go
test/integration/expose-keptn-metric/00-install.yaml
test/integration/expose-keptn-metric/01-install.yaml

Follow up to #823 
This PR fixes the setup of the K8s service and deployment to be able to access the metrics API endpoint

fix(metrics-operator): use correct port for serving metrics api

---

docs/CONTRIBUTING.md

This PR creates a CONTRIBUTING.md file that is modeled on that file for the keptn.github.io repo.  It has mostly been updated to be appropriate for KLT but note the following:
* This file contains a detailed "github cheatsheat" that should more properly be in the Contributor Guide.  When that document includes this information, we will delete it from this file.
* I did not modify the information about updating the current version of the docs versus providing changes that should only be published for the next release until we define exactly how we are going to handle that.
* I did not provide details about the structure of the docs source because we have not finalized the plan for how we are going to structure the source.
*

docs: add CONTRIBUTING.md file for docs

---

operator/test/component/taskdefinitioncontroller_test.go

test: introduce component test for KeptnTaskDefinition controller

---

docs/config/production/params.yaml

This would be fixed with the next release, but we want to be consistent, so here is the change for the testing. As the branch is already protected, we are doing this by PR.

chore: fix development url in page branch

---

README.md
docs/CONTRIBUTING.md
docs/README.md
docs/content/en/docs/concepts/keptnConfig/_index.md
docs/content/en/docs/crd-ref/_index.md
docs/content/en/docs/snippets/tasks/install.md
docs/content/en/docs/tasks/migrate-keptnevaluationprovider/_index.md
examples/Makefile
klt-cert-manager/README.md
metrics-operator/README.md
operator/README.md
scheduler/README.md

Fixes: #597 
PLEASE do not merge this until we do not have a first version of helm-charts released

docs: use helm charts instead of manifests + document KeptnConfig CRD

---

.github/workflows/CI.yaml

- sets the registry correctly to the scarf one for released helm charts
- uses better branch naming for the charts repo PRs so that ehy are overwritten with pushes to keptn/klt main branch

fix: helm chart generation fixes

---

docs/CONTRIBUTING.md
docs/README.md

This PR removes the outdated step to run `make clone`

docs: update README and CONTRIBUTING instructions

---

.github/stale.yml

- adds the stale bot to this repo
- configures stale bot so that issues  with 60 days of inactivity get marked as "stale" with a label
- issues get closed after they have been labeled stale for 7 days and without further activity

chore: close issues and PRs if they get stale

---

docs/README.md
docs/config/_default/params.yaml
docs/config/production/params.yaml
netlify.toml

set the urls properly for the new page.
Update the github_branch to point always to the current branch, which netlify used for a build

chore: set new documentation approach live

---

metrics-operator/config/metrics/role.yaml
metrics-operator/config/metrics/role_binding.yaml

This PR adds the `metrics-operator` prefix to the ClusterRole and ClusterRoleBinding required by the HPA to read KeptnMetrics.  The resulting names are now:
```
server-resources --> metrics-operator-server-resources
hpa-controller-keptn-metrics -> metrics-operator-hpa-controller 
```
The name of the ClusterRoleBinding has been changed to avoid errors when upgrading from the previous version, due to the limitation of not being able to change the roleRef of an existing ClusterRoleBinding

fix: added metric-operator prefix to related ClusterRole and ClusterRoleBindings

---

.github/labeler.yml
.github/workflows/update-labels.yml

- adds the `actions/labeler` to this repo so that PRs get labeled depending on the content that they update
Fixes #927

ci: add auto labeling for PRs

---

docs/config/_default/config.yaml
docs/go.mod
docs/go.sum

Our theme has matured and is now part of the keptn organization. The first release v0.0.1 is a simple fork of the keptn-sandbox version.
We will gradually increase our repository and hope to improve it to be generally available for all our tools.

chore: change theme repository

---

helm/chart/Chart.yaml
helm/overlay/kustomization.yaml

Further, this PR modifies the minimum version check for K8s to also allow prerelease versions of K8s, since I ran into an error telling me that the chart can not be installed on `v1.25.6-gke.1000`

fix: adapted patch for mutating webhook to correctly add release namespace to exclusions

---

.github/workflows/release.yml

- fixes some issues with cosign during signing and verification by signing the image by digest and not by tag
- verification of images behind the released tags should still be possible with this solution

fix: fix cosign image signing after breaking changes

---

metrics-operator/controllers/common/providers/common.go
metrics-operator/controllers/common/providers/datadog/common.go
metrics-operator/controllers/common/providers/datadog/common_test.go
metrics-operator/controllers/common/providers/datadog/datadog.go
metrics-operator/controllers/common/providers/datadog/datadog_test.go
metrics-operator/controllers/common/providers/provider.go
metrics-operator/controllers/common/providers/provider_test.go
metrics-operator/go.mod
metrics-operator/go.sum

Fixes #554
**_Due to a breaking change I have closed my previous draft and opened this updated one._**
I am hoping to get your opinion on DataDog APIs. I'm still getting the hang of things and would appreciate your input on what I've learned so far and where to go next. As a newcomer to DataDog, I'm eager to soak up as much knowledge as possible, so any assistance you can provide would be awesome :+1: 
**Progress**
- I have looked into the [dyantrace.go](https://github.com/keptn/lifecycle-toolkit/blob/main/metrics-operator/controllers/common/providers/dynatrace/dynatrace.go) and [prometheus.go](https://github.com/keptn/lifecycle-toolkit/blob/main/metrics-operator/controllers/common/providers/prometheus/prometheus.go) files and tried to understand EvaluateQuery function.
- Similar to the …

feat: datadog metric provider for KLT

---

.github/workflows/CI.yaml
helm/chart/Chart.yaml
helm/chart/README.md
helm/chart/doc.yaml
helm/chart/values.yaml
klt-cert-manager/config/manager/kustomization.yaml
metrics-operator/config/manager/kustomization.yaml
operator/config/manager/kustomization.yaml
scheduler/manifests/install/kustomization.yaml

- adds some missing values that were not re-auto-generated before the v0.7.0 release
- adds docs for the missing values
- updates changes from released chart version 0.2.1
- fixes a pipeline issue that prevented renamed files to be deleted during `rsync`

fix(helm-chart): fix missing values in the KLT helm chart

---

operator/apis/lifecycle/v1alpha3/keptnappversion_test.go
operator/apis/lifecycle/v1alpha3/keptntask_test.go
operator/apis/lifecycle/v1alpha3/keptntask_types.go
operator/apis/lifecycle/v1alpha3/keptntaskdefinition_types.go
operator/apis/lifecycle/v1alpha3/keptnworkloadinstance_test.go
operator/apis/lifecycle/v1alpha3/zz_generated.deepcopy.go
operator/config/crd/bases/lifecycle.keptn.sh_keptntaskdefinitions.yaml
operator/config/crd/bases/lifecycle.keptn.sh_keptntasks.yaml
operator/controllers/common/taskhandler.go
operator/controllers/common/taskhandler_test.go
operator/controllers/errors/errors.go
operator/controllers/lifecycle/keptntask/function_utils.go
operator/controllers/lifecycle/keptntask/job_utils.go
operator/controllers/lifecycle/keptntask/job_utils_test.go
operator/test/component/task/task_test.go
test/integration/app-failing-pre-task-retry/00-assert.yaml
test/integration/app-failing-pre-task-retry/00-install.yaml
test/integration/app-failing-pre-task-retry/00-teststep.yaml
test/integration/app-failing-pre-task-timeout/00-assert.yaml
test/integration/app-failing-pre-task-timeout/00-install.yaml
test/integration/app-failing-pre-task-timeout/00-teststep.yaml

feat(operator): introduce retry logic for KeptnTasks

---

.github/actions/deploy-prometheus-on-cluster/action.yml
Makefile

closes #1085
1. `kind create cluster`
2. `helm upgrade --install klt klt/klt  -n keptn-lifecycle-toolkit-system   --create-namespace`
3. than run `make integration-test-local ` now Prometheus is installed before running so all tests pass locally

fix: move prometheus install into make file

---

.github/workflows/validate-semantic-pr.yml
examples/sample-app/base/app.yaml
examples/sample-app/base/manifest.yaml
examples/sample-app/base/provider.yaml
examples/sample-app/version-1/app.yaml
examples/sample-app/version-2/app.yaml
examples/sample-app/version-3/app.yaml
examples/support/observability/Makefile
examples/support/observability/config/otel-collector.yaml
examples/support/observability/config/prometheus-mock/mockserver-config.yaml
examples/support/observability/config/prometheus/grafana-deployment.yaml
examples/support/observability/config/prometheus/kube-state-metrics-deployment.yaml
examples/support/observability/config/prometheus/node-exporter-daemonset.yaml
examples/support/observability/config/prometheus/prometheus-adapter-deployment.yaml
examples/support/observability/config/prometheus/prometheus-prometheus.yaml
examples/support/observability/config/prometheus/setup/prometheus-operator-deployment.yaml

- fixes a bug in the examples makefile where a missing namespace broke the setup
- reduces the resource footprint for o11y support software
- reduces the resource footprint of the podtato-head example app by removing the legs
- makes use of https://github.com/mock-server/mockserver instead of prometheus to mock metrics

feat: make examples resource footprint smaller, fix bugs

---

scheduler/pkg/klcpermit/permit.go

fix: removed failure branch

---

.github/workflows/validate-helm-chart.yml
.yamllint
helm/chart/values.yaml
klt-cert-manager/config/rbac/role.yaml
metrics-operator/config/crd/bases/metrics.keptn.sh_keptnmetrics.yaml
metrics-operator/config/crd/bases/metrics.keptn.sh_keptnmetricsproviders.yaml
metrics-operator/config/rbac/role.yaml
operator/config/crd/bases/lifecycle.keptn.sh_keptnapps.yaml
operator/config/crd/bases/lifecycle.keptn.sh_keptnappversions.yaml
operator/config/crd/bases/lifecycle.keptn.sh_keptnevaluationdefinitions.yaml
operator/config/crd/bases/lifecycle.keptn.sh_keptnevaluationproviders.yaml
operator/config/crd/bases/lifecycle.keptn.sh_keptnevaluations.yaml
operator/config/crd/bases/lifecycle.keptn.sh_keptntaskdefinitions.yaml
operator/config/crd/bases/lifecycle.keptn.sh_keptntasks.yaml
operator/config/crd/bases/lifecycle.keptn.sh_keptnworkloadinstances.yaml
operator/config/crd/bases/lifecycle.keptn.sh_keptnworkloads.yaml
operator/config/crd/bases/options.keptn.sh_keptnconfigs.yaml
operator/config/rbac/role.yaml

- fixed helm generation checker pipeline
- executed `make manifests && make generate` on each operator
- executed `make helm-package`
- add ignore to yamllint check for generated files (they have different indentation)

fix: helm generation checker pipeline

---

docs/.htmltest.yml
docs/config/_default/config.yaml
docs/content/en/_index.md
docs/go.mod
docs/go.sum
docs/static/google2c8933a0d1bc803c.html

It is hard to navigate our community files within GitHub. They're not well structured etc. To make this problem more visible, we integrate them into the webpage.
This way, we can easier manage them, fix any content issues and share this for multiple pages.
close: #1009

docs: add community files to webpage

---

examples/Makefile
examples/support/observability/Makefile
examples/support/observability/config/otel-collector.yaml

The examples have been changed to support Killercoda and the limited resource available there. However, this breaks all the tutorials and examples. We should instead provision a new repo for just running the killercoda demo.

fix: fix kubecon examples

---

.github/workflows/set-date.yml

Modified the `set-date.yml` file to fix the [issue](https://github.com/keptn/lifecycle-toolkit/actions/runs/4667145006/jobs/8262562937) with the set-date pipeline.
After the modification of YAML files (due to the addition of YAMLLinter), there was an extra space added in the `Get project data` step. I have modified the step and it should work properly now.

ci: fix set-date pipeline bug

---

docs/config/_default/config.yaml

Within #1077 a small regression slipped through, due to the constant rebasing.

fix: adapt mapping for community files

---

.github/scripts/generate-crd-docs/generate-crd-docs.sh
docs/content/en/docs/concepts/metrics/_index.md
docs/content/en/docs/crd-ref/metrics/v1alpha2/_index.md
docs/content/en/docs/crd-ref/metrics/v1alpha3/_index.md
examples/sample-app/base/metric.yaml
examples/sample-app/base/provider.yaml
examples/support/metrics/README.md
examples/support/metrics/hpa.yaml
examples/support/metrics/metric.yaml
examples/support/observability/assets/podtatohead-deployment-evaluation/available-cpus-metric.yaml
examples/support/observability/assets/podtatohead-deployment-evaluation/consumed-memory-metric.yaml
examples/support/observability/assets/podtatohead-deployment-evaluation/metricsprovider.yaml

- adjusts the API reference generator script to work with the metrics API under the metrics operator
- re-generates all metrics API references pages
- adjusts all KeptnMetricProvider occurrences to the new API version while also introducing the new `type` field
- adds some info about support for multiple providers of the same type
Part of #1144

docs: update docs for multi metrics provider support, fix API reference generator

---

operator/controllers/common/otel_utils.go
operator/controllers/common/otel_utils_test.go
operator/controllers/options/keptnconfig_controller.go
operator/controllers/options/keptnconfig_controller_test.go

Closes #1261
With these changes the traces should be exported correctly again:

fix(operator): fix otel collector URL setup 

---

CODEOWNERS

improving the CODEOWNERs With the new keptn-org team-structure for easier maintaince and configuration.
The CODEOWNERS are now defined via teams, which are configured with peribolos within #keptn/community
closes: #1180
blocked-by: keptn/community#280

chore: adapt CODEOWNERS to new team structure

---

.github/scripts/generate-crd-docs/generate-crd-docs.sh

As the crd-ref relies on the GOPATH to be part of PATH, we will add this in the script, as not everyone might have this setup properly.

feat: improve API reference generation script with path extension

---

docs/assets/scss/_variables_project.scss
docs/content/en/_index.md

Fixes #1136 
Modified the footer of the website with the following changes:
- In the Keptn Recordings part, added a new button that redirects to Youtube.
- Renamed the `Read more....` to `Github` in the contributions welcome part.
- Renaming the `Read more...` to `Twitter` in the Follow us on Twitter part.
- Added a new `assets/scss/_variable_project.scss` file for the custom modification of the styles.

docs: modify footer

---

operator/apis/lifecycle/v1alpha3/common/common.go
operator/apis/lifecycle/v1alpha3/common/common_test.go
operator/apis/lifecycle/v1alpha3/keptnappversion_test.go
operator/apis/lifecycle/v1alpha3/keptnappversion_types.go
operator/apis/lifecycle/v1alpha3/keptntask_test.go
operator/apis/lifecycle/v1alpha3/keptntask_types.go
operator/apis/lifecycle/v1alpha3/keptnworkloadinstance_test.go
operator/apis/lifecycle/v1alpha3/keptnworkloadinstance_types.go
operator/controllers/lifecycle/keptntask/function_utils.go
operator/controllers/lifecycle/keptntask/job_utils_test.go
operator/test/component/task/task_test.go

feat(operator): propagate KeptnTaskDefinition labels and annotations to Job Pods

---

operator/controllers/lifecycle/keptnevaluation/controller.go
operator/controllers/lifecycle/keptnevaluation/controller_test.go
operator/test/component/evaluation/evaluation_test.go

Closes #1339 
This PR adds the reason for a failing evaluation in the `status.message` field of the evaluation CR.
As a result, the reason will also be properly displayed in the trace event - see screenshot below

feat(operator): add information about evaluation target in status

---

docs/content/en/docs/getting-started/orchestrate/_index.md

The headline in the getting started section has a wrong caption

docs: improve headline of Getting Started subsection

---

docs/go.mod
docs/go.sum

Go files have been cleaned with `go mod tidy` but that does not incoporate the hugo dependencies, so everyone know has changes, as soon as they start the docs server or build them.

fix: restore go files

---

docs/content/en/docs/getting-started/generic-gs/_index.md

Replaces https://github.com/keptn/lifecycle-toolkit/pull/1309 
* Re-title this exercise; probably needs further revisions
* A bit of rewriting of text before we get into the actual exercise
Note that some info was moved to other pages in the docs (see https://github.com/keptn/lifecycle-toolkit/pull/1364):
* Small additions to "Requirements" to capitalize on info from the Getting Started guide
* Add "Prepare your cluster for KLT" section to install/k8s.md page.  All these getting-started guides and probably other documents need to reference that list of what their k8s cluster needs to have, but better to have it in one place than try to maintain multiple copies
Satisfies https://github.com/keptn/lifecycle-toolkit/issues/1306 
Satisfies https://github.com/keptn/lifecycle-toolkit/issues/1307

docs: small edit of original Getting Started guide

---

docs/content/en/docs/install/install.md

I had a bit of additional information in the Getting Started guides.  We want to just reference the Install page for that so I need to get that info onto the install page.  That is what this PR does.

docs: enhance install page

---

docs/content/en/docs/install/_index.md

Tweaks to the Install landing page to support Getting Started guides

docs: improve list on install landing page

---

docs/content/en/docs/getting-started/metrics/_index.md

@agardnerIT commented:
Nitpicking but: Datadog, Dynatrace, Lightstep, Honeycomb, Splunk
1) missing Prometheus
2) it should be alphabetical OR we are subtly suggesting that datadog is better than DT.
3) (My opinion) but we shouldn’t give free promotion. If the vendors want their name listed here, they should write a provider. By giving this list, we’re putting Honeycomb on the same footing at DT.
This PR:
* Adds Prometheus to the list of data providers and arranges them in the order they were implemented for KLT
* Replaced the names of other data providers with "and others"
* Tweaked the prose a bit for better flow

docs: mention Prometheus in intro

---

metrics-operator/api/v1alpha3/keptnmetric_types.go
metrics-operator/api/v1alpha3/keptnmetric_types_test.go

The introduced method was removed by this PR https://github.com/keptn/lifecycle-toolkit/commit/3c465d07044b0317cbb6e462004dff9cf8f1d533#diff-62dbadcf91fc4f2b7cb287a2251c530635223016577a548b21fcf6eda8291137L134
but it's used by the klt-operator here https://github.com/keptn/lifecycle-toolkit/blob/main/operator/controllers/common/providers/keptnmetric/keptnmetric.go#L27

fix(metrics-operator): introduce IsStatusSet method to KeptnMetric

---

docs/config/_default/config.yaml

backport of https://github.com/keptn/lifecycle-toolkit/pull/1461

docs: fix link to v1 docs

---

operator/controllers/common/fake/fakeclient.go
operator/controllers/lifecycle/keptnappversion/controller_test.go
operator/controllers/lifecycle/keptnappversion/reconcile_workloadsstate.go
operator/controllers/lifecycle/keptnappversion/reconcile_workloadstate_test.go
operator/controllers/lifecycle/keptnworkloadinstance/controller.go

chore(operator): use List() when fetching KeptnWorkloadInstances for KeptnAppVersion

---

metrics-operator/controllers/common/providers/datadog/datadog.go
metrics-operator/controllers/common/providers/datadog/datadog_test.go
metrics-operator/controllers/common/providers/dynatrace/common.go
metrics-operator/controllers/common/providers/dynatrace/dynatrace.go
metrics-operator/controllers/common/providers/dynatrace/dynatrace_dql.go
metrics-operator/controllers/common/providers/dynatrace/dynatrace_dql_test.go
metrics-operator/controllers/common/providers/dynatrace/dynatrace_test.go
metrics-operator/controllers/common/providers/provider_test.go
metrics-operator/controllers/metrics/controller.go

1.  handles hidden error in the response of metrics providers 
2.  adds trim of queries from dt provider so that spaces and new lines are allowed.
3.  in case error may not be clear returns the raw value of the provider response
1. pass a wrong token, API returns error that is logged and stored in the KeptnMetrics ex
`Status:              
Err Msg:       provider api response: Token Authentication failed                       `          
2. use a metric like so or change >- with | :
```
apiVersion: metrics.keptn.sh/v1alpha3
kind: KeptnMetric
metadata:
name: podtatometric
namespace: keptn-lifecycle-toolkit-system
spec:
provider:
name: "dynatrace"
query:  >-
(( builtin:kubernetes.workload.cpu_throttled
:filter(eq("k8s.workload.name","frontend")) …
```

fix(metrics-operator): improve error handling in metrics providers

---

klt-cert-manager/controllers/keptnwebhookcontroller/keptnwebhookcertificate_controller.go
klt-cert-manager/controllers/keptnwebhookcontroller/webhook_cert_controller_test.go

This PR fixes a copy paste error that can potentially lead to index out of bounds errors when iterating through the list of matching `ValidatingWebhookConfigurations`.

fix(cert-manager): avoid index-out-of-bounds error when updating webhook configs

---

.github/actions/deploy-klt-on-cluster/action.yml
.github/workflows/CI.yaml
.github/workflows/e2e-test.yml
.github/workflows/helm-checks.yaml
.github/workflows/integration-test.yml
.github/workflows/load-test.yml
.github/workflows/performance-test.yml
.github/workflows/release.yml
.github/workflows/security-scans.yml
.github/workflows/validate-semantic-pr.yml
helm/chart/README.md
helm/chart/doc.yaml
helm/chart/values.yaml
operator/config/manager/manager.yaml
python-runtime/Dockerfile
renovate.json

Fixes: #1491 
- changed python-runtime base image from `python:3.9` to `python:3.9-alpine` to make the image size smaller
- added python-runtime to all pipelines
- added env variable pointing to the image into klt-operator Deployment
- added helm value for setting up the image + updated the docs
Image available in ghrc: https://github.com/keptn/lifecycle-toolkit/pkgs/container/python-runtime

feat: integrate python-runtime into pipelines

---

.github/workflows/validate-semantic-pr.yml

- disables the semantic PR check for single commit PRs preventing PRs to be merged that have a single commit that is not semantic. This is not needed anymore since github introduced a setting to always use the PR title as the commit message during squash and merge.

ci: remove requirement for semantic commit in single-commit PRs

---

operator/main.go
operator/webhooks/pod_mutator/pod_mutating_webhook.go
operator/webhooks/pod_mutator/pod_mutating_webhook_test.go

Fixes #1445 Removed Decoder Injector interface from webhook and explicitly initialized the decoder in the operator main
Signed-off-by: geoffrey1330 <israelgeoffrey13@gmail.com>

chore: remove decoder injector interface from webhook

---

.github/actions/deploy-klt-on-cluster/action.yml
.github/workflows/CI.yaml
.github/workflows/component-test.yml
.github/workflows/golangci-lint.yml
.github/workflows/markdown-checks.yaml
.github/workflows/release.yml
.github/workflows/security-scans.yml

- adds the `check-latest` option to all `setup-go` actions so that the latest go version within the defined version constraint will be used even if the cache has a different/older but valid version
- will partly solve #1545

ci: add check for latest version and fix cache path

---

.github/workflows/release.yml
docs/Makefile
docs/go.mod
docs/go.sum
netlify.toml

- updates the docs-tooling version to v0.1.2
- updates the keptn/community import to the latest master commit hash
- fixes the edit links on the KLT docs page by injecting the branch name differently in the `netlify.toml` file
- updates hugo to `0.111.3`

docs: fix edit links

---

helm/chart/README.md
helm/chart/values.yaml
klt-cert-manager/.gitignore
metrics-operator/.gitignore
operator/config/manager/manager.yaml

- sets the Python runtime version to the current KLT version so that it will be updated correctly during the release
- changes some minor things in the gitignore files

fix(helm-chart): fix Python runtime version number

---

docs/content/en/docs/yaml-crd-ref/taskdefinition.md

https://github.com/keptn/lifecycle-toolkit/pull/1579 does not pick up that the `deno-runtime` runner is now defined as `deno` rather than `function`.  This PR corrects the Synopsis, Examples, and Differences between versions info.

docs: `deno` rather than `function` for deno-runtime runner

---

.github/workflows/release.yml
.markdownlint-cli2.yaml
helm/chart/values.yaml
klt-cert-manager/Dockerfile
release-please-config.json

- sets up release please to work with the KLT repo as a monorepo with separate releases for KLT and KLT cert-manager
- Separate release PRs will be created for the 2 artifacts that can be merged separately. Release Please will create separate git tags and github releases for 2 artifacts as well
Fixes: #1139

feat: cert-manager monorepo setup

---

docs/content/en/docs/getting-started/generic-gs/_index.md

fixed an issue with collapsible caret/arrow ending page text was hiding under "watch pods" section

docs: fix </details> ending under watch pods

---

docs/content/en/docs/getting-started/generic-gs/_index.md

fixed an issue with collapsible caret/arrow ending page text was hiding under "watch pods" section

docs: fix </details> ending under watch pods in _index.md

---

python-runtime/Dockerfile

The missing curl binary in the ython runtime image was preventing scripts referenced via url to be executed. This PR resolves that

fix(python-runtime): install curl to execute scripts referenced via url

---

operator/controllers/common/otel_utils.go
operator/controllers/common/otel_utils_test.go
operator/controllers/lifecycle/keptnappcreationrequest/controller.go
operator/controllers/lifecycle/keptnappcreationrequest/controller_test.go
test/integration/container-runtime/00-assert.yaml
test/integration/simple-deployment-python-runtime/00-assert.yaml
test/integration/simple-deployment-recursive-task/01-assert.yaml
test/integration/simple-deployment-sanitize-version-number/01-assert.yaml
test/integration/simple-deployment/01-assert.yaml

BEGIN_COMMIT_OVERRIDE
fix(operator): provide the right app version for single-service applications
chore(operator): print trace in the logs only if the collector is not enabled
END_COMMIT_OVERRIDE
fixes #1667

fix(operator): provide the right app version for single-service applications

---

metrics-operator/api/v1alpha3/keptnmetric_types.go
metrics-operator/config/crd/bases/metrics.keptn.sh_keptnmetrics.yaml

Fixes #1677
Changes made:
- Introduced a new `interval` field for `kubectl get KeptnMetric`.
- This field has the value of `metric.spec.range.interval` field.
Some screenshots:
- With `range.interval` field defined
- Without a `range.interval` field defined

feat: add `interval` field for `kubectl get KeptnMetric`

---

operator/controllers/lifecycle/keptntask/job_runner_builder.go
operator/controllers/lifecycle/keptntask/job_utils.go
operator/controllers/lifecycle/keptntask/runtime_builder.go
operator/controllers/lifecycle/keptntask/runtime_builder_test.go

There is no need to export EventSender in BuilderOptions, therefore we can hide it
Failing helm-chart validation check will be fixed with https://github.com/keptn/lifecycle-toolkit/pull/1697

chore(operator): unexport EventSender in BuilderOptions

---

docs/content/en/docs/intro-klt.md

Fixed typo: "Keptn Metrics Server unifies and standardizes access to data from arious sources" -> "Keptn Metrics Server unifies and standardizes access to data from various sources"

docs: fix typo

---

.github/workflows/stale.yml

fix: This will create a reminder after 3 weeks of assigned issues and thereafter will put a label "to be unassigned" in a week
fixes #1709

ci: create jobs to unassign stale good first issues

---

docs/content/en/docs-v0.8.0/yaml-crd-ref/evaluationdefnition.md
docs/content/en/docs/yaml-crd-ref/evaluationdefnition.md

Fix #1727
Removing [evaluationdefnition.md](https://lifecycle.keptn.sh/docs/yaml-crd-ref/evaluationdefnition/) file - eliminating duplication and enhancing clarity
cc @StackScribe

docs: remove evaluationdefnition.md for codebase clarity

---

operator/apis/lifecycle/v1alpha3/common/phases.go
operator/controllers/common/evaluationhandler.go
operator/controllers/common/evaluationhandler_test.go
operator/controllers/common/phasehandler.go
operator/controllers/common/taskhandler.go
operator/controllers/lifecycle/keptnapp/controller.go
operator/controllers/lifecycle/keptnapp/controller_test.go
operator/controllers/lifecycle/keptnappversion/controller.go
operator/controllers/lifecycle/keptnappversion/controller_test.go
operator/controllers/lifecycle/keptnappversion/reconcile_workloadsstate.go
operator/controllers/lifecycle/keptnevaluation/controller.go
operator/controllers/lifecycle/keptntask/job_utils.go
operator/controllers/lifecycle/keptntask/runtime_builder.go
operator/controllers/lifecycle/keptntaskdefinition/reconcile_function.go
operator/controllers/lifecycle/keptnworkload/controller.go
operator/controllers/lifecycle/keptnworkloadinstance/controller.go
operator/controllers/lifecycle/keptnworkloadinstance/controller_test.go
operator/webhooks/pod_mutator/pod_mutating_webhook.go

Fixes: #1683 
- standardize k8s Events on lifecycle path - introduce started, finished and failed events
- introduce PhaseStates of Phases and make use of them in the code
- remove k8s Events creating big noise and having no big value for the end users (not finished Events, ...)
- add more tests
- normalize all Events to use the same pattern

chore(operator): standardize k8s Events on lifecycle path

---

helm/chart/README.md
helm/chart/doc.yaml

- fixes #1734 
- removes the cert manager release please annotation comment in the helm readme so that it doesn't get the same version as KLT anymore (since it has its own versioning now in a monorepo fashion)

fix: remove klt-cert-manager from version bumps during KLT release

---

docs/content/en/docs/crd-ref/_index.md
docs/content/en/docs/crd-ref/metrics/v1alpha3/_index.md
docs/content/en/docs/yaml-crd-ref/_index.md

This PR does the following:
* Renames the yaml-crd-ref section to be "Manifest CRD Reference"
* Adds xrefs between the two sections to the landing pages of crd-ref and yaml-crd-ref
* Removes some duplicated info from the yaml-crd-ref landing page
* Adds instructions for inspecting an existing resource

docs: manifests ref section, edits to ref section intros

---

.github/workflows/markdown-checks.yaml
metrics-operator/api/v1alpha3/keptnmetric_types.go

ci: adapt markdown check trigger to include changes to CRD structs 

---

.github/workflows/release.yml
helm/chart/README.md
helm/chart/doc.yaml
metrics-operator/Dockerfile
release-please-config.json

- sets up release please to work with the KLT repo as a monorepo with separate releases for KLT lifecycle-operator, KLT cert-manager and KLT metrics-operator
- Separate release PRs will be created for the 3 artifacts that can be merged separately. Release Please will create separate git tags and github releases for 3 artifacts as well
- renamed general klt release to lifecycle-operator, as from now it's a monorepo itself
- remove release-please tag for metrics-operator on helm docs auto updates
- re-generate CRD documentation
Fixes: #1597 
This could be test only on fork:
PRs creted: https://github.com/odubajDT/lifecycle-controller/pulls
release please run: https://github.com/odubajDT/lifecycle-controller/actions/runs/5691308796/job/15426250933

feat: metrics-operator monorepo setup

---

docs/content/en/docs/install/cert-manager.md

This PR:
- Adds text explaining the name change from `certs-dir` to `cert`
@StackScribe as discussed, could I get a quick approval on this and we can see if this makes it's way to live quickly.

docs: add text about name change

---

README.md

After the python, deno, and container runtime release, we can mark it as beta. 
This feature can be marked as stable after we have the readiness gate put in place with #1448

chore: promote Release Lifecycle to beta

---

docs/content/en/docs/implementing/dora/_index.md
docs/content/en/docs/implementing/otel.md

This PR fixes: #1747 
[The kubectl command](https://github.com/keptn/lifecycle-toolkit/blob/main/docs/content/en/docs/implementing/dora/_index.md?plain=1#L40-#L43) on the DORA page doesn't work when users install using helm because helm prepends the chart name to the svc name.
Changes suggested by @agardnerIT are applied here.
Before:
After:

docs: adapt DORA metrics kubectl command

---

docs/content/en/docs/concepts/architecture/cert-manager.md
docs/content/en/docs/install/cert-manager.md
docs/content/en/docs/install/k8s.md
helm/chart/templates/analysis-crd.yaml
helm/chart/templates/analysisdefinition-crd.yaml
helm/chart/templates/analysisvaluetemplate-crd.yaml
helm/chart/templates/keptnapp-crd.yaml
helm/chart/templates/keptnappcreationrequest-crd.yaml
helm/chart/templates/keptnappversion-crd.yaml
helm/chart/templates/keptnconfig-crd.yaml
helm/chart/templates/keptnevaluation-crd.yaml
helm/chart/templates/keptnevaluationdefinition-crd.yaml
helm/chart/templates/keptnevaluationprovider-crd.yaml
helm/chart/templates/keptnmetric-crd.yaml
helm/chart/templates/keptnmetricsprovider-crd.yaml
helm/chart/templates/keptntask-crd.yaml
helm/chart/templates/keptntaskdefinition-crd.yaml
helm/chart/templates/keptnworkload-crd.yaml
helm/chart/templates/keptnworkloadinstance-crd.yaml
helm/chart/templates/lifecycle-mutating-webhook-configuration.yaml
helm/chart/templates/lifecycle-validating-webhook-configuration.yaml
helm/chart/templates/metrics-validating-webhook-configuration.yaml

- added `ca-injection` annotations to webhooks and CRDs
- update documentation how to use external cert-manager
Fixes: https://github.com/keptn/lifecycle-toolkit/issues/1809

chore: support external cert-manager

---

docs/content/en/docs/concepts/architecture/keptn-apps/_index.md
docs/content/en/docs/getting-started/observability/_index.md
docs/content/en/docs/getting-started/orchestrate/_index.md
docs/content/en/docs/implementing/integrate/_index.md
docs/content/en/docs/implementing/tasks/_index.md
docs/content/en/docs/install/_index.md
docs/content/en/docs/install/install.md
docs/content/en/docs/yaml-crd-ref/app.md
docs/content/en/docs/yaml-crd-ref/taskdefinition.md

Replaces https://github.com/keptn/lifecycle-toolkit/pull/1785 .  That PR had lots of reviews and discussions but got corrupted.
Closes https://github.com/keptn/lifecycle-toolkit/issues/1732 
*  This PR corrects and clarifies info about integrating KLT into a Kubernetes workflow/cluster
* Also adds remarks about annotations vs labels
* This PR includes an architecture piece about KeptnApp and KeptnWorkload but we decided that this belongs in the section about the Scheduler (https://github.com/keptn/lifecycle-toolkit/pull/1777).  This file is temporarily still here until Yash can grab it.
* Information about the annotations for pre/post-deployment evaluations/tasks really is not part of Integrating the app.  We probably need a separate page about using the release lifecycle management …

docs: improve how-to and ref info for apps

---

lifecycle-operator/controllers/common/eventsender_test.go

This is a follow up to #1844 to get rid of the sleep in the unit tests, and use the auto generated mock event emitter instead of defining a new type in the unit tests

refactor(lifecycle-operator): refactor event emitter unit tests

---

lifecycle-operator/controllers/common/phasehandler.go
lifecycle-operator/controllers/common/phasehandler_test.go
lifecycle-operator/controllers/lifecycle/keptnappversion/controller.go
lifecycle-operator/controllers/lifecycle/keptnappversion/reconcile_workloadsstate.go

fix(lifecycle-operator): avoid setting the overall state of an App or WorkloadInstance between state transitions

---

docs/content/en/contribute/docs/contribution-guidelines/_index.md
docs/content/en/contribute/docs/source-file-structure/_index.md
docs/content/en/contribute/general/technologies/_index.md
docs/content/en/docs/concepts/architecture/cert-manager.md
docs/content/en/docs/concepts/architecture/components/metrics-operator/_index.md
docs/content/en/docs/concepts/architecture/keptn-apps/_index.md
docs/content/en/docs/crd-ref/lifecycle/v1alpha2/_index.md
docs/content/en/docs/crd-ref/lifecycle/v1alpha3/_index.md
docs/content/en/docs/getting-started/_index.md
docs/content/en/docs/implementing/_index.md
docs/content/en/docs/implementing/add-app-awareness/index.md
docs/content/en/docs/implementing/integrate/_index.md
docs/content/en/docs/implementing/otel.md
docs/content/en/docs/implementing/restart-application-deployment/_index.md
docs/content/en/docs/implementing/tasks/_index.md
docs/content/en/docs/install/k8s.md
docs/content/en/docs/install/upgrade.md
docs/content/en/docs/intro-klt/_index.md
docs/content/en/docs/intro-klt/usecase-orchestrate.md
docs/content/en/docs/intro-klt/usecase_metrics.md
docs/content/en/docs/migrate/strategy/_index.md
docs/content/en/docs/troubleshooting.md
docs/content/en/docs/tutorials/_index.md
docs/content/en/docs/yaml-crd-ref/app.md
docs/content/en/docs/yaml-crd-ref/metric.md
docs/content/en/docs/yaml-crd-ref/taskdefinition.md
lifecycle-operator/apis/lifecycle/v1alpha2/keptnworkloadinstance_types.go
lifecycle-operator/apis/lifecycle/v1alpha3/keptntaskdefinition_types.go
lifecycle-operator/apis/lifecycle/v1alpha3/keptnworkloadinstance_types.go

- fixes tons of typos and grammar errors
- fixes the left sidebar items not being aligned by removing the `icon: concepts` from all page headers

docs: fix typos and grammar issues

---

docs/content/en/docs/yaml-crd-ref/taskdefinition.md

Deno seems to have renamed their web page and it is causing failures in other PRs.  This PR replaces the deno.com link with what appears to be the correct link.

docs: fix link to deno web page

---

.github/PULL_REQUEST_TEMPLATE/pr-template.md

- adds a default PR template for docs and code contributions
Fixes #1242

chore: create pull request template

---

README.md

This is a proposed rewrite of the main KLT README file.  It strips out information that is now included in the main doc set, adds some headers, etc.  I also implemented the new product naming conventions -- please verify that they are done correctly.
Please consider whether this is the appropriate information to have in the README file, remembering that we want to minimize the duplication of information that must be maintained as the product evolves.
I did not strip out the Architecture section.  That should be removed when the relevant information has been merged into the Architecture section of the documentation.

docs: rewrite README file

---

CONTRIBUTING.md
docs/CONTRIBUTING.md
docs/content/en/contribute/general/dco/_index.md

Closes https://github.com/keptn/lifecycle-toolkit/issues/1884 
This PR:
* Combines/rewrites info about working with DCO from the main CONTRIBUTING.md and docs CONTRIBUTING.md files
* Replaces the DCO content in the main CONTRIBUTING.md file with a link to this page
* Replaces the DCO content in the main CONTRIBUTING.md file with a link to this page

docs: contrib: DCO

---

docs/content/en/docs/implementing/evaluatemetrics.md
docs/content/en/docs/install/k8s.md
docs/content/en/docs/migrate/metrics-observe/_index.md

closes https://github.com/keptn/lifecycle-toolkit/issues/1609 
* How to migrate keptn v1 SLIs/SLOs to KLT metrics and evaluations
* Moved basic info about implementing KeptnMetricsProvider to main docs; it is not specific to migration

docs: migrate quality gates

---

metrics-operator/converter/sli_converter_test.go

Order of the results in manifests is not guaranteed, as we unmarshal the data to a map, which does not guarantee the order of the elements by default

fix(metrics-operator): flaky test in SLI converter

---

metrics-operator/api/v1alpha3/analysisdefinition_types.go
metrics-operator/converter/sli_converter_test.go
metrics-operator/converter/slo_converter.go
metrics-operator/converter/slo_converter_test.go
metrics-operator/go.mod
metrics-operator/main.go

- introduced convertor for SLO files
- unit tests
- converter is part of metrics-operator binary under --convert-slo flag
`./metrics-operator --convert-slo=slo.yaml --slo-namespace=default --definition=defname`
-  There is need to cover the cases when multiple criteria have logical AND operator in between them, see TODOs in `setupTarget` function and [here](https://github.com/keptn/spec/blob/master/service_level_objective.md#comparison) for more information
Part-of: #1760

feat(metrics-operator): introduce SLO -> AnalysisDefinition converter

---

README.md

This PR
- Fixes the broken Go version badge on the readme

fix: fix Go badge

---

docs/content/en/docs/concepts/architecture/components/_index.md
docs/content/en/docs/concepts/architecture/deployment-flow.md
docs/content/en/docs/concepts/architecture/working/_index.md

This pulls together the basic information from the slack discussion.  
Closes #689 
Epic: #770 
Replaces https://github.com/keptn/lifecycle-toolkit/pull/1342 , which replaced https://github.com/keptn/lifecycle-toolkit/pull/828 , which is totally corrupted but contains a lot of interesting comments and history

docs: deployment flow architecture

---

docs/content/en/contribute/docs/source-file-structure/_index.md

This PR updates information about the structure of the doc source files, the metadata header required for each page, and how weights work.

docs: update the doc source file structure page

---

docs/CONTRIBUTING.md
docs/content/en/contribute/docs/contrib-guidelines-docs/_index.md
docs/content/en/contribute/docs/local-building/_index.md
docs/content/en/contribute/general/contrib-guidelines-gen/_index.md

This PR does the following:
* Moves most of the content from the "Contributing Guidelines" page that was in the Docs section to the General section, removing the one doc-specific guideline and including a link to the doc-specific guidelines
* Modifies the "Contributing Guidelines for documentation" page to only include documentation issues and adds additional guidelines
* Corrects errors (outdated info) in the "Build docs locally" page
Note that https://github.com/keptn/lifecycle-toolkit/pull/1936 modifies the PR template to include a checklist for many of these items.  That PR currently includes links to the CONTRIBUTING.md file.  After this PR is merged, need to modify the `.github/PULL_REQUEST_TEMPLATE/pr-template.md` file to instead link to the Contrib Guide.  See …

docs: contribution guidelines

---

docs/content/en/docs/implementing/tasks/_index.md

This implements the KLT -> Keptn name change for the implementing/tasks page that was merged after (https://github.com/keptn/lifecycle-toolkit/pull/2001) was reviewed

docs: implement KLT -> Keptn name change for tasks page

---

.github/workflows/release.yml

as a fix for https://github.com/keptn/lifecycle-toolkit/actions/runs/6085201088
This fixes scenarios where no artifacts need to be built but the release matrix still has `{config: []}` inside which means that the build steps start, but then the matrix has no content so we get an error.

ci: fix release matrix again again again again

---

docs/content/en/docs/getting-started/_index.md
docs/content/en/docs/intro/_index.md

Partially satisfies https://github.com/keptn/lifecycle-toolkit/issues/2005 
This PR improves the "Intro to KLT" page:
* Intro page appears before "Getting started" page
* Improve the flow by grouping descriptive information into the three use-cases, which should map to the future modules
* Removed the first sentence that says the section includes tutorials although those old tutorials are still listed here.
* Removed the "GitOps" term, which seemed to be making people who are not doing full GitOps feel that Keptn was not for them
* Add CloudEvents to list of signals Keptn emits
* Remove info about Keptn v1 and the history of Keptn as well as the links to the youtube videos
* Add a sentence that is ready to link to Stacey's blog, which discusses the history of the Keptn project, what Keptn …

docs: improve "Intro to Keptn" page

---

docs/content/en/docs/concepts/architecture/cert-manager.md

The Architecture page for cert-manager was pointing to the old location for information about replacing the Keptn cert-manager with cert-manager.io.  This fixes that.

docs: fix xref to cert-manager page

---

docs/content/en/docs/getting-started/_index.md
release-please-config.json

- removes the `rollout restart` commands since they are not needed
- fixes the klt tag version for the examples files
- fixes the service name in the prometheus helm values
- fixes release-please not updating the tag in the examples urls

docs: improve getting started guide

---

docs/content/en/docs/implementing/tasks-non-k8s-apps.md

This PR moves the "Keptn for non-Kubernetes applications" page from the "tutorials" section to the "implementing" section.
Originally, I did https://github.com/keptn/lifecycle-toolkit/pull/2086 to move and expand the information in this page.  The "expanding" is more complicated than I had anticpated so let's just move this file as is into the new location.  I will then do another PR that enhances the content.

docs: move tasks-non-k8s-apps to implementing from tutorials

---

dashboards/grafana/configmap/grafana-dashboard-keptn-applications.yaml
dashboards/grafana/configmap/grafana-dashboard-keptn-overview.yaml
dashboards/grafana/configmap/grafana-dashboard-keptn-workloads.yaml
examples/support/observability/config/prometheus/grafana-dashboard-keptn-applications.yaml
examples/support/observability/config/prometheus/grafana-dashboard-keptn-overview.yaml
examples/support/observability/config/prometheus/grafana-dashboard-keptn-workloads.yaml

Closes #2081 
Adding the `uid` properties to the datasources again resulted in the values to be retrieved and displayed correctly again

fix: add uid fields to Grafana dashboard datasources

---

metrics-operator/controllers/analysis/controller_test.go
metrics-operator/controllers/common/analysis/types/types.go
test/integration/analysis-controller/01-assert.yaml

feat(metrics-operator): remove omitempty tags to get complete representation of AnalysisResult

---

docs/content/en/docs/implementing/otel.md

This PR fixes: #1748 
Adding an instruction above the commands to clone the repo and `cd` into the current directory.

docs: add better instructions for OTel example

---

docs/content/en/contribute/docs/contrib-guidelines-docs/_index.md

Adds a note to `contribute/docs/contrib-guidelines-docs`  about using the `embed path` shortcode to pull a sample file into the documentation.
Note that the formatting here is not great.  I could not successfully escape the shortcode when it was in a code block or within tics.  If anyone knows the trick to do this right, please let me know.

docs: how to embed a file in docs

---

.github/scripts/.helm-tests/default/result.yaml
docs/content/en/docs/crd-ref/metrics/v1alpha3/_index.md
helm/chart/templates/analysis-crd.yaml
metrics-operator/api/v1alpha3/analysis_types.go
metrics-operator/api/v1alpha3/common.go
metrics-operator/api/v1alpha3/common_test.go
metrics-operator/config/crd/bases/metrics.keptn.sh_analyses.yaml
metrics-operator/controllers/analysis/controller.go
metrics-operator/controllers/analysis/controller_test.go
metrics-operator/controllers/analysis/worker_pool_test.go
test/integration/analysis-controller/01-assert.yaml
test/integration/analysis/00-assert.yaml

- introduce `.status.state` in `Analysis` CRD
- refactor analysis controller logic to make it testable
- add unit tests
- integration tests
Fixes: #2044

fix(metrics-operator): introduce `.status.state` in Analysis

---

.github/scripts/generate-crd-docs/crd-docs-generator-config.yaml
docs/content/en/docs/crd-ref/lifecycle/v1alpha1/_index.md
docs/content/en/docs/crd-ref/lifecycle/v1alpha2/_index.md
docs/content/en/docs/crd-ref/lifecycle/v1alpha3/_index.md

KeptnEvaluationProviders are now KeptnMetricsProviders they stay in the API just to avoid a breaking change, we should not mention them in the docs to avoid generating confusion for the users.

chore: hide unused KeptnEvaluationProvider from the crd docs

---

docs/content/en/docs/getting-started/_index.md
docs/content/en/docs/install/k8s.md

The new getting-started exercise references helm.io which is a bogus site that is sometimes causing markdownlint to complain.  I fixed that link to point to the installation instructions for Helm CLI, and also added that link to the installation page that lists software that should be installed to use Keptn.

docs: correct link to Helm CLI installation info

---

docs/content/en/docs/yaml-crd-ref/evaluationprovider.md

The `KeptnEvaluationProvider` CRD was deprecated a few releases ago and nobody should be running Keptn releases that use it so time to delete the content-free reference page.

docs: remove yaml-crd-ref/evaluationprovider.md

---

.github/PULL_REQUEST_TEMPLATE/pr-template.md

docs: update contribution guideline link in PR template

---

runtimes/python-runtime/Dockerfile

Fixes: #2164 
Security scan: https://github.com/keptn/lifecycle-toolkit/actions/runs/6337202206

deps: bump image version of python-runtime

---

Makefile
klt-cert-manager/Makefile
lifecycle-operator/Makefile
metrics-operator/Makefile
scheduler/Makefile

fixes: #1935
* add golangci-lint cmd in subfiles as well as in root makefile
* add test cmd for in subfiles as well as in root makefile

feat: add test and lint cmd to makefiles

---

docs/content/en/docs/implementing/evaluations.md

This copies the information about evaluations from the intro/usecase-orchestrate.md file that is a remnant of an old getting-started guide.  The goal is to eventually delete the intro/usercase-orchestrate.md file.
The following changes were made to the content:
* Replaced the examples from Andi's example with examples from the official PodtatoHead example
* Added some notes about implementing evaluations.  **Please verify that the items in the last bullet list are accurate!!!**
* A bit of word-smithing

docs: add content to implementing/evaluations

---

docs/content/en/docs/implementing/slo/_index.md

Just a bit of wordsmithing on @RealAnna 's excellent page:
* Renamed this to be just "Analysis" to match other titles under "User Guides"
* Modified weight to locate this after OpenTelemetry and before Tasks
* Expanded the intro a bit
* Slight restructuring to make it flow better
* Removing "there is/are" occurrances, replace future tense with present in most cases, enclosed all names of resources in tics, etc

docs: edit Analysis guide page

---

docs/content/en/docs/getting-started/_index.md
docs/content/en/docs/tutorials/tasks/_index.md

docs: fix image ref

---

docs/assets/scheduler-gates/gate-removed.yaml
docs/assets/scheduler-gates/gated.yaml
docs/assets/scheduler-gates/scheduler.yaml
docs/content/en/docs/architecture/_index.md
docs/content/en/docs/architecture/components/_index.md
docs/content/en/docs/architecture/components/lifecycle-operator/_index.md
docs/content/en/docs/architecture/components/metrics-operator/_index.md
docs/content/en/docs/architecture/components/scheduler/_index.md
docs/content/en/docs/architecture/keptn-apps/_index.md
docs/content/en/docs/architecture/working/_index.md
docs/content/en/docs/implementing/otel.md
docs/content/en/docs/migrate/strategy/_index.md
lifecycle-operator/chart/templates/deployment.yaml
lifecycle-operator/chart/templates/extension-apiserver-authentication-reader-rbac.yaml
lifecycle-operator/chart/templates/keptn-scheduler-rbac.yaml
lifecycle-operator/chart/templates/scheduler-config.yaml

closes #1460 
1. The scheduling feature needs to be enabled and the k8s minor version needs to be more than 26 for the gates to be enabled
2. docs are updated to explain both gates and scheduler

feat(lifecycle-operator): automatically decide for scheduler installation based on k8s version

---

docs/assets/scss/_variables_project.scss

Fixes #1525
Please check the page preview. The navbar now always has solid background color and doesn't change during scrolling.

docs: add solid background color override to navbar

---

docs/content/en/contribute/docs/word-list/_index.md

Closes https://github.com/keptn/lifecycle-toolkit/issues/812
This is the beginning of an "official" list of terminology and how to use it in Keptn docs.  I don't see us ever doing a big effort to come up with such a list but, by starting the list, we can add to it as issues arise.
This first iteration has two entries: Keptn and CRD/resources.  See if you agree with what I wrote here.  Also suggests other terms that should be included now.

docs: begin official word list for Keptn documentation

---

.github/actions/deploy-klt-on-cluster/action.yml
.github/scripts/.helm-tests/default/result.yaml
.github/scripts/.helm-tests/lifecycle-only/result.yaml
.github/scripts/.helm-tests/lifecycle-with-certs/result.yaml
.github/workflows/CI.yaml
.github/workflows/integration-test.yml
Makefile
README.md
lifecycle-operator/chart/README.md
lifecycle-operator/chart/doc.yaml
lifecycle-operator/chart/templates/lifecycle-mutating-webhook-configuration.yaml
lifecycle-operator/chart/values.yaml
test/allowed-namespaces/simple-deployment-allowed/00-assert.yaml
test/allowed-namespaces/simple-deployment-allowed/00-install.yaml
test/allowed-namespaces/simple-deployment-allowed/00-teststep.yaml
test/allowed-namespaces/simple-deployment-allowed/01-assert.yaml
test/allowed-namespaces/simple-deployment-not-allowed/00-assert.yaml
test/allowed-namespaces/simple-deployment-not-allowed/00-install.yaml
test/allowed-namespaces/simple-deployment-not-allowed/00-teststep.yaml
test/allowed-namespaces/simple-deployment-not-allowed/01-verify-tasks.yaml
test/allowed-namespaces/simple-deployment-not-allowed/01-verify.yaml
test/common-scripts/verify-number-of-resources.sh
test/integration/app-one-taskdefinition-not-found/01-teststep-verify-number-of-tasks.yaml
test/integration/simple-task/01-teststep.yaml

- adapt helm charts to allow mutating webhook only for certain namespaces
- adapt installation action to be able to test the feature
- introduce integration tests
- update docs
- document changes
Fixes: #2090

feat(lifecycle-operator): introduce option to enable lifecycle orchestration only for specific namespaces

---

docs/content/en/docs/migrate/metrics-observe/_index.md
docs/content/en/docs/migrate/strategy/_index.md
docs/content/en/docs/yaml-crd-ref/analysis.md
docs/content/en/docs/yaml-crd-ref/analysisdefinition.md
docs/content/en/docs/yaml-crd-ref/analysisvaluetemplate.md

This PR:
- Adds instructions for converting Keptn v1 quality gates to Keptn Analysis
- Creates stub files for the yaml-crd-ref pages for the resources used for the  Keptn Analysis feature.  This lets me implement xrefs to these pages.  The content of these pages is being developed in https://github.com/keptn/lifecycle-toolkit/pull/2219
- Rewrites to the beginning of the "Migrate Quality Gates" page to reflect that Analysis is available as well as Keptn Metrics and Evaluations
Closes https://github.com/keptn/lifecycle-toolkit/issues/2175

docs: how to migrate quality gates to Keptn Analysis feature

---

docs/content/en/docs/yaml-crd-ref/analysis.md
docs/content/en/docs/yaml-crd-ref/analysisdefinition.md
docs/content/en/docs/yaml-crd-ref/analysisvaluetemplate.md
docs/content/en/docs/yaml-crd-ref/crd-template.md

Replaces https://github.com/keptn/lifecycle-toolkit/pull/2219/
Draft of CRD reference pages for the analysis feature:
* Analysis
* AnalysisDefinition
* AnalysisValueTemplate
Also updates:
* crd-template.md, which is just the template to start a new page in this section

docs: ref pages for Analysis CRDs

---

docs/content/en/docs/implementing/tasks/_index.md
docs/content/en/docs/migrate/strategy/_index.md
docs/content/en/docs/yaml-crd-ref/taskdefinition.md

This PR:
* Clarifies that the httpRef and functionRef syntax can each have a max two functions/resources specified
* This meant deleting a lot of fanciful text about various ways you could combine `KeptnTaskDefinition` resources for different needs.
* Restructures the `KeptnTaskDefinition` reference page
* Combine the "Field descriptions" for `deno-runtime` and `python-runtime` since the content is almost identical
* Fix an xref to this page on the migrate/strategy page
* Replace the code snippets given in the "Field descriptions" with links to the code examples that are included on the page.  This makes the page more readable and means that all the examples can be embedded from source code so are easier to maintain.
Closes https://github.com/keptn/lifecycle-toolkit/issues/2144

docs: restructure KeptnTaskDefinition, clarify httpRef and functionRef

---

docs/content/en/docs/architecture/components/scheduler/_index.md
docs/content/en/docs/getting-started/_index.md
docs/content/en/docs/intro/_index.md
docs/content/en/docs/tutorials/tasks/_index.md

Relates to https://github.com/keptn/lifecycle-toolkit/issues/2216
* I am proposing that the "get started" links on the landing page take the user to the short blurbs about the use-cases that are in the "Introduction to Keptn" page.
* This PR then adds "To learn more" lists at the end of each section
* First link(s) go to whatever relevant getting started material we have
* Other links go to relevant user guide pages
* Also tweaked the titles of the getting started exercises to be specific to the use case
* Add a sentence or two about the specific use-case to the beginning of each of the new tutorials

docs: tweaks to intro material for Keptn landing page

---

docs/CONTRIBUTING.md
docs/content/en/contribute/docs/publish/_index.md
docs/content/en/docs/architecture/components/scheduler/_index.md

This moves the content from docs/CONTRIBUTING.md to the documentation section of the Contributing Guide.

docs: move publishing info to contribute guide

---

metrics-operator/config/crd/bases/metrics.keptn.sh_keptnmetricsproviders.yaml
scheduler/pkg/klcpermit/permit.go
scheduler/pkg/klcpermit/workflow_manager.go

chore(scheduler): improve logging

---

docs/content/en/docs/implementing/tasks-non-k8s-apps.md
docs/content/en/docs/yaml-crd-ref/task.md

This PR and https://github.com/keptn/lifecycle-toolkit/pull/2089 replace https://github.com/keptn/lifecycle-toolkit/pull/2086 .
This PR:
* Expands the content of the "Keptn for non-Kubernetes Applications" guide chapter a bit.
* Creates a reference page for `KeptnTask` in the yaml-crd-ref section.  Normally, `KeptnTask` is generated automatically but, in this case, the user must populate and maintain it manually so we need to document the YAML syntax.
* The reference page no longer has an example but instead links to the guide chapter.  We do not need to be maintaining two examples and, in this case, it makes more sense to have the `KeptnTask` example presented in the context of running a `KeptnTask` for a non-k8s deployment.
28 September review notes:
* The initial draft was based on …

docs: add KeptnTask ref page; enhance guide chapter for keptn-no-k8s

---

lifecycle-operator/controllers/options/keptnconfig_controller.go
lifecycle-operator/controllers/options/keptnconfig_controller_test.go
lifecycle-operator/main.go

This PR fixes the KeptnConfig reconciler by calling the method to set the cloud events endpoint. Some refactoring has been done in the controller as well, to be able to verify that the relevant methods of the config instance have been called

fix(lifecycle-operator): make sure the CloudEvents endpoint from the KeptnConfig is applied

---

docs/content/en/docs/yaml-crd-ref/analysis.md

This Pull Request fixes a Typo in the Analysis Documentation. 
Currently `AnalysisTemplateValue` is used but the respective CRD is called `AnalysisValueTemplate`

docs: fix typo in analysis.md

---

docs/content/en/docs/implementing/otel.md
docs/content/en/docs/install/k8s.md

This PR refines the (minimal) information about configuring Grafana and Jaeger for Keptn:
* install/k8s says that you must install and configure Grafana and Jaeger if you want. dashboard for metrics and tracing and links to the "Requirements" subsection of the OpenTelemetry page for more details
* The OpenTelemetry/Requirements section gives links to the vendor docs for Grafana and Jaeger and to the Keptn Grafana README file for info about configuring Grafana for Keptn

docs: refine info about configuring Grafana/Jaeger

---

.github/workflows/integration-test.yml
.github/workflows/load-test.yml
.github/workflows/performance-test.yml

This PR changes the integration tests to collect and upload logs only in case of failure. 
Inspecting the logs for successful runs is not common and these two steps could take as much as running the test itself

ci: run report creation and upload only in case of failure

---

docs/content/en/docs/implementing/tasks-non-k8s-apps.md
docs/content/en/docs/yaml-crd-ref/task.md

This PR cuts in comments that came in for https://github.com/keptn/lifecycle-toolkit/pull/2103 after it was closed.

docs: more comments for tasks-non-k8s-apps

---

.github/actions/deploy-klt-on-cluster/action.yml
.github/workflows/CI.yaml
.github/workflows/integration-test.yml

Part-of: #1602 
- drop manifests installation support in CI, integration tests and installation action
-  drop support os manifests in security checks

ci: drop manifests support in CI pipelines

---

lifecycle-operator/main.go
lifecycle-operator/webhooks/pod_mutator/handlers/appcreationrequest_handler.go
lifecycle-operator/webhooks/pod_mutator/handlers/appcreationrequest_handler_test.go
lifecycle-operator/webhooks/pod_mutator/handlers/workload.go
lifecycle-operator/webhooks/pod_mutator/handlers/workload_test.go
lifecycle-operator/webhooks/pod_mutator/pod_mutating_webhook.go
lifecycle-operator/webhooks/pod_mutator/pod_mutating_webhook_test.go

Part of #2290
This PR removes the spans created by the webhook, as they did not prove to be useful

chore(lifecycle-operator): remove spans created by webhook

---

.github/actions/deploy-klt-on-cluster/action.yml
.github/actions/deploy-klt-on-cluster/values.yaml
.github/scripts/.helm-tests/certificates-only/result.yaml
.github/scripts/.helm-tests/default/result.yaml
.github/scripts/.helm-tests/lifecycle-only/result.yaml
.github/scripts/.helm-tests/lifecycle-with-certs/result.yaml
.github/scripts/.helm-tests/lifecycle-with-certs/values.yaml
.github/scripts/.helm-tests/metrics-only/result.yaml
.github/scripts/.helm-tests/metrics-with-certs/result.yaml
.github/scripts/.helm-tests/metrics-with-certs/values.yaml
klt-cert-manager/chart/README.md
klt-cert-manager/chart/values.yaml
lifecycle-operator/chart/README.md
lifecycle-operator/chart/values.yaml
metrics-operator/chart/README.md
metrics-operator/chart/templates/deployment.yaml
metrics-operator/chart/values.yaml

fixes #2360
also adds missing image function and imagePullPolicy from the metrics operator templates
to check that it works I added tests in the helm test folder and used a value file for our install action

fix: helm charts image registry, image pull policy and install action

---

.github/workflows/security-scans.yml
.trivyignore

Security run: https://github.com/keptn/lifecycle-toolkit/actions/runs/6693358357

fix(scheduler): ignore OTel security issue in scheduler

---

docs/content/en/docs/yaml-crd-ref/app.md
docs/content/en/docs/yaml-crd-ref/config.md
docs/content/en/docs/yaml-crd-ref/evaluationdefinition.md

docs: add required labels to required CRD fields (KeptnApp, KeptnConfig, KeptnEvaluationDefinition)

---

docs/content/en/docs/yaml-crd-ref/metric.md
docs/content/en/docs/yaml-crd-ref/metricsprovider.md
docs/content/en/docs/yaml-crd-ref/task.md
docs/content/en/docs/yaml-crd-ref/taskdefinition.md

- adds required labels for required fields in the CRD reference pages for the following types:
- KeptnTask
- KeptnMetric
- KeptnMetricsProvider
- KeptnTaskDefintion
Part-of: https://github.com/keptn/lifecycle-toolkit/issues/2324

docs: add required labels to required CRD fields (KeptnTask, KeptnMetric, KeptnMetricsProvider, KeptnTaskDefintion)

---

docs/content/en/docs/implementing/slo/_index.md
docs/content/en/docs/install/k8s.md
docs/content/en/docs/yaml-crd-ref/analysis.md
docs/content/en/docs/yaml-crd-ref/analysisdefinition.md
docs/content/en/docs/yaml-crd-ref/analysisvaluetemplate.md

Closes https://github.com/keptn/lifecycle-toolkit/issues/2317 
This PR:
* Adds an item about analyses to the "How many namespaces" section
* Adds info about namespace location to the three yaml-crd-ref reference pages
* Refined the synopsis and fields definitions for the `AnalysisDefinition` reference page
* Link to the yaml-crd-ref pages rather than the API pages from the guide chapter
* Adds the `(required)` label as appropriate to the "Field" descriptions

docs: add required labels to required CRD fields (Analysis, AnalysisDefinition, AnalysisValueTemplate)

---

chart/Chart.lock
chart/Chart.yaml

With the changes made in this [commit](https://github.com/keptn/lifecycle-toolkit/commit/55e12d4a6c3b5cd0fbb2cd6b8b8d29f2b7c8c500#diff-5963488a989d82482fe71c85de7999c1c6c11088831ba7f541c8770fcfa597a1), any change of the fields in CRDs will cause failure of the test, like [here](https://github.com/keptn/lifecycle-toolkit/pull/2254).
Reverting these changes.
https://github.com/keptn/lifecycle-toolkit/pull/2397

chore: revert Chart.yaml to point to local repositories

---

.github/workflows/CI.yaml
.github/workflows/security-scans.yml

Fixes: #1602 
- remove storage/upload of manifests during CI
- remove manifests usage from security pipeline
Security scan run https://github.com/keptn/lifecycle-toolkit/actions/runs/6731161682

chore: remove manifests usage from security-scans

---

.github/workflows/CI.yaml
chart/Chart.yaml

Adapt chart sync pipeline to substitute local paths with official charts url

chore: adapt helm chart pipeline to substitue local paths before syncing with charts repository

---

lifecycle-operator/apis/lifecycle/v1alpha3/keptnapp_test.go
lifecycle-operator/apis/lifecycle/v1alpha3/keptnapp_types.go
lifecycle-operator/controllers/common/telemetry/spanhandler.go
lifecycle-operator/controllers/lifecycle/keptnapp/controller.go
lifecycle-operator/controllers/lifecycle/keptnapp/controller_test.go
lifecycle-operator/main.go
lifecycle-operator/test/component/app/app_suite_test.go
lifecycle-operator/test/component/app/app_test.go
lifecycle-operator/test/component/load/load_suite_test.go
lifecycle-operator/test/component/load/load_test.go

This PR fixes the span structure of a KeptnApp deployment by:
1. Ensuring the root span (i.e. the span with the name of the KeptnAppVersion) encompasses the complete deployment
2. Removing the duplicated root span that was terminated immediately after the KeptnApp controller has created a KeptnAppVersion

fix(lifecycle-operator): fix app deployment span structure

---

docs/content/en/docs/implementing/integrate.md
docs/content/en/docs/implementing/tasks-non-k8s-apps.md
docs/content/en/docs/install/install.md
docs/content/en/docs/install/troubleshooting.md

This PR removes instructions for installing Keptn from a manifest.
- [n/a ] My PR fulfills the Definition of Done of the corresponding issue and not more (or parts if the issue is separated
- [ n/a] I regenerated the auto-generated docs for Helm and the CRD documentation (if applicable)

docs: remove manifest install instructions

---

.github/workflows/CI.yaml

Fixes the problem with helm chart sync in main branch
https://github.com/keptn/lifecycle-toolkit/actions/runs/6742064027/job/18327624214

chore: fix yq command for helm chart sync

---

.github/actions/deploy-klt-on-cluster/action.yml
.github/actions/deploy-klt-on-cluster/values.yaml
.github/workflows/security-scans.yml

closes #2182 
Security run: https://github.com/keptn/lifecycle-toolkit/actions/runs/6745011001

chore: use templated values in install action and security workflow

---

lifecycle-operator/webhooks/pod_mutator/handlers/appcreationrequest_handler.go
test/integration/simple-deployment-k8s-recommended-label/00-assert.yaml
test/integration/simple-deployment-k8s-recommended-label/00-install.yaml
test/integration/simple-deployment-k8s-recommended-label/00-teststep.yaml
test/integration/simple-deployment-k8s-recommended-label/01-assert.yaml

When no app name is set explicitly in the labels/annotations of a pod, the mutating webhook was using the name of the workload for the name of the related, autogenerated app. Afterwards it adds the name of the app as an annotation to the pod, however it did that without considering the `app.kubernetes.io/name` label, but only based on what is in `keptn.sh/workload`. This prevented pods not using the `keptn.sh/workload` label from spinning up as the scheduler, which is using these annotations as information for constructing the name of the related workload version, could not find a matching WorkloadVersion.

fix(lifecycle-operator): adopt KeptnApp name from either Keptn or k8s label

---

docs/content/en/contribute/docs/source-file-structure/_index.md

Update the list of directories/titles in the primary Keptn doc section.
Note that this just reflects what the current structure is.  Discussions about what the structure should be are outside the scope of this PR.
Fixes https://github.com/keptn/lifecycle-toolkit/issues/2431 
- [x/a] My PR fulfills the Definition of Done of the corresponding issue and not more (or parts if the issue is separated
- [n/a] I regenerated the auto-generated docs for Helm and the CRD documentation (if applicable)

docs: update list of primary doc folders/titles

---

docs/content/en/docs/implementing/slo.md
docs/content/en/docs/yaml-crd-ref/analysis.md
docs/content/en/docs/yaml-crd-ref/analysisdefinition.md
docs/content/en/docs/yaml-crd-ref/analysisvaluetemplate.md

* Updates note that the Analysis feature is also preliminary on Analysis ref page to include 0.9.0
* Expand information on the Analysis ref page about activating a preview of this feature
* Make the AnalysisDefinition and AnalysisValueTemplate ref pages link to the Analysis ref page for implementation details rather than duplicating the information on each page
Note that the info about activating this feature that is on the "Install" page will also be modified to point to the Analysis ref page but I'll do that in https://github.com/keptn/lifecycle-toolkit/pull/2419 which currently has that page open.
- [n/a] My PR fulfills the Definition of Done of the corresponding issue and not more (or parts if the issue is separated
see [Contribution …

docs: analysis feature in 0.9.0

---

docs/content/en/docs/architecture/components/scheduler.md

This PR aligns terminology with what is in the install section and improves the readability of the prose.

docs: clarify scheduler architecture info

---

renovate.json

- removes occurrences of `testreg` from renovate since this name is only used to test helm values in the helm test setup

chore: remove test images from renovate config

---

lifecycle-operator/controllers/lifecycle/keptnappversion/controller.go
lifecycle-operator/controllers/lifecycle/keptnappversion/controller_test.go
lifecycle-operator/main.go
lifecycle-operator/test/component/appversion/appversion_suite_test.go

chore(lifecycle-operator): adapt KeptnAppVersionReconciler to make use of PhaseHandler interface

---

lifecycle-operator/apis/lifecycle/v1alpha3/common/common.go
lifecycle-operator/webhooks/pod_mutator/handlers/objectmeta.go
lifecycle-operator/webhooks/pod_mutator/handlers/objectmeta_test.go
lifecycle-operator/webhooks/pod_mutator/handlers/pod_annotation.go
lifecycle-operator/webhooks/pod_mutator/handlers/pod_annotation_test.go
scheduler/pkg/klcpermit/workflow_manager.go
scheduler/pkg/klcpermit/workflow_manager_test.go

If a pod contains multiple containers the user can select which container the version should be extracted from by setting the keptn.sh/container annotation. If the annotation is set, but no container matches its name we assume something is wrong an throw an error.
Part-of #2464 
The tests `Test_calculateVersion` were expanded to cover the added functionality

feat: add annotation to select container for version extraction

---

docs/content/en/contribute/docs/contrib-guidelines-docs/_index.md
docs/content/en/contribute/docs/linter-requirements/_index.md
docs/content/en/contribute/docs/local-building/_index.md

This PR fixes the weights for files in contribute/docs section
- [n/a] My PR fulfills the Definition of Done of the corresponding issue and not more (or parts if the issue is separated
- [n/a] I regenerated the auto-generated docs for Helm and the CRD documentation (if applicable)

docs: fix weights for contrib/docs files

---

docs/Makefile
renovate.json

- This PR pins the markdownlint version to 0.10.0. Before, `next` was used, which is not a fixed tag. That caused unforseen error from now and then. Also now, this is the issue behind some markdownlint errors on files that nobody touched.
- This PR also updates the renovate config to be able to capture more deps updates in makefiles.

chore: update renovate file to allow more makefile regex patterns, pin markdownlint version

---

lifecycle-operator/webhooks/pod_mutator/handlers/objectmeta.go
test/integration/simple-deployment-container-annotation/00-assert.yaml
test/integration/simple-deployment-container-annotation/00-install.yaml
test/integration/simple-deployment-container-annotation/00-teststep.yaml
test/integration/simple-deployment-container-annotation/01-assert.yaml
test/integration/simple-deployment-container-annotation/01-install.yaml

Fixes #2464 
Depends on https://github.com/keptn/lifecycle-toolkit/pull/2471

test: introduce e2e test for keptn.sh/container annotation

---

docs/content/en/docs/implementing/dora.md
docs/content/en/docs/implementing/otel.md

This PR:
* Deletes the "DORA Metrics" section from the "Observability" page since it duplicated what is in the separate "DORA metrics" page
* Minor modifications to the "Observability" page to update and correct it 
Fixes https://github.com/keptn/lifecycle-toolkit/issues/2465 
- [n/a ] I regenerated the auto-generated docs for Helm and the CRD documentation (if applicable)

docs: remove duplicated DORA section from otel.md

---

lifecycle-operator/controllers/lifecycle/keptntask/container_builder.go
lifecycle-operator/controllers/lifecycle/keptntask/container_builder_test.go
lifecycle-operator/controllers/lifecycle/keptntask/job_runner_builder.go
lifecycle-operator/controllers/lifecycle/keptntask/runtime_builder.go
test/integration/container-runtime/00-assert.yaml

Closes [#2483](https://github.com/keptn/lifecycle-toolkit/issues/2483)
Note: Renaming the environment variable for the other runtimes will be done in https://github.com/keptn/lifecycle-toolkit/issues/2491

feat(lifecycle-operator): add `KEPTN_CONTEXT` to task container env vars

---

.github/scripts/.helm-tests/default/result.yaml
.github/scripts/.helm-tests/lifecycle-only/result.yaml
.github/scripts/.helm-tests/lifecycle-only/values.yaml
.github/scripts/.helm-tests/lifecycle-with-certs/result.yaml
lifecycle-operator/chart/README.md
lifecycle-operator/chart/templates/lifecycle-mutating-webhook-configuration.yaml
lifecycle-operator/chart/values.yaml

Adds the option an option to the `lifecycle-operator` chart to exclude namespaces  in the `MutatingWebhookConfiguration`. This is useful to prevent possible deadlocks with other mutating webhooks running in other namespace, which might also prevent pods from being started.
This change should not result in any unexpected changes for users when upgrading. It preserves the default values for the excluded namespaces and does not change the logic of `allowedNamespaces`. In my opinion it also adds the benefit to be more explicit about the namespaces ("cert-manager" etc.)  which are excluded by default right now.
Fixes #2512
The change is rather trivial as it mimics the already implemented features. I only tested it manually by rendering the Helm Chart:
```
echo 'deniedNamespaces: ["foo"]' > …
```

feat(lifecycle-operator): add option to exclude additional namespaces

---

docs/config/production/params.yaml

This PR exchanges the previous google custom search engine for a new one that is owned by the keptnproject google account.
Fixes #2337

chore: use new search engine ID

---

.github/actions/spelling/expect.txt
.readthedocs.yaml

This PR adds the config file for readthedocs integration. I also create the project on readthedocs.com
@thisthat will be invited as soon as he signs up there.
Fixes #2552

chore: add config file for ReadTheDocs

---

examples/support/observability/config/otel-collector.yaml

This pr fixes the broken opentelemetry collector, 
the bug was introduced by this renovate pr #2109
v0.85.0 removed jeager as exporter https://github.com/open-telemetry/opentelemetry-collector-releases/releases/tag/v0.85.0
for more info see here https://stackoverflow.com/questions/77475771/error-when-running-otel-collector-with-jaeger-in-docker-containers

fix: changed jaeger to otlp

---

.github/actions/spelling/expect.txt
docs-new/overrides/partials/header.html

This PR adds the customized header override html file. The file contains exactly the same content as the [original header](https://github.com/squidfunk/mkdocs-material/blob/master/src/templates/partials/header.html) but adds the `div` to inject the ReadTheDocs version selection menu.
Part of #2550

docs: add MkDocs header override to enable version dropdown menu

---

.markdownlint-cli2.yaml
dashboards/grafana/README.md

This pull request adds links to the official Grafana documentation for creating and modifying dashboards in the README.md file.
Changes made:
- Added links to the relevant sections of the Grafana documentation.
- Ensured the links are accurate and functional.
Fixes #2538

docs: add links to official Grafana documentation for creating and modifying dashboards 

---

.github/scripts/.helm-tests/default/result.yaml
.github/scripts/.helm-tests/lifecycle-only/result.yaml
.github/scripts/.helm-tests/lifecycle-with-certs/result.yaml
.github/scripts/.helm-tests/metrics-only-with-apiservice-disabled/result.yaml
.github/scripts/.helm-tests/metrics-only/result.yaml
.github/scripts/.helm-tests/metrics-with-certs/result.yaml
lifecycle-operator/chart/templates/deployment.yaml
lifecycle-operator/config/manager/manager.yaml
metrics-operator/chart/templates/deployment.yaml
metrics-operator/config/manager/manager.yaml

Some volumes in lifecycle-operator and metrics-operator  Deployments are not used, we can remove them

chore: clean up unused volumes

---

Makefile
docs-new/docs/components/index.md
docs-new/docs/getting-started/index.md
docs-new/docs/guides/index.md
docs-new/docs/index.md
docs-new/docs/installation/configuration/index.md
docs-new/docs/reference/api-reference/lifecycle/index.md
docs-new/docs/reference/api-reference/metrics/index.md
docs-new/docs/reference/api-reference/options/index.md
docs-new/docs/reference/index.md
docs-new/docs/use-cases/index.md

This PR adds basic content to all section index pages so that users are not presented with empty pages.
Fixes #2586

docs: add content to all section index pages

---

docs/config/_default/config.yaml

- ports the url change from #2676 into the live page

docs: fix the navigation to Keptn v1 Docs

---

.github/actions/spelling/expect.txt
docs-new/docs/guides/slo.md
docs-new/docs/reference/crd-reference/analysisdefinition.md
docs/content/en/docs/guides/slo.md
docs/content/en/docs/reference/crd-reference/analysisdefinition.md

Explains the use of Kubernetes `quantity` type rather than `float` for values specified for values in the `target` specification.
Fixes https://github.com/keptn/lifecycle-toolkit/issues/2610
- [ n/a] I regenerated the auto-generated docs for Helm and the CRD documentation (if applicable)

docs: explain quantity data type for analysis targets

---

docs-new/docs/components/scheduling.md
docs-new/docs/guides/evaluations.md
docs-new/docs/installation/index.md
docs-new/docs/installation/tips-tricks.md
docs-new/docs/reference/crd-reference/analysis.md
docs-new/docs/reference/crd-reference/analysisvaluetemplate.md
docs-new/docs/reference/crd-reference/taskdefinition.md
docs-new/docs/use-cases/day-2-operations.md
docs-new/docs/use-cases/hpa.md

This PR puts backticks around embedded yaml files to format them properly on the rendered page

docs: surround embedded yaml files with backticks

---

.github/workflows/CI.yaml

- adds an ignore path for the spell checker files to the CI pipeline to reduce docs PR build time

ci: ignore spell-checker adaptations in CI workflow

---

examples/support/observability/config/prometheus/grafana-config.yaml
examples/support/observability/config/prometheus/grafana-dashboard-keptn-applications.yaml
examples/support/observability/config/prometheus/grafana-dashboard-keptn-overview.yaml
examples/support/observability/config/prometheus/grafana-dashboard-keptn-workloads.yaml
examples/support/observability/config/prometheus/grafana-deployment.yaml

closes #1816
this pr sets up DORA dashboard as default in the observability example and renames it to help the user understand the data

chore: setup workload dashboard as default in observability example

---

docs-new/CONTRIBUTING.md

Link to Contributing Guide from docs-new/CONTRIBUTING.md
Fixes https://github.com/keptn/lifecycle-toolkit/issues/2757

docs: link to contrib guide from docs-new/CONTRIBUTING.md

---

scheduler/manifests/install/base/deployment.yaml
scheduler/manifests/install/base/rbac.yaml
scheduler/manifests/install/base/serviceaccount.yaml
scheduler/manifests/install/kustomization.yaml

This PR adapts the namespace of the scheduler to `keptn-system`, as the previously used `keptn-lifecycle-toolkit-system` namespace is not used anywhere else anymore

chore(scheduler): adapt namespace name

---

docs-new/blog/posts/analyzing-application-performance/memory-usage.yaml

The example query was including the `metricSelector=` prefix, which is added by the dynatrace provider later on as well

docs: fix AnalysisValueTemplate query in blog post

---

.github/actions/deploy-keptn-on-cluster/action.yml
.github/workflows/CI.yaml
.github/workflows/e2e-test.yml
.github/workflows/integration-test.yml
.github/workflows/load-test.yml
.github/workflows/performance-test.yml
.github/workflows/security-scans.yml

fix [this](https://github.com/keptn/lifecycle-toolkit/actions/runs/7448634934/job/20263546678?pr=2392#step:3:131) annoying integration test failures due to artifacts download

chore: downgrade download artifact action

---

docs-new/docs/migrate/strategy.md
docs-new/docs/use-cases/non-k8s.md

This captures information @bacherfl provided in a Slack discussion about using Keptn with deployments that do not run on Kubernetes.
* Change title of this page to be more appropriate and descriptive
* Remove metadata from the file
* Add information about running analyses on a non-k8s deployment
* Required some restructuring of the file
Fixes # https://github.com/keptn/lifecycle-toolkit/issues/2760 
- [ x] My PR title is formatted according to the semantic PR conventions described in

docs: analysis for non-k8s deployments

---

.github/actions/spelling/expect.txt
metrics-operator/controllers/common/providers/dynatrace/client/client_test.go
metrics-operator/controllers/common/providers/dynatrace/client/common.go
metrics-operator/controllers/common/providers/dynatrace/client/common_test.go
metrics-operator/controllers/common/providers/dynatrace/client/config.go
metrics-operator/controllers/common/providers/dynatrace/client/config_test.go
metrics-operator/controllers/common/providers/dynatrace/common.go
metrics-operator/controllers/common/providers/dynatrace/common_test.go
metrics-operator/controllers/common/providers/dynatrace/dynatrace.go
metrics-operator/controllers/common/providers/dynatrace/dynatrace_dql.go
metrics-operator/controllers/common/providers/dynatrace/dynatrace_dql_test.go
metrics-operator/controllers/common/providers/dynatrace/dynatrace_test.go

* made AuthUrl in metrics-operator configurable
* removed `DefaultAuthUrl`
* added tests
Fixes #1968

chore(metrics-operator): make Dynatrace DQL provider oAuth URL configurable

---

mkdocs.yml

This makes the title for use-cases/keptn-non-k8s match the title in the main frame.

docs: fix left frame title for keptn-no-k8s

---

docs-new/docs/contribute/software/dev-environ.md

* Captures info about running Kuttle test from slack discussion 15 Jan 2024
* Modified the "Testing" section to have a sub-section for each test rather than a numbered list for all tests.  This makes the types of tests pop a bit more in the page and in the contents in the right frame and is more accurate because people don't need to run all these tests on all PRs.

docs: add info on how to run kuttl tests

---

docs-new/Makefile
docs/Makefile

- fixes the markdown lint fix command after the version bump to 0.12 since the old command was deprecated

ci: fix markdown lint fix command after version bump

---

.github/actions/spelling/expect.txt
docs-new/docs/contribute/general/contrib-guidelines-gen.md
docs-new/docs/contribute/general/refinement-guide.md
mkdocs.yml

This pull request addresses the issue #2675, where the goal is to document the refinement process in the contribute guide.
Fixes #2675
- Added a new page named `refinement-guide.md` in the contribute/general section.
- Updated the `contribut-guidelines-gen.md` file to include guidance on creating and refining tickets for proposed work.
- Provided detailed for contributors and members on how to participate in refinement meetings and improve their contributions iteratively.

docs: add documentation for the refinement process in the contribute guide

---

.sonarcloud.properties

- adds all API folders for all operators to the ignore sections for duplication detection for SonarCloud
- This should fix the failing sonarcloud checks

chore: fix sonarcloud duplication detections in API folders

---

release-please-config.json

This PR tries to fix some of the release issues currently occurring.
It removes some of the root-level folder from being picked up by release-please. This should ensure that when e.g. an integration test is changed or added as part of an operator feature, that won't show up in the keptn-overall changelog. Same with spelling issues and examples.
Part of #2812

ci: remove some folders from release-please monorepo setup

---

.markdownlint-cli2.yaml

- adds back the docs folder for markdown lint

chore: enable markdownlint for new/old docs folder

---

mkdocs.yml

Since google analytics apparently doesn't work from the readthedocs integration, this adds GA through mkdocs material which I verified to work.

chore: add google analytics tag to docs page

---

.github/workflows/release.yml

Fixes #2872 
Just a small change to the `release` action to enhance supply chain security best practices by [attesting](https://docs.sigstore.dev/verifying/attestation/) the container images with cosign.
No additional dependencies required to test.
Please also refer to the associated issue for more details.
Simply trigger the release action.

ci: add sbom attestation step to release action

---

examples/support/observability/config/otel-collector.yaml

This PR adapts the port number for the otlp exporter to use the Jaeger service that supports the otlp proto service used by the OTel exporter. With the old port the trace export was not working due to the used grpc service not being implemented in the Jaeger counterpart.

fix(examples): adapt jaeger service port number for OTel exporter

---

.github/workflows/htmltest.yaml
docs/Makefile

- enables debug level logs for HTMLTest
- removes caching of hugo packages since hugo is not used anymore
Fixes #2919

chore: enable HTMLTest debug logging

---

.github/scripts/generate-crd-docs/templates/type_members.tpl
docs/docs/reference/api-reference/lifecycle/v1alpha1/index.md
docs/docs/reference/api-reference/lifecycle/v1alpha2/index.md
docs/docs/reference/api-reference/lifecycle/v1alpha3/index.md
docs/docs/reference/api-reference/lifecycle/v1alpha4/index.md
docs/docs/reference/api-reference/lifecycle/v1beta1/index.md
docs/docs/reference/api-reference/metrics/v1alpha1/index.md
docs/docs/reference/api-reference/metrics/v1alpha2/index.md
docs/docs/reference/api-reference/metrics/v1alpha3/index.md
docs/docs/reference/api-reference/metrics/v1beta1/index.md
docs/docs/reference/api-reference/options/v1alpha1/index.md

context spec metadata in crd ref now has the correct reference info, metadata for k8s now links to https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/#attaching-metadata-to-objects

chore: fix auto-generated API docs having wrong metadata info

---

docs/docs/guides/slo.md
docs/docs/reference/crd-reference/analysisdefinition.md

- replaces some remaining `embed` shortcodes from Hugo with `include` shortcodes from MkDocs
Fixes #2916

docs: replace remaining embeds with includes

---

lifecycle-operator/controllers/lifecycle/keptnworkload/controller.go
lifecycle-operator/controllers/lifecycle/keptnworkload/controller_test.go

fix(lifecycle-operator): make sure spec of KeptnWorkloadVersion is consistent with KeptnWorkload

---

docs/docs/reference/crd-reference/task.md

This PR:
* Fixes a couple lines in synopsis that were examples rather than description
* Augmented description under field to show the example
* Add links to API ref for `KeptnAppVersion` and `KeptnWorkloadVersion

docs: fix Synopsis for KeptnTask CRD reference page

---

.github/actions/spelling/expect.txt
.github/workflows/htmltest.yaml

- removes the `docs/tmp/.htmltest` path from the github cache since it's not needed anymore because of the recent docs tooling changes
- changes the cache key so that it includes a hash of the `refcache.json` file which stores external URLs checks from HTMLTest. This should fix recent HTTP 429 issues when new external links were added to the docs

ci: fix HTMLTest HTTP 429 issues

---

docs/docs/reference/crd-reference/evaluationdefinition.md
docs/docs/reference/crd-reference/metric.md
docs/docs/reference/crd-reference/metricsprovider.md

This PR:
* Fixes formatting issues for "Fields" sections on the `KeptnMetricsProvider`, `KeptnMetric`, and `KeptnEvaluationDefinition` ref pages
* Also add mention of `AnalysisValueTemplate` to `KeptnMetricsProvider` descriptive text and "See also"

docs: fix formatting in CRD reference pages

---

docs/docs/assets/crd/eval.yaml
docs/docs/assets/crd/python-configmap.yaml
docs/docs/assets/crd/python-context.yaml
docs/docs/assets/crd/python-inline.yaml
docs/docs/assets/crd/python-libs.yaml
docs/docs/assets/crd/python-recursive.yaml
docs/docs/assets/crd/task-definition.yaml
docs/docs/components/lifecycle-operator/keptn-apps.md
docs/docs/guides/assets/tasks/dummy-task.yaml
docs/docs/guides/assets/tasks/multi-secret.yaml
docs/docs/guides/assets/tasks/slack.yaml
docs/docs/guides/assets/tasks/taskdef-secure-data.yaml
docs/docs/guides/evaluations.md
docs/docs/guides/integrate.md
docs/docs/guides/tasks.md
docs/docs/reference/crd-reference/app.md
docs/docs/reference/crd-reference/config.md
docs/docs/reference/crd-reference/evaluationdefinition.md
docs/docs/reference/crd-reference/task.md
docs/docs/reference/crd-reference/taskdefinition.md
docs/docs/use-cases/non-k8s.md

Synce our lifecycle  api  is at v1beta1 all links in the docs should refer to that api

chore: changed all ref to v1beta1 in docs links

---

docs/docs/migrate/keptnapp/index.md
lifecycle-operator/Makefile
lifecycle-operator/converter/convert_app.go
lifecycle-operator/converter/convert_app_test.go
lifecycle-operator/converter/example_keptnapp.yaml
lifecycle-operator/converter/example_output.yaml

added basic conversion code to generate app context from an old keptn app
https://github.com/keptn/lifecycle-toolkit/tree/main/lifecycle-operator/converter  is added in this pr so the 
link checks fail

chore: add KeptnApp migration script

---

docs/docs/reference/crd-reference/metric.md

This PR provides some basic information about the multiple metrics feature to the KeptnMetric CRD ref page.
The software was implemented in https://github.com/keptn/lifecycle-toolkit/pull/2190 .

docs: add multiple metrics field descriptions to KeptnMetric CRD ref

---

.github/actions/spelling/expect.txt
.github/workflows/release.yml

- move the log for `cosign verify-attestation` to an output file since several megabytes of text will come in that block/hang the pipeline
- the log file is uploaded as an artifact to the release pipeline

ci: log cosign attest verification to file to release pipeline remove hangs

---

.github/workflows/security-scans.yml

security run: https://github.com/keptn/lifecycle-toolkit/actions/runs/7815724809

ci: fix untar OCI images before running trivy scans 

---

docs/docs/reference/crd-reference/taskdefinition.md

This PR fixes the formatting of the "Fields for pre-defined containers" section of the KeptnTaskDefinition crd-ref page

docs: fix formatting for KeptnTaskDefinition fields

---

CONTRIBUTING.md
docs/CONTRIBUTING.md
docs/blog/posts/2023-keptn-year-in-review.md
docs/docs/use-cases/non-k8s.md

Fixes #3015 
Changed all links in the repo to keptn.sh/stable instead of keptn.sh/latest.

docs: move all keptn.sh links to /stable

---

test/chainsaw/testanalysis/analysis-controller-existing-status/mock-server.yaml
test/chainsaw/testanalysis/analysis-controller-multiple-providers/mock-server.yaml
test/chainsaw/testanalysis/analysis-controller-with-duration-timeframe/mock-server.yaml
test/chainsaw/testanalysis/analysis-controller/mock-server.yaml
test/chainsaw/testmetrics/metrics-hpa/mock-server.yaml

chore: introduce resource limts to mockserver integration tests

---

docs/docs/contribute/general/contrib-guidelines-gen.md

- fixes the referenced slack channel in the contribution guide

docs: fix referenced slack channel

---

.github/scripts/.helm-tests/default/result.yaml
.github/scripts/.helm-tests/lifecycle-only/result.yaml
.github/scripts/.helm-tests/lifecycle-only/values.yaml
.github/scripts/.helm-tests/lifecycle-with-certs/result.yaml
lifecycle-operator/chart/README.md
lifecycle-operator/chart/templates/deployment.yaml
lifecycle-operator/chart/values.yaml
lifecycle-operator/config/manager/manager.yaml
lifecycle-operator/main.go

feat(lifecycle-operator): add feature flag for enabling promotion tasks

---

.github/workflows/release.yml

+  During the release of Keptn v0.10.0, it was observed that the container build arguments in the release pipeline were not set properly.
* The affected variables include:
`GIT_HASH`
`RELEASE_VERSION`
`BUILD_TIME`
- These variables should be configured in the release pipeline in a manner consistent with how they are set in the CI pipeline.
Changes Made:
- Added environment variables (GIT_SHA, DATETIME, BUILD_TIME) to ensure accurate setting of container build arguments during the release pipeline.
*  Modified workflow to pass these variables to the subsequent job for Docker image creation.
Reason for Changes:
+ The original code lacked proper configuration of container build arguments during the release process, leading to inconsistencies.
* These changes aim to address the issue reported …

ci: fix container build arguments in release pipeline

---

.github/actions/spelling/expect.txt
.markdownlint-cli2.yaml
docs/docs/assets/crd/deno-context.yaml
docs/docs/assets/crd/examples/configmap-for-deno-script.yaml
docs/docs/assets/crd/examples/configmapref-for-deno-script.yaml
docs/docs/guides/tasks.md
docs/docs/reference/crd-reference/taskdefinition.md
lifecycle-operator/config/samples/function_execution/taskdefinition_function.yaml
lifecycle-operator/config/samples/function_execution/taskdefinition_function_configmap.yaml
lifecycle-operator/config/samples/function_execution/taskdefinition_function_inline.yaml
lifecycle-operator/config/samples/function_execution/taskdefinition_function_inline_slack.yaml
lifecycle-operator/config/samples/function_execution/taskdefinition_function_upstream.yaml
lifecycle-operator/config/samples/function_execution/taskdefinition_function_upstream_scheduler.yaml
lifecycle-operator/config/samples/function_execution/taskdefinition_function_upstream_slack.yaml
mkdocs.yml
test/chainsaw/allowed-namespaces/simple-deployment-not-allowed/chainsaw-test.yaml

This pr cleans up our KeptnTaskDefinition examples
Fixes #3083 

docs: review keptntaskdefinition examples

---

.github/scripts/.helm-tests/default/result.yaml
.github/scripts/.helm-tests/lifecycle-only/result.yaml
.github/scripts/.helm-tests/lifecycle-with-certs/result.yaml
docs/docs/reference/api-reference/lifecycle/v1beta1/index.md
lifecycle-operator/apis/lifecycle/v1beta1/keptnevaluation_types.go
lifecycle-operator/chart/templates/keptnevaluation-crd.yaml
lifecycle-operator/config/crd/bases/lifecycle.keptn.sh_keptnevaluations.yaml

chore(lifecycle-operator): remove unused FailAction parameter from KeptnEvaluation

---

.github/actions/spelling/expect.txt
runtimes/python-runtime/Dockerfile

This PR pins the version of libexpat to `2.6.0-r0` to resolve [CVE-2023-52425](https://nvd.nist.gov/vuln/detail/CVE-2023-52425).
Fixes #3120

chore(python-runtime): pin libexpat version to fix CVE-2023-52425

---

.github/workflows/CI.yaml
.github/workflows/component-test.yml

Since codecov-action [v4](https://github.com/codecov/codecov-action/releases/tag/v4.0.0), codecov only allows coverage upload WITHOUT token for PRs with forks as sources. Every other scenario now needs a token, which we didn't use until now.
This is added in this PR to get proper coverage reports again.

ci: use codecov token to upload coverage reports

---

docs/docs/components/lifecycle-operator/keptn-apps.md
docs/docs/installation/upgrade.md

Keptn does not track single pods lifecycle but only Workloads (Deployments, Daemonsets,StatefulSets...)
Some places in the docs where not superclear about this so edited them. 
Fixed some typos as well.

docs: remove wrong documentation on lifecycle of single Pods

---

test/chainsaw/integration/expose-keptn-metric/chainsaw-test.yaml
test/chainsaw/integration/expose-keptn-metric/job-existing-metric.yaml
test/chainsaw/integration/expose-keptn-metric/job-no-metric.yaml

Use chainsaw wait operation.
NOTE: this potentially fixes a bug, timeout was not honoured.

chore: use chainsaw wait operation

---

lifecycle-operator/controllers/common/config/config.go
lifecycle-operator/controllers/common/config/config_test.go
lifecycle-operator/controllers/common/config/fake/config_mock.go
lifecycle-operator/controllers/options/keptnconfig_controller.go
lifecycle-operator/controllers/options/keptnconfig_controller_test.go

part-of: #3134
Depends on: https://github.com/keptn/lifecycle-toolkit/pull/3149

feat(lifecycle-operator): adapt KeptnConfig reconciler to set up observabilityTimeout parameter

---

docs/docs/reference/crd-reference/analysis.md

Fix wrong indentation of status field

docs: fix wrong indentation of analysis status field in CRD reference

---

docs/docs/reference/crd-reference/task.md

Adds "Example" subsection to `KeptnTask` CRD reference.  This just includes an existing sentence that references the guide chapter but it means that users can use the ref page to quickly locate an example.
Also added link to that guide chapter in the "See also" section.
Fixes # https://github.com/keptn/lifecycle-toolkit/issues/3178

docs: add Example section to KeptnTask CRD ref

---

.github/actions/spelling/expect.txt
docs/docs/contribute/docs/code-docs.md
docs/docs/contribute/docs/source-file-structure.md
mkdocs.yml

This PR documents some quirks for coding the docs to work with our tools.  See the related issue for details.
Fixes https://github.com/keptn/lifecycle-toolkit/issues/2822
- [n/a] I regenerated the auto-generated docs for Helm and the CRD documentation (if applicable)

docs: document formatting quirks of MkDocs and markdownlint

---

docs/docs/getting-started/metrics.md

There is redundancy with the repetition of the word "metrics" in the last sentence of the third paragraph of the Keptn Metrics section in the file [lifecycle-toolkit/docs/docs/getting-started/metrics.md](https://github.com/keptn/lifecycle-toolkit/blob/main/docs/docs/getting-started/metrics.md#keptn-metrics)

docs: corrected grammatical error in Keptn Metrics

---

.github/workflows/CI.yaml
.github/workflows/component-test.yml
.github/workflows/e2e-test.yml
.github/workflows/github-repo-stats.yml
.github/workflows/golangci-lint.yml
.github/workflows/htmltest.yaml
.github/workflows/integration-test.yml
.github/workflows/load-test.yml
.github/workflows/markdown-checks.yaml
.github/workflows/release-examples.yml
.github/workflows/release.yml
.github/workflows/security-scans.yml
.github/workflows/set-date.yml
.github/workflows/spell-checker.yml
.github/workflows/stale.yml
.github/workflows/update-labels.yml
.github/workflows/validate-helm-chart.yml
.github/workflows/validate-semantic-pr.yml
.github/workflows/yaml-checks.yaml
docs/docs/index.md

- sets all workflows to readonly by default
- pins all github actions deps to a commit hash

chore: pin GHA deps, set default readonly in GHA

---

dashboards/grafana/configmap/grafana-dashboard-keptn-applications.yaml
dashboards/grafana/import/grafana_dashboard_applications.json
examples/Makefile

Updates grafana boards.
go to the example folder run
`make install`
after that is completed do
`make deploy-version-1`
after that is done 
`make port-forward-grafana`
and check the app dashboard

chore: add promotion counter to grafana dashboard for apps

---

.github/workflows/CI.yaml
.github/workflows/component-test.yml
.github/workflows/e2e-test.yml
.github/workflows/golangci-lint.yml
.github/workflows/integration-test.yml
.github/workflows/load-test.yml
.github/workflows/markdown-checks.yaml
.github/workflows/release.yml
.github/workflows/security-scans.yml
.golangci.yml
keptn-cert-manager/Dockerfile
lifecycle-operator/Dockerfile
metrics-operator/Dockerfile
scheduler/Dockerfile

Follow up for the failing security check:
https://github.com/keptn/lifecycle-toolkit/pull/3217

chore: bump Go base images and pipelines version to 1.21

---

docs/docs/contribute/software/dev-environ.md

This pull request addresses a minor documentation inaccuracy. Previously, the [second point ](https://keptn.sh/stable/docs/contribute/software/dev-environ/)in the first step section mentioned pushing the image to a GitHub repository (intended destination is Docker Hub). This change clarifies the paragraph to reflect the correct behavior: the command pushes the built image to Docker Hub.

docs: correct container image reference to dockerhub

---

README.md
docs/docs/contribute/software/dev-environ.md

docs: remove duplicated sections from README

---

.github/actions/deploy-keptn-on-cluster/action.yml
.github/workflows/CI.yaml
.github/workflows/component-test.yml
.github/workflows/e2e-test.yml
.github/workflows/github-repo-stats.yml
.github/workflows/golangci-lint.yml
.github/workflows/htmltest.yaml
.github/workflows/integration-test.yml
.github/workflows/load-test.yml
.github/workflows/markdown-checks.yaml
.github/workflows/release-examples.yml
.github/workflows/release.yml
.github/workflows/security-scans.yml
.github/workflows/spell-checker.yml
.github/workflows/stale.yml
.github/workflows/update-labels.yml
.github/workflows/validate-helm-chart.yml
.github/workflows/validate-semantic-pr.yml
.github/workflows/yaml-checks.yaml

- changes pin annotations from `# pin@v2` to `# v2` so that renovate understands it correctly
- [link](https://docs.renovatebot.com/modules/manager/github-actions/#additional-information) to the renovate docs for this feature

ci: pin GHA deps correctly for renovate

---

.github/scripts/.helm-tests/lifecycle-only/result.yaml
.github/scripts/.helm-tests/lifecycle-only/values.yaml

This PR exchanges the made-up `myrep` docker repo for busybox to make renovate happy and remove some "not found" errors. Busybox is already in the list of ignored deps so it shouldn't be any additional deps burden for the team.

chore: remove not found docker repo

---

.github/workflows/CI.yaml
.github/workflows/component-test.yml
.github/workflows/e2e-test.yml
.github/workflows/golangci-lint.yml
.github/workflows/htmltest.yaml
.github/workflows/integration-test.yml
.github/workflows/load-test.yml
.github/workflows/markdown-checks.yaml
.github/workflows/release-examples.yml
.github/workflows/release.yml
.github/workflows/security-scans.yml
.github/workflows/validate-helm-chart.yml
.github/workflows/yaml-checks.yaml

- pins actions/checkout to the specific v4.1.1 version instead of v4
- pins the docker/build-push-action to the specific v5.1.1 version instead of v5

ci: pin some more github actions to specific versions

---

.github/actions/spelling/expect.txt
docs/blog/.authors.yml
docs/blog/posts/stable-release-announcement.md

This blogpost was initially prepared by @agardnerIT 
Since he's currently traveling, he asked me to post it :)

docs: new blog post for release candidate

---

.chainsaw.yaml
test/chainsaw/testcertificate/cert-recreates/00-assert.yaml
test/chainsaw/testcertificate/cert-recreates/01-assert.yaml
test/chainsaw/testcertificate/cert-recreates/02-assert.yaml

Since the `testcertificate` integration test does restart `lifecycle-operator` and `metrics-operator` Deployments, it should properly assert that the pods are running after the restart. If this is not the case after the restart -> chainsaw continues with another test (`non-blocking-deployment`), but since the pods are not yet up and running, it fails.
Also there was a need to increase the `execTimeout` in the chainsaw configuration to allow the scripts with retry logic to be executed for longer than the default 5s

fix: assert keptn-cert-manager integration test more precisely

---

.github/scripts/generate-crd-docs/generate-crd-docs.sh
.github/scripts/generate-crd-docs/templates/type.tpl
docs/docs/reference/api-reference/lifecycle/v1alpha1/index.md
docs/docs/reference/api-reference/lifecycle/v1alpha2/index.md
docs/docs/reference/api-reference/lifecycle/v1alpha3/index.md
docs/docs/reference/api-reference/lifecycle/v1alpha4/index.md
docs/docs/reference/api-reference/lifecycle/v1beta1/index.md
docs/docs/reference/api-reference/metrics/v1alpha1/index.md
docs/docs/reference/api-reference/metrics/v1alpha2/index.md
docs/docs/reference/api-reference/metrics/v1alpha3/index.md
docs/docs/reference/api-reference/metrics/v1beta1/index.md
docs/docs/reference/api-reference/options/v1alpha1/index.md

This pr adds the validation field in our autogenerated crd docs, this way it is possible to see expected values for those fields that have a validation webhook.
🛑  This pr currently uses unreleased version of crd gen tool thus it must wait for an official release before merge!
Fixes  #2292
example validation field https://keptn--3068.org.readthedocs.build/3068/docs/reference/api-reference/metrics/v1beta1/#totalscore

chore: bump elastic/crd-ref-docs to 0.0.11 to enable validation field in docs

---

docs/docs/contribute/docs/linter-requirements.md
runtimes/python-runtime/Dockerfile

security scan: https://github.com/keptn/lifecycle-toolkit/actions/runs/8294452725

fix(python-runtime): bump libexpat to v2.6.2

---

docs/docs/guides/assets/multi-stage-delivery/application-production.yaml
docs/docs/guides/multi-stage-application-delivery.md

The spanLinks attribute was missing in the example, leading to some confusion about how the deployment traces are actually connected with each other

docs: add missing span link to example

---

docs/blog/posts/stable-release-announcement.md
mkdocs.yml

- adjusts the release candidate blogpost title so that it fits into the social card while sharing (see screenshot)
- set the post slug to the old one so that the URL that is already released stays the same as before
- adjusts the social card background color to use the default Keptn color

docs: reduce blogpost title length to fit into social card

---

lifecycle-operator/apis/lifecycle/v1beta1/keptnappversion_types.go
lifecycle-operator/apis/lifecycle/v1beta1/keptnappversion_types_test.go
lifecycle-operator/apis/lifecycle/v1beta1/keptnworkloadversion_types.go
lifecycle-operator/apis/lifecycle/v1beta1/keptnworkloadversion_types_test.go

This PR adds namespace attributes to both `keptn_app_deploymentduration` and `keptn_deployment_deploymentduration` metrics.
All other DORA specific metrics include either the `keptn_deployment_app_namespace` or the `keptn_deployment_workload_namespace`, except for the `_deploymentduration`. This PR fixes that.
This is useful for our usecase where we want to filter deploymentduration per namespace instead of per app.
Unit tests have been updated, manual verification was done to check if these namespace attributes are present on the exported metrics at `localhost:2222/metrics`.

feat(lifecycle-operator): add namespace to `deploymentduration` metrics

---

README.md
docs/docs/components/lifecycle-operator/webhook.md
mkdocs.yml

docs: move webhook section from README to docs

---

docs/docs/guides/assets/auto-app-discovery/deployments.yaml

This PR fixes our example podtato head deployment in the autodiscovery app guide.

docs: fix missing registry and selector from example podtatohead

---

README.md

- removes the detailed docs description
- fixes some broken links
- fixes #3255

docs: remove details docs intro, fix some links

---

.github/actions/spelling/expect.txt
docs/docs/contribute/docs/blog.md
mkdocs.yml

How to post a blog in the Keptn docs
Fixes https://github.com/keptn/lifecycle-toolkit/issues/3212
- [xI signed off all my commits according to the Developer Certificate of Origin (DCO)(

docs: how to create a blog post

---

docs/docs/contribute/general/contrib-guidelines-gen.md
docs/docs/contribute/general/git/branch-create.md
docs/docs/contribute/general/git/fork-clone.md
docs/docs/contribute/general/git/index.md
docs/docs/contribute/general/git/pr-create.md
docs/docs/contribute/general/git/review.md
docs/docs/contribute/general/index.md
docs/docs/contribute/index.md
docs/docs/contribute/software/index.md

This PR does the following:
- Remove "under development" disclaimer for "General" and "Software" sections of the "Contributing" guide
- Adds brief description of the sub-sections of the "Contributing" guide on the main landing page
- Adds brief description of the "General" section on that landing page
- Adds brief description of the "Software contributions" section on that landing page
- Adds some xrefs and content enhancements to "General" sub-sections
- [n/a] My PR fulfills the Definition of Done of the corresponding issue and not more (or parts if the issue is separated
- [n/a] I …

docs: improve landing pages for Contrib Guide

---

.github/actions/spelling/expect.txt
.markdownlint-cli2.yaml
docs/docs/use-cases/assets/keda/k-describe-metric.txt
docs/docs/use-cases/assets/keda/k-describe-scaledobject.txt
docs/docs/use-cases/assets/keda/k-get-pods-result.txt
docs/docs/use-cases/assets/keda/keptnmetric.yaml
docs/docs/use-cases/assets/keda/keptnmetricsprovider.yaml
docs/docs/use-cases/assets/keda/sample-app.yaml
docs/docs/use-cases/assets/keda/sample-service.yaml
docs/docs/use-cases/assets/keda/scaledobject.yaml
docs/docs/use-cases/hpa.md
docs/docs/use-cases/keda.md
mkdocs.yml

- fixes #2899 
- sets up a use case page on how to set up KEDA to consume keptn metrics

docs: add use case page for KEDA

---

mkdocs.yml

Disabling due to problem described here
https://github.com/squidfunk/mkdocs-material/issues/6983.
After resolving it, the plugin can be enabled again.

docs: temporary disable mkdocs social plugin

---

.github/actions/spelling/expect.txt
.github/scripts/.helm-tests/default/result.yaml
.github/scripts/.helm-tests/local-global-precedence/result.yaml
.github/scripts/.helm-tests/metrics-only-with-apiservice-disabled/result.yaml
.github/scripts/.helm-tests/metrics-only/result.yaml
.github/scripts/.helm-tests/metrics-with-certs/result.yaml
docs/docs/assets/crd/examples/yaml-synopsis.yaml
docs/docs/components/metrics-operator.md
docs/docs/contribute/software/add-new-metric-provider.md
docs/docs/core-concepts/index.md
docs/docs/getting-started/metrics.md
docs/docs/installation/k8s.md
docs/docs/migrate/keptn/strategy.md
docs/docs/reference/api-reference/metrics/v1/index.md
docs/docs/reference/crd-reference/analysisvaluetemplate.md
docs/docs/reference/crd-reference/evaluationdefinition.md
docs/docs/reference/crd-reference/metricsprovider.md
docs/docs/use-cases/non-k8s.md
metrics-operator/api/v1/keptnmetricsprovider_types.go
metrics-operator/api/v1/keptnmetricsprovider_types_test.go
metrics-operator/chart/templates/keptnmetricsprovider-crd.yaml
metrics-operator/config/crd/bases/metrics.keptn.sh_keptnmetricsproviders.yaml
metrics-operator/controllers/analysis/provider_selector_test.go
metrics-operator/controllers/common/providers/common.go
metrics-operator/controllers/common/providers/provider.go
metrics-operator/controllers/common/providers/provider_test.go

Fixes: #2903 
Prometheus and Cortrex metrics providers have 100% compatible API, see [here](https://cortexmetrics.io/docs/configuration/v1guarantees/#api-compatibility)
metrics provider uses only single [api endpoint](https://prometheus.io/docs/prometheus/latest/querying/api/#range-queries), which is same for Cortex as well, see [here](https://cortexmetrics.io/docs/api/#range-query)

feat(metrics-operator): support Cortex metrics provider

---

docs/blog/.authors.yml

This PR implements "Keptn Maintainer", etc in the `.authors.yml` file.  This makes us a little more "multicultural" as we get blog contributions from other projects and other companies.

docs: use "Keptn Maintainer" for blog authors

---

.github/scripts/.helm-tests/Openshift/result.yaml
.github/scripts/.helm-tests/default/result.yaml
.github/scripts/.helm-tests/lifecycle-only/result.yaml
.github/scripts/.helm-tests/lifecycle-only/values.yaml
.github/scripts/.helm-tests/lifecycle-with-certs/result.yaml
.github/scripts/.helm-tests/local-global-precedence/result.yaml
lifecycle-operator/chart/README.md
lifecycle-operator/chart/templates/deployment.yaml
lifecycle-operator/chart/values.yaml
lifecycle-operator/config/manager/manager.yaml

This PR adds the ability to set the .spec.template.spec.hostNetwork value for the lifecycle-operator deployment in the helm-chart values. By default it will be set to `false`.
This is required due to the webhook being blocked while using Cilium on managed Amazon EKS clusters. This makes it so other deployments won't be able to deploy on our clusters.
Added the default values to `.github/scripts/.helm-tests`.

feat(helm-chart): ability to set hostNetwork for lifecycle operator deployment

---

docs/docs/getting-started/observability.md
examples/support/observability/config/prometheus/grafana-dashboard-keptn-applications.yaml
examples/support/observability/config/prometheus/grafana-dashboard-keptn-overview.yaml
examples/support/observability/config/prometheus/grafana-dashboard-keptn-workloads.yaml

1. helm value overide:
`sidecar.datasources.defaultDatasourceEnabled: false`
this format has no effect, should be like 
```
sidecar:
datasources:
defaultDatasourceEnabled: false
```
2. dashboard label 
grafana_dashboard should be "1"
grafana-sc-dashboard containers watch 
- name: LABEL
value: "grafana_dashboard"
- name: LABEL_VALUE
value: "1"
with lable=0 currently, follow the document example deployment, Grafana will not have the corresponding Dashboard.

fix(examples): helm values overide format and dashboard fix

---

lifecycle-operator/controllers/lifecycle/keptnappversion/controller_test.go

Added a unit test for the non-blocking lifecycle operator mode. 
I used the manifest provided in the [docs](https://keptn.sh/stable/docs/components/lifecycle-operator/keptn-non-blocking/) as the template for the unit test. 
Since the non-blocking mode does not introduce any errors in the controller, we can write a unit test with a mock handler that does not return any errors when using the manifest provided in the docs. 
Partially Fixes # (#3121)
I use the run test option in VSCode to verify that my tests works. 
see [Contribution …

chore: introduce unit test for non-blocking lifecycle operator mode

---

keptn-cert-manager/eventfilter/eventfilter_test.go
keptn-cert-manager/kubeutils/certificates_test.go
keptn-cert-manager/kubeutils/secret_test.go
keptn-cert-manager/pkg/certificates/watcher_test.go

This PR aims to improve the test coverage of Keptn-cert-manager components
Fixes #3038
```
eventfilter: 60.0% of statements
kubeutils: 69.7% of statements
pkg/certificates: 73.1% of statements
```

test: enhance test coverage for keptn-cert-manager

---

examples/support/metrics/metric.yaml

for some reason, the keptnmetric doesn't work with the keptn provided range options

fix(examples): fix KeptnMetric in metrics example

---

.github/actions/spelling/expect.txt
lifecycle-operator/config/crd/bases/lifecycle.keptn.sh_keptntaskdefinitions.yaml
lifecycle-operator/webhooks/pod_mutator/handlers/workload.go
lifecycle-operator/webhooks/pod_mutator/handlers/workload_test.go
test/chainsaw/integration/simple-deployment-revisionhistorylimit/00-assert.yaml
test/chainsaw/integration/simple-deployment-revisionhistorylimit/00-install.yaml
test/chainsaw/integration/simple-deployment-revisionhistorylimit/01-assert.yaml
test/chainsaw/integration/simple-deployment-revisionhistorylimit/01-install.yaml
test/chainsaw/integration/simple-deployment-revisionhistorylimit/chainsaw-test.yaml

When updating KeptnWorkload after an update of the workload, ownerReference should be updated as well
Fixes #3680

fix(lifecycle-operator): update ownerReference when updating KeptnWorkload

---

.github/scripts/.helm-tests/Openshift/result.yaml
.github/scripts/.helm-tests/default/result.yaml
.github/scripts/.helm-tests/local-global-precedence/result.yaml
.github/scripts/.helm-tests/metrics-only-with-apiservice-disabled/result.yaml
.github/scripts/.helm-tests/metrics-only/result.yaml
.github/scripts/.helm-tests/metrics-with-certs/result.yaml
docs/docs/reference/api-reference/metrics/v1/index.md
metrics-operator/api/v1/keptnmetricsprovider_types.go
metrics-operator/chart/templates/keptnmetricsprovider-crd.yaml
metrics-operator/config/crd/bases/metrics.keptn.sh_keptnmetricsproviders.yaml
metrics-operator/controllers/analysis/fake/evaluator_mock.go
metrics-operator/controllers/analysis/objectives_evaluator.go
metrics-operator/controllers/analysis/objectives_evaluator_test.go
metrics-operator/controllers/analysis/provider_selector.go
metrics-operator/controllers/analysis/provider_selector_test.go
metrics-operator/controllers/common/providers/dynatrace/dynatrace_dql.go
metrics-operator/controllers/common/providers/provider.go
metrics-operator/controllers/common/providers/provider_test.go
metrics-operator/controllers/metrics/controller.go
metrics-operator/controllers/metrics/controller_test.go

Fixes: #3678 
https://github.com/keptn/lifecycle-toolkit/issues/3712
- introduced new parameter to skip tls certificate verification
- adapted interfaces and functions to use this parameter

feat(metrics-operator): introduce insecureSkipTlsVerify parameter

---

.github/workflows/stale.yml

This PR adds a new "never-stale" label to prevent the stale bot from closing old issues.

ci: add never-stale label

---

docs/docs/components/lifecycle-operator/keptn-apps.md
docs/docs/guides/integrate.md

- adding a NOTE to integrate.md 
- adding the Note to the architectural with a brief explanation  
Fixes #3540 

docs: explain that part-of and name annotations are concatenated

---

.github/actions/deploy-keptn-on-cluster/action.yml
lifecycle-operator/controllers/lifecycle/keptntask/job_utils.go
lifecycle-operator/controllers/lifecycle/keptntask/job_utils_test.go
test/chainsaw/integration/TTLSecondsAfterFinished-in-jobs/00-assert.yaml
test/chainsaw/integration/container-runtime/00-assert.yaml
test/chainsaw/integration/imagepullsecret/00-assert.yaml
test/chainsaw/integration/simple-deployment-python-runtime/00-assert.yaml
test/chainsaw/integration/simple-deployment-recursive-task/00-assert.yaml

feat: add support for Kubernetes v1.31

---

docs/docs/reference/crd-reference/analysis.md

Added the code annotations to the Analysis reference pages in the JSON code block & removed the below made description of the code block.
Please review my changes.
Fixes #3040

docs: add code annotations in analysis reference page

---

test/chainsaw/testmetrics/metrics-keda/chainsaw-test.yaml

There is no need to wait for cleanup of KEDA resources (which takes time+resources and often times out) after KEDA integration test as the cluster will be deleted after the test is finished even if the uninstallation is not done yet.

chore: remove waiting after KEDA integration test cleanup

---

docs/docs/guides/assets/auto-app-discovery/deployments.yaml

The observability guide [here](https://keptn.sh/stable/docs/guides/auto-app-discovery/) includes deployment manifests whose `selector.matchLabels` does not match the template's `metadata.labels`.  This results in an error when trying to apply the manifest.
Specifically, the error is:
```
Error from server (Invalid): error when creating "sample-deployment.yaml": Deployment.apps "podtato-head-frontend" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"app.kubernetes.io/name":"podtato-head-frontend", "app.kubernetes.io/part-of":"podtato-head", "app.kubernetes.io/version":"0.1.0"}: `selector` does not match template `labels`
Error from server (Invalid): error when creating "sample-deployment.yaml": Deployment.apps "podtato-head-hat" is invalid: …
```

docs: correct match selector section in auto app discovery guide

---

metrics-operator/controllers/common/providers/elastic/elastic.go
metrics-operator/controllers/common/providers/elastic/elastic_test.go

fixes a bug for  https://github.com/keptn/lifecycle-toolkit/issues/3727
Hey @mowies @odubajDT  there is a small bug when using elastic as a provider. Previously we have not included the provider info now I have modified to include it. Can you please have a look at this? It is a continuation of the PR https://github.com/keptn/lifecycle-toolkit/pull/3890

fix: fix a bug when elastic as a provider 
